Unidata/MetPy

- metpy/calc/tests/test_turbulence.py
- metpy/calc/turbulence.py
Added calculations and tests for kinematic fluxes and friction velocity.
> More turbulence calculations

- docs/source/developerguide.rst
- docs/source/index.rst
Add page describing various elements of development.
> Add developer docs. (Fixes #29)

- metpy/calc/basic.py
- metpy/calc/thermo.py
Mainly fixes #46 , but also catches an issue with the example for `potential_temperature()`.
> Documentation fixes

- metpy/io/nexrad.py
- metpy/io/tests/test_nexrad.py
With tests that detect problem.
> Fix use of zip() on Python 3 (Fixes #55).

- README.rst
Add some information about the general philosophy of the project: goals,
scope, audience, etc.
> Readme improvements. (Fixes #53)

- metpy/calc/basic.py
- metpy/calc/tests/test_basic.py
> Split wind speed and direction calculation

- metpy/calc/kinematics.py
> Fixed the doc string for geostrophic wind

- README.rst
- docs/source/developerguide.rst
- environment.yml
Add conda development environment config, update dev instructions, and add some binstar package badges.
> Conda information

- docs/source/conf.py
So our docs have (silently) had build problems for the last month. Lovely.
> Fix mocking problem with pint.

- appveyor.yml
- environment.yml
- metpy/plots/skewt.py
- metpy/plots/tests/test_ctables.py
Test on windows using AppVeyor. Instead of using pip packaging, this uses conda packages, requiring `environment.yml` to be current.
> Set up AppVeyor

- metpy/calc/basic.py
- metpy/calc/tests/test_basic.py
See #178 for description of the problem.
> Fix 180 degree offset in wind direction calculation

- docs/source/installguide.rst
> MNT: Fix link to examples.

- docs/source/installguide.rst
> MNT: Source build to use pip.

- metpy/calc/tests/test_thermo.py
- metpy/calc/tests/test_tools.py
- metpy/calc/thermo.py
- metpy/calc/tools.py
Add a way to more precisely calculate the LFC by solving for the intersection of two line segments that bracket it. Addresses #200
> LFC calculation

- metpy/calc/basic.py
- metpy/calc/tests/test_basic.py
> Coriolis Force Calculation

- CLA.md
- CONTRIBUTING.md
- CONTRIBUTORS.md
- Add CONTRIBUTORS.md listing people who have contributed to the project
- Add a document describing the CLA now that we have one.
> Updates for contributors

- metpy/calc/tests/test_thermo.py
- metpy/calc/thermo.py
Fixes #232--it turns out it was just the combination of handling a bad end point/corner case and weird plotting.
I also went ahead and did some clean up of the tests and docstrings.
> Fix parcel_profile

- docs/source/installguide.rst
- metpy/io/cdm.py
- metpy/io/gini.py
- metpy/io/nexrad.py
- metpy/io/tests/test_gini.py
- metpy/io/tests/test_nexrad.py
- metpy/io/tools.py
- metpy/plots/_mpl.py
- metpy/plots/station_plot.py
- metpy/plots/tests/test_mpl.py
A bunch of small things to try to get this bugfix release out the door.
- Fix datetime in NEXRAD #244 
- Fix small station plot bug with PathEffects #245 
- Add Conda to installation instructions #246 
- Fix GINI polar stereographic images #233
> Small fixes

- .travis.yml
- appveyor.yml
- Give some more build information when uploading to codecov; this should make it easier to decipher what's been uploaded
- Upload results from pytest to AppVeyor--we'll actually see the tests run and results in the web interface.
> CI enhancements

- metpy/plots/skewt.py
- Remove log minor tick labels introduced in matplotlib 2.0 (#257)
- Refactor and clean up
- Fix extra whitespace (#158) with test
> SkewT Fixes

- .travis.yml
- appveyor.yml
- conftest.py
- examples/notebooks/GINI_Water_Vapor.ipynb
- examples/notebooks/NEXRAD_Level_2_File.ipynb
- examples/notebooks/NEXRAD_Level_3_File.ipynb
- metpy/gridding/interpolation.py
- metpy/gridding/points.py
- metpy/gridding/tests/test_interpolation.py
- metpy/gridding/tests/test_points.py
- metpy/io/_tools.py
- metpy/io/gini.py
- metpy/io/nexrad.py
- metpy/io/tests/test_gini.py
- metpy/io/tests/test_nexrad.py
- metpy/io/tests/test_upperair.py
- metpy/package_tools.py
- metpy/plots/ctables.py
- metpy/plots/tests/test_ctables.py
- metpy/plots/tests/test_mpl.py
- metpy/plots/tests/test_skewt.py
- metpy/plots/tests/test_station_plot.py
- metpy/testing.py
Some updates and removals since we're now on pytest 0.7 (and just in general). Also cleaned up some imports and added some more information to the default pytest output.
Will also be adding a bit more clean up of minor issues.
> Various odd and ends

- .gitignore
- .landscape.yml
- MANIFEST.in
- docs/conf.py
- docs/index.rst
- setup.cfg
- tutorials/README.txt
- tutorials/upperair_soundings.py
Very rough draft of an upper air example tutorial/notebook. I'm working on the LFC calculation to make this better. Any thoughts on things to add appreciated. I was thinking of adding some videos on thermo/skew-t, but maybe that's beyond scope?
Also, where should this live. Maybe we need to make a user's guide folder in docs?
> Upper air tutorial

- environment.yml
Fix appveyor failing image testing.
> Fix Appveyor Testing

- examples/plots/Station_Plot.py
- examples/plots/Station_Plot_with_Layout.py
Minor name change for making things consistent. Addresses #308
> Change Station Plot Examples to CF standard names

- CONTRIBUTING.md
- environment.yml
Cleanup small odds and ends from the 2/13-2/24 sprint. https://github.com/Unidata/python-general/issues/12
> Sprint cleanup

- examples/plots/Station_Plot.py
- examples/plots/Station_Plot_with_Layout.py
Fix examples per #290 - as far as I can tell only the station plots examples needed to be modified.
> Set edgecolor to black on state borders

- metpy/plots/fonts/wx_symbols_license.md
Added with a link to their repo and to the CC BY license. Should keep everything kosher? Addresses #227
> Add CC BY 4.0 license for weather symbol font

- docs/_templates/footer.html
This way we can actually see what of our docs is being used.
> ENH: Add google analytics to docs

- metpy/io/upperair.py
Fails gracefully if no data is available when requested from both Wyoming and IA State.
> Check if data exists when requested

- docs/api/calc.rst
- docs/api/tools.rst
- metpy/calc/tests/test_tools.py
- metpy/calc/tools.py
Add a utility and tests for interpolating NaN values per #349
> Interpolation utility

- docs/make.bat
Fix the `make clean` command so it actually runs on Windows.
> [MNT]: Fix clean

- docs/conf.py
Abort the build if the examples fail.
> Gallery Abort

- examples/formats/GINI_Water_Vapor.py
Update the example to use `img_extent` from #357
> Use new img_extent attribute in example

- metpy/plots/ctables.py
- metpy/plots/tests/test_ctables.py
Not sure if you want to implement this, but this is the functionality I was searching for with the satellite stuff. Unless I mis-understand the workflow in which people would use the colortable retrieval.
> Colortable get with range

- metpy/calc/tests/test_tools.py
- metpy/calc/tools.py
Uses a kd-tree to eliminate points within a radius of a given point; iterates through all the points, skipping those already eliminated. Can optionally use an array of values to assign priority.
Closes #90.
> ENH: Add tool to thin down point data (Fixes #90)

- CITATION.txt
- MANIFEST.in
- docs/citing.rst
- docs/index.rst
Good to do now that we have a DOI.
Closes #161.
> ENH: Add information for citing MetPy in publications

- metpy/calc/tests/test_tools.py
- metpy/calc/tools.py
- metpy/plots/skewt.py
Makes the Skew-T and related plotting functionality play nice with masked data points.
> Skew T Masked Data

- .travis.yml
- docs/conf.py
Pin pydocstyle and update the sphinx-gallery configuration to get the build lights green again.
> Build maintenance

- metpy/calc/kinematics.py
- metpy/calc/tests/test_kinematics.py
This pull request adds calculations of shearing and stretching deformation with tests.
> Adding shearing and stretching deformation calcs

- metpy/calc/basic.py
- metpy/calc/tests/test_basic.py
These helpers let us get heights and pressures above other heights and pressures. Really useful when figuring different layer heights and thicknesses. I don't love the spelling currently - maybe we should also be clarifying that they are deltas?
> Pressure height helpers

- metpy/io/tests/test_upperair.py
- metpy/io/upperair.py
Modifies the get_upper_air_data function to pull in height data with soundings from the Wyoming or Iowa State archives.
> Have get_upper_air_data bring in height data.

- metpy/calc/tests/test_tools.py
- metpy/calc/tools.py
Add utilities to mix a variable in a layer and to get a mixed parcel.
Open Questions:
> Get Layer Function

- metpy/calc/thermo.py
Looks like in #446 there were some errors in rendering the equations and references. Quick maintenance PR to clean that up.
> Fix equation and reference rendering issues

- .travis.yml
- docs/installguide.rst
- setup.py
Changes Pint dependency to support units wrapper in log_interp.
> Change Pint dependency to version 0.8.

- docs/references.rst
- metpy/calc/basic.py
- metpy/calc/tests/test_basic.py
Simple sigma to pressure function to help with vertical interpolation,
etc. Reference and test included. Code style cleanup performed.
> Add sigma to pressure conversion

- metpy/calc/tests/test_tools.py
- metpy/calc/tools.py
Adds ability to interpolate along a given axis of n-dimensional data to log_interp. Fixes #293. Will likely use this in #454 after it has been merged.
> Log interpolation

- metpy/calc/tests/test_tools.py
- metpy/calc/tools.py
This fixes a bug in interp where nan would be returned when a interpolation to the endpoints of the data was requested. A test has been added for this case.
> Interp Bug Fix

- metpy/constants.py
Cleans up two issues in the documentation of constants. Closes #479
> Constants documentation

- examples/plots/Station_Plot.py
Modified Station_Plot.py example so that it provides an example of how metpy.calc.reduce_point_density can be used for station plotting. 
Closes #460 .
> Reduce point density in Station_Plot.py example

- .github/CODEOWNERS
- README.rst
- SUPPORT.md
- docs/references.rst
- metpy/calc/thermo.py
Adds SUPPORT and CODEOWNERS files. Closes #522 
Do we need/want to link to SUPPORT anywhere in README?
> GitHub enhancements

- metpy/calc/kinematics.py
- metpy/calc/tests/test_kinematics.py
Added a function to calculate storm-relative helicity and a test for said function. A storm motion vector and the layer over which SRH is to be calculated can be specified.
> Added a function to calculate storm-relative helicity given a storm motion vector and a wind profile.

- examples/sigma_to_pressure_interpolation.py
Adds an example of using log_interp to interpolate from sigma to isobaric coordinates. Also adds example WRF dataset.
> Sigma to Pressure Interpolation Example

- metpy/calc/indices.py
- metpy/calc/thermo.py
- metpy/calc/tools.py
- Denote optional arguments in docs
- Rename function arguments from "p" to "pressure" (these haven't been released yet, so we can do this at will)
- Fix a few typos
> Doc cleanup

- metpy/calc/indices.py
- metpy/calc/tests/test_indices.py
Adds a function to calculate the pressure-weighted mean wind through a layer.
> Pressure-Weighted Mean

- examples/Advanced_Sounding.py
- tutorials/upperair_soundings.py
Use shade_cape and shade_cin in examples. Closes #538
> Update to shade helpers in docs

- CLA.md
- docs/CONTRIBUTING.md
This one has better features and seems more maintained.
> MNT: Move from clahub to cla-assistant for CLA handling

- docs/CONTRIBUTING.md
We need a guiding set of principles to remind ourselves and contributors of what it takes to maintain and add to an amazing scientific library. Feel free to add, subtract, suggest, modify.
> Zen and the Art of MetPy Maintenance

- metpy/calc/tests/test_thermo.py
- metpy/calc/thermo.py
Calculate the properties of a mixed layer and mixed parcel. A few things to consider when looking over the code before I get into tests.
@mwilson14 and @tjwixtrom were wanting this functionality so any thoughts on the versatility/interface would be good.
> Mixed parcel and layer

- docs/references.rst
- metpy/calc/indices.py
- metpy/calc/tests/test_indices.py
Adds calculations for supercell comp. and significant tornado parameters, along with tests and a reference.
> Supercell Composite and Significant Tornado Parameters

- metpy/cbook.py
- metpy/io/_tools.py
- metpy/io/gini.py
- metpy/io/nexrad.py
> Remove is_string_like

- metpy/calc/tests/test_tools.py
- metpy/calc/tools.py
Check for and remove the duplicates as the most straight forward solution. See the discussion in the issue. Closes #467
> Fix duplication of intersections in find_intersections

- .gitignore
- metpy/calc/tests/test_indices.py
- metpy/io/tests/test_upperair.py
- metpy/plots/tests/test_skewt.py
- metpy/tests/test_units.py
- metpy/units.py
- setup.cfg
It seems like this works well now with matplotlib 2.0.2 and master.
Let's hook this up properly then.
> ENH: Fully implement matplotlib/pint integration

- .gitattributes
- examples/isentropic_example.py
- metpy/io/_nexrad_msgs/parse_spec.py
Found by LGTM/Codacy.
Mainly just a PR to exercise the org CLA stuff, but might as well do something useful. 😁
> MNT: Fix up a few minor issues

- README.rst
- docs/index.rst
> Add the Unidata Python Gallery link to the MetPy README

- .travis.yml
- CONTRIBUTING.md
- docs/index.rst
- examples/Four_Panel_Map.py
- examples/gridding/Inverse_Distance_Verification.py
- examples/plots/Station_Plot.py
- examples/plots/Station_Plot_with_Layout.py
- metpy/calc/tests/test_thermo.py
- metpy/calc/thermo.py
- metpy/io/_tools.py
- metpy/plots/_mpl.py
- metpy/plots/skewt.py
- setup.py
- tutorials/upperair_soundings.py
- Relocate where we require recommon, since we can't build without it
- A few fixes for the contributor's guide
- Hide the table of contents from the doc landing page--this still leaves it in the side bar
> Doc updates

- examples/Advanced_Sounding.py
- examples/Four_Panel_Map.py
- examples/formats/GINI_Water_Vapor.py
- examples/gridding/Point_Interpolation.py
- examples/gridding/Wind_SLP_Interpolation.py
- examples/sigma_to_pressure_interpolation.py
Sir if this is correct I will add for other examples too. Please review.
> Add metpy logo for few plots.

- metpy/calc/tests/test_indices.py
- metpy/calc/tools.py
- metpy/plots/__init__.py
Closes #596 by cleaning up our floating point logic that manifested in some sounding data.
> get_layer bounds improvements

- examples/Advanced_Sounding.py
- examples/Four_Panel_Map.py
- examples/formats/GINI_Water_Vapor.py
- examples/formats/NEXRAD_Level_2_File.py
- examples/formats/NEXRAD_Level_3_File.py
- examples/gridding/Point_Interpolation.py
- examples/gridding/Wind_SLP_Interpolation.py
- examples/isentropic_example.py
- examples/meteogram_metpy.py
- examples/plots/Hodograph_Inset.py
- examples/plots/Simple_Sounding.py
- examples/plots/Skew-T_Layout.py
- examples/plots/Station_Plot.py
- examples/plots/Station_Plot_with_Layout.py
- examples/sigma_to_pressure_interpolation.py
Add logos to more examples and improve the positioning of the logos. Probably the best way to review is build the docs and have a look! Closes #563
> Improve logo positioning

- metpy/calc/tests/test_thermo.py
- metpy/calc/thermo.py
Add calculations for dry and moist static energy. Will need page numbers from the older Wallace and Hobbs or another reference. This will be useful for #606 as well.
> Static energy calculations

- .appveyor.yml
- .travis.yml
- docs/Makefile
- docs/conf.py
- docs/make.bat
- environment.yml
- metpy/calc/basic.py
- metpy/calc/tools.py
- Fix up a bit of RST markup--one of these caused poor rendering
- Regenerate `Makefile` and `make.bat` since sphinx-build can handle much more internally now
- Re-enable build on AppVeyor
Closes #312
> Docs cleanup

- metpy/calc/indices.py
- metpy/calc/tests/test_indices.py
> Indices scalar input

- metpy/calc/tests/test_thermo.py
- metpy/calc/tests/test_tools.py
- metpy/calc/tests/test_turbulence.py
- metpy/calc/thermo.py
As a part of resolving issue #295, this adds a calculation to convert from RH to mixing ratio, given temperature and pressure data.
> Add a Mixing Ratio from RH Calculation

- metpy/calc/tests/test_thermo.py
- metpy/calc/thermo.py
I added a function to calculate relative humidity from temperature and dewpoint to calc (metpy.calc.relative_humidity_from_dewpoint) for issue #648
This is my first ever pull request to an open source project, if there's anything I've done wrong please feel free to let me know.
> Add relative humidity calculation from dewpoint function

- docs/gempak.rst
- docs/index.rst
A table to help GEMPAK users convert to MetPy. This is a rough equivalency table. There's still a lot of testing to do, equivalency entries, etc. It's a start though. A few things to workup before merging:
Feedback on things I've missed in this first cut, other formatting things, etc welcome.
> GEMPAK Conversion Table

- examples/isentropic_example.py
Changed extend value in colorbar call to 'max'
Removed figure number 1 from the figure call
Added call to plt.show at the end of script
Changed unpacking interpolation results
> Clean up isentropic interpolation example

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.rst
- docs/index.rst
Adds a code of conduct for MetPy - Comments and discussion welcome before merging.
> Add Code of Conduct

- metpy/calc/tools.py
This addresses issue #700.
Added @exporter.export above the gradient function.
> Export gradient

- setup.cfg
Ignore print statements in examples and tutorials.
> Fix Example/Tutorial Flake

- .gitignore
- docs/index.rst
> Add AMS talk

- metpy/calc/kinematics.py
- metpy/calc/tests/test_kinematics.py
Closes #660 by adding an ageostrophic wind calculation. Trivial, yes, but it is a GEMPAK calculation.
> Ageostrophic wind

- metpy/calc/tests/test_thermo.py
- metpy/calc/thermo.py
Trying to implement the conversion from potential temperature at a given pressure level to temperature #702. It simply inverts the equation given in `potential_temperature`, hope that this is the correct approach.
Comments welcome.
> Add potential temperature to temperature conversion

- metpy/calc/kinematics.py
- metpy/calc/tests/test_kinematics.py
Closes #657 adding absolute vorticity and preparing for EPV and others.
> Absolute vorticity

- examples/Four_Panel_Map.py
- examples/formats/GINI_Water_Vapor.py
- examples/gridding/Point_Interpolation.py
- examples/gridding/Wind_SLP_Interpolation.py
- examples/isentropic_example.py
- examples/plots/Station_Plot.py
- examples/plots/Station_Plot_with_Layout.py
- examples/sigma_to_pressure_interpolation.py
Update state and coastline features for Cartopy 0.16
> CartoPy Updates

- metpy/calc/tests/test_thermo.py
- metpy/calc/thermo.py
As discussed in #757, this adds the Exner function (as a function of pressure), and refactors `potential_temperature` and `temperature_from_potential_temperature` to use it.
Closes #757.
> Add Exner Function

- docs/developerguide.rst
- docs/installguide.rst
- docs/references.rst
- examples/gridding/Inverse_Distance_Verification.py
- examples/gridding/Natural_Neighbor_Verification.py
- examples/gridding/Point_Interpolation.py
- examples/gridding/Wind_SLP_Interpolation.py
- examples/isentropic_example.py
- examples/meteogram_metpy.py
- examples/sigma_to_pressure_interpolation.py
- tutorials/upperair_soundings.py
- Remove link redirects
- Fix link to WMO manual
- Eradicate unneeded use of pyplot in examples--this started as just trying to eliminate a matplotlib warning from running the examples and it...grew.
> Doc and example fixups

- metpy/calc/tests/test_thermo.py
- metpy/calc/thermo.py
Adds function to combine rh_from_specific_humidity and dewpoint_rh to get dewpoint from inputs of specific humidity, temperature, and pressure.
> Dewpoint From Specific Humidity

- examples/calculations/Parse_Angles.py
Adds an example of using the parse_angle function.
> Add example usage of parse_angle()

- examples/calculations/Gradient.py
- metpy/calc/tests/test_tools.py
- metpy/calc/tools.py
> Add tests for gradient

- examples/cross_section.py
This PR adds a basic example of cross section analysis using the NARR example dataset. It plots potential temperature, relative humidity, and projected winds, with an inset 500 hPa map with the cross section path depicted. The inset plot showing the path and the start and end coordinates themselves are borrowed from #518, but this was otherwise implemented to use xarray's plotting wrappers where possible, rather than the past approach.
> Add NARR Cross Section Example

- tutorials/unit_tutorial.py
Closes #905 by adding a tutorial on how to use units.
> Add unit tutorial

- metpy/cbook.py
Add v to beginning of version number for pooch search path.
> Fix pooch path

- examples/gridding/Point_Interpolation.py
- examples/gridding/Wind_SLP_Interpolation.py
- metpy/calc/basic.py
- metpy/calc/kinematics.py
- metpy/io/_nexrad_msgs/parse_spec.py
- metpy/io/gini.py
- metpy/io/nexrad.py
- tutorials/xarray_tutorial.py
- Silence a few more warnings. I think we're down to ones we don't control now.
- Flake8 fixes
- Update a copyright year
- Remove Matplotlib 3.0.0/CartoPy 0.16 incompatibility hacks--matplotlib 3.0.1 has been released (and the hacks actually break with 3.0.1)
> Miscellaneous Cleanup

- .appveyor.yml
- docs/_templates/overrides/metpy.calc.rst
- metpy/calc/basic.py
- metpy/calc/tests/test_basic.py
This PR adds a smoothing function for a 5 and 9 point smoother and closes issue #659
> Adds n point smoothing function

- .mailmap
- docs/index.rst
- docs/roadmap.rst
Best sketch of a roadmap, which was brainstormed after AMS 2019.
@kgoebber @jrleeman I'm going to merge as soon as the docs successfully build because I need a link to be valid for our status report. 😉 Feel free to submit issues or pull requests with improvements/clean up afterwards.
> Add roadmap document

- examples/Advanced_Sounding.py
Wasn't intuitive why the `0` index was selected when I first read it.
> Update Advanced Sounding doc to explain why 0 index is chosen

- metpy/calc/kinematics.py
> Update potential_vorticity_baroclinic() docstring

- AUTHORS.txt
- metpy/calc/thermo.py
Updated docstrings for pressure to go from high to low in profile calculations where this matters. Addresses #982
> Documentation update for pressure in profile calculations

- .github/CODEOWNERS
- .mailmap
- .travis.yml
- AUTHORS.txt
- LICENSE
Addresses 5/6 issues in #1083.
> MNT: Contributors, license, code owners

- setup.cfg
> MNT: suppress pytest-mpl warning for unregistered marker

- .travis.yml
- docs/_templates/layout.html
- docs/conf.py
- docs/index.rst
- docs/installguide.rst
- setup.py
- Ignore Youtube links with linkchecker to hopefully eliminate spurious Travis failures
- Update some redirecting links
- Replace deprecated method for including custom javascript
> Tweak docs

- .travis.yml
- README.rst
- conftest.py
- docs/installguide.rst
- metpy/plots/station_plot.py
- setup.py
Add pandas dependency (>=0.20.1). Also adds Xarray to dependency list in README
> Add Pandas dependency

- examples/Advanced_Sounding.py
- examples/plots/Hodograph_Inset.py
- examples/plots/Simple_Sounding.py
- examples/plots/Skew-T_Layout.py
- metpy/calc/basic.py
- metpy/calc/indices.py
- metpy/calc/kinematics.py
- metpy/calc/tests/test_basic.py
- metpy/calc/thermo.py
- metpy/future.py
- tutorials/upperair_soundings.py
Updates docstrings for more usage of `pint.Quantity` and consistent spelling of `dew point`. Also uses `@check_units` throughout several modules. Let me know if I changed something in error.
Note: I added `@check_units` to `wind_direction` and there was an explicit test to make sure that worked without units...I removed that test, but can add it back and remove the check if that was desired in the long term.
> Docstring updates and increased use of check_units

- metpy/plots/skewt.py
- metpy/plots/tests/test_skewt.py
Adds handles to the SkewT lines so that they can be removed if the call is provided twice. 
Temporary solution to fix #991 until we make these gridlines.
> Add handles to SkewT special lines

- metpy/plots/__init__.py
- metpy/plots/cartopy_utils.py
- metpy/plots/declarative.py
Make it so CartoPy imports are done as late as possible and are otherwise optional, so that you can install and import MetPy without CartoPy installed.
> Rearrange CartoPy Imports

- docs/index.rst
Adds a link to the Python gallery in the sidebar (named Topical Examples) and rewords the link to the MetPy examples as "Reference/API Examples".
> Add link to Python Gallery in sidebar

- src/metpy/xarray.py
In #1212, it was found that `_reassign_quantity_indexer` in `xarray.py` was modifying dictionary keys while iterating over the indexers dictionary. This refactors that helper function to perform the key replacement first, and then the value replacement, to clear up the issue.
> Refactor _reassign_quantity_indexer to avoid modifying dict keys while iterating

- setup.cfg
- src/metpy/calc/indices.py
- src/metpy/calc/kinematics.py
- src/metpy/future.py
- src/metpy/testing.py
- src/metpy/units.py
- tests/calc/test_indices.py
- tests/calc/test_kinematics.py
Changes the signature of `precipitable_water` and `storm_relative_helicity` to put the vertical coordinate first, to be consistent with other related calculations. This adds the new versions to the `future` module and makes the old versions forward on with a warning.
This also required updating some utility code.
> Update some function signatures

- examples/Four_Panel_Map.py
- examples/isentropic_example.py
This PR makes some maintenance changes to the example so that dates from xarray coordinate variables plot correctly.
> MNT: Update examples for date plotting

- src/metpy/plots/declarative.py
- tests/plots/test_declarative.py
- Fix up some declarative doc issues
- Make region trait do a case-insensitive look-up
> Declarative fixes

- src/metpy/plots/declarative.py
Closes #1297 with a minor doc cleanup.
> Clarify documentation on layers traits

- src/metpy/calc/kinematics.py
- tests/calc/test_kinematics.py
Closes #1287 - I used the extra transposes so the original intent of the test is still apparent, but they could be "cancelled" in a few cases. Probably not worth it, but open to debate.
> Remove dim_order

- src/metpy/calc/thermo.py
In saturation_mixing_ratio, add Notes section and move citation for implementation to Notes. Add an equation for the implementation.
> Update saturation_mixing_ratio docstring

- docs/_templates/footer.html
- Removing Inoperable 'Say Thanks' Link
- Closes #1377
> Removing 'Say Thanks' Link (#1377)

- .github/workflows/code-analysis.yml
Testing out running GitHub's CodeQL analysis (derivative of LGTM that they bought).
> ENH: Add workflow performing CodeQL analysis

- .gitattributes
- docs/_templates/overrides/metpy.calc.rst
- src/metpy/calc/tools.py
- tests/calc/test_calc_tools.py
Attempting to help finish this PR by fixing an error (the azimuth and ranges were reversed in saving from the meshgrid output and adding a test. Couldn't figure out how to add directly to the other PR, but this builds off of the one modified by @dopplershift.
> Latlon from azran

- src/metpy/calc/kinematics.py
- src/metpy/calc/thermo.py
Rewrite to forward on to dry_static_energy since they are identical calculations. Also add references to each other in the docstrings.
> MNT: Refactor montgomery_streamfunction

- docs/startingguide.rst
> replace data with ds

- tutorials/declarative_tutorial.py
This PR adds a declarative tutorial that has an example of gridded plotting and surface observation plotting.
For the gridded plotting there is a simple calculation (wind speed) done to demonstrate the MetPy 1.0 RC2 capability of getting back a DataArray, putting that in as a new variable to the Dataset, then plotting.
I've added descriptions of the attributes for each of the used declarative Classes.
Feedback on whether this is heading in the right direction would be welcome. Can add more explanations around some of the work as desired and add other examples as well.
> declarative tutorial

- .github/workflows/code-analysis.yml
- .github/workflows/release.yml
* Simplify CodeQL action (and remove a warning)
* Pin to a version of the PyPI upload action (rather than master 😬 )
> GH Action Workflow Updates

- README.md
Readme was referring to "our current 0.x version", that needs to be updated.
> MNT: Update readme for 1.0 release

- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
- .github/workflows/code-analysis.yml
- .github/workflows/docs-conda.yml
- .github/workflows/docs.yml
- .github/workflows/linting.yml
- .github/workflows/tests-conda.yml
- .github/workflows/tests-pypi.yml
- CONTRIBUTING.md
- README.md
- SUPPORT.md
- docs/conf.py
- docs/devel/infrastructureguide.rst
- docs/index.rst
- src/metpy/cbook.py
I already have renamed `master` to `main`, this just updates everywhere that was using the previous branch name.
> Update for rename of `master` branch to `main`

- docs/conf.py
- src/metpy/calc/tools.py
Fixes the incorrect copyright year range in the docs noted in #1716.
> Fix copyright in docs

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitignore
This is a (probably first cut) configuration for GitHub codespaces. This will allow essentially a remote VSCode instance running on GitHub managed infrastructure.
> Set up a codespaces configuration

- .github/codeql/codeql-config.yml
- .github/workflows/assign-milestone.yml
- .github/workflows/code-analysis.yml
- .github/workflows/docs.yml
- .github/workflows/draft-release.yml
- .github/workflows/nightly-builds.yml
- docs/api/references.rst
* Fix broken WMO link
* Add quality checks for the CodeQL (Code Analysis) action
* Fix milestone assignment action--it failed when it actually tried to assign a milestone because it was running on `pull_request` rather than `pull_request_target`
* Specify permissions for workflows as necessary so we can use more restricted (i.e. read-only content and metadata) default permissions
> CI Updates

- .github/workflows/assign-milestone.yml
Apparently, need to have write permission for issues set, in addition to PRs, for this to work. (This is not what [the docs](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-pull-requests) say.)
Also cleaned up a couple things and added some more debugging output.
> Fix assign milestone action

- src/metpy/calc/indices.py
Replaced loop using `enumerate` with a list comprehension in `mean_pressure_weighted()`. Also, I will be searching for any other uses of `enumerate` that could be refactored to a for loop or list comprehension.
> Refactor mean_pressure_weighted()

- .github/workflows/nightly-builds.yml
Xarray has updated their default branch from [master to main](https://github.com/pydata/xarray/issues/5516).
> Update xarray git install for nightly build

- tests/calc/test_calc_tools.py
See discussion in #1981. While this showed up on the nightly build, it will probably be also affecting our main CI now that xarray 0.19 is out!
- ~~Tests added~~ (test fix only)
- ~~Fully documented (test fix only)
> Specify coords as dict rather than tuple of tuples in tests

- src/metpy/calc/thermo.py
I find it useful to have the formula in the documentation so I added it to this function I was using.
> Added equation to relative_humidity_from_dewpoint

- src/metpy/calc/thermo.py
These weren't being displayed due to either missing closing brackets/parens, or missing space after ::. Also fixed the section in order in the docs for `dry_static_energy`.
> DOC: Fix some equations

- src/metpy/calc/basic.py
- src/metpy/calc/kinematics.py
- src/metpy/calc/thermo.py
- src/metpy/calc/tools.py
- src/metpy/interpolate/grid.py
- src/metpy/interpolate/points.py
- src/metpy/xarray.py
- Changes the order of "See Also" and "Notes" sections in documentation if the order is incorrect as per [numpydocs Style Guide](https://numpydoc.readthedocs.io/en/latest/format.html#documenting-modules)
> Swap "See Also" and "Notes" section in docs

- .github/workflows/docs-conda.yml
- README.md
- ci/doc_requirements.txt
- ci/test_requirements.txt
- src/metpy/calc/thermo.py
* Fix the parameter name ("e" instead of "vapor_pressure") in the docstring.
* While here also fix up the typesetting of the equation.
* Remove dead link to saythanks in `README.md`
> A couple of doc fixes

- .github/workflows/nightly-builds.yml
As the title says, need to update our nightly builds to get a working Cartopy built from source. It's unfortunate that due to actions/runner#834 we can't refactor these workflows and avoid this straight copy/paste properly.
> CI: Update nightly builds with cartopy build changes from #2165

- README.md
* Fix bad link to Codacy status badge
* Add MetPy and Unidata logos to top of Readme
* To improve space for the logos, compress the badges a bit
Before:
After:
> Readme Tweaks

- ci/doc_requirements.txt
Should be good to remove our jinja pin now that we're on a new version of the doc theme.
> CI: Remove jinja pin

- CONTRIBUTING.md
Fix redirecting link for git commit messages.
> DOC: Fix redirecting link (Fixes #2234)

- docs/conf.py
- docs/userguide/startingguide.rst
- tutorials/declarative_tutorial.py
- tutorials/unit_tutorial.py
- tutorials/xarray_tutorial.py
* Fix redirects due to xarray enabling https on their docs
* Clean up spelling/grammar flagged by PyCharm while I was in there
> Fix up xarray doc links redirecting

- examples/gridding/Inverse_Distance_Verification.py
- src/metpy/calc/basic.py
- src/metpy/calc/thermo.py
- src/metpy/calc/turbulence.py
- src/metpy/interpolate/geometry.py
- src/metpy/interpolate/tools.py
- tests/calc/test_basic.py
- tests/plots/test_skewt.py
* Use `np.hypot` instead of manual `np.sqrt(x * x + y * y)`
* Use `x**2` instead of multiplication (`x * x`). Younger me had some misguided notion of the former calling `pow()`, when in reality the integer power algorithms are highly efficient. Yes, multiplication is faster for a single scalar, but you're talking a difference of ~0.1us. For anything more than a few items they're indistinguishable, and `x**2` is more readable and maintainable.
* Fix up docs/examples a bit while editing these files
> Math tweaks

- src/metpy/io/_metar_parser/metar_parser.peg
- src/metpy/io/_metar_parser/metar_parser.py
- src/metpy/io/metar.py
- tests/io/test_metar.py
Prevents a crash through an expanded if test, but leaves unparsed groups beyond the invalid group unparsed.
> Handle truncated vertical visibility

- .github/workflows/nightly-builds.yml
GitHub is [disabling](https://github.blog/2021-09-01-improving-git-protocol-security-github/) the git:// protocol, so just switch to https://
> Update git location for pip in nightly build

- .github/workflows/nightly-builds.yml
This allows us to test the workflow in PRs, but only when relevant. This also tweaks things to always run the "Report" job (so that we can exercise the javascript in it), but stubs out the API calls so it doesn't fail due to the expected permission errors (on PRs).
> Run nightly workflow when the file is modified

- README.md
As discussed in #2305, the installation guide URL is broken. This updates it to:
https://unidata.github.io/MetPy/latest/userguide/installguide.html
> DOC: Update README installation guide URL

- .github/actions/install-conda/action.yml
- .github/actions/install-pypi/action.yml
- .github/workflows/docs-conda.yml
- .github/workflows/docs.yml
- .github/workflows/tests-conda.yml
- .github/workflows/tests-pypi.yml
- README.md
- docs/index.rst
- docs/userguide/installguide.rst
- setup.cfg
- setup.py
- src/metpy/_version.py
> Drop Python 3.7

- tests/plots/test_declarative.py
I have no idea why this changed, but it just seems like a bunch of minor
tweaks to random pixels. Easiest just to allow a minor amount of
difference.
> Bump test tolerance

- .gitattributes
- ci/requirements.txt
- docs/conf.py
- examples/gridding/Natural_Neighbor_Verification.py
- src/metpy/cbook.py
- src/metpy/io/station_data.py
- tutorials/xarray_tutorial.py
* Fix test data erronenously downloading when running from git checkouts
* Notate our vendored xarray code with the appropriate linguist tag
* Remove unneeded importlib_metadata from `ci/requirements.txt`
* Minor refactor of `StationLookup` to use more things from the standard library
* Fix some broken/redirecting links (#2335)
> Miscellaneous Maintenance

- SUPPORT.md
Trying to help promote not blasting multiple support channels with the same question.
> Add a note to SUPPORT to just pick one

- docs/devel/infrastructureguide.rst
The link we had in there pre-dates some updates to Codacy and no longer works (some other links were already updated).
> Update Codacy link in the dev docs 

- src/metpy/calc/basic.py
> DOC: add import to wind_components doc string example

- src/metpy/calc/thermo.py
> DOC: switch order of Parameters in specific_humidity_from_dewpoint

- docs/userguide/media.rst
* Fix redirecting link for podcast episode
* Add links to 2021 and 2022 AMS talks
> Update media page

- .github/workflows/cffcheck.yml
A [pre-existing action](https://github.com/citation-file-format/cffconvert-github-action) to run cffconvert to validate the `CITATION.cff` file exists, so why not use it? Thanks to GHA configuration, it's really easy to ensure it only runs when needed.
> CI: Add a workflow to check CITATION.cff

- .github/dependabot.yml
Use "CI:" prefix rather than "MNT:" since that matches what we currently
usually do. Also add the infrastructure label.
> MNT: Tweak Dependabot config

- src/metpy/calc/thermo.py
Add a docstring example to `thickness_hydrostatic`, as requested in [#2277](https://github.com/Unidata/MetPy/issues/2277). 
First-time open-source project contributor here, so I think I should start small. Let me know if any changes should be made. 
- <s>[ ] Closes #xxxx</s>
- <s>[ ] Tests added</s>
- <s>[ ] Fully documented</s>
> Add docstring examples for thickness_hydrostatic

- .github/actions/setup-proj/action.yml
Apparently using inputs as the path to cache causes it to show up empty at save time (which caused our problems in caching ~ before). Just hard-code `local`, since that's all we were using.
> Fix PROJ caching

- .github/actions/install-conda/action.yml
This gives us built-in caching and hopefully eliminates some warnings.
> Switch to mamba's "official" GitHub Action

- examples/formats/NEXRAD_Level_2_File.py
- examples/formats/NEXRAD_Level_3_File.py
- src/metpy/io/nexrad.py
Changes made to resolve issue #2511: 
- Included azimuth_range_to_lat_lon in the NEXRAD level 2 + 3 file examples 
- Plotted counties on example images
- Updated documentation to reflect max_range is in kilometers
> Code changes using azimuth_range_to_lat_lon

- ci/linting_requirements.txt
- src/metpy/plots/declarative.py
This needs a bunch of coordinated things, so easier to do it this way than use dependabot PRs.
> Update to Flake8 5.0

- docs/userguide/gempak.rst
- docs/userguide/startingguide.rst
- tutorials/declarative_tutorial.py
- tutorials/xarray_tutorial.py
Some were caught by the linkchecker due to forwarding. Apparently, it doesn't find links in our HTML in the GEMPAK reference.
> Update links to Xarray docs

- examples/plots/Station_Plot.py
thredds-test has been retired in favor of thredds-dev.
> Update link to THREDDS server

- src/metpy/calc/basic.py
- src/metpy/calc/indices.py
- src/metpy/calc/kinematics.py
- src/metpy/calc/thermo.py
This PR adds a number of examples for various calculations directly into the DOCs. It also fixes Issue #2585 by removing the math error that was reported.
Closes #2585 - [x]
> DOCS: Add numerous calculation examples

- tutorials/unit_tutorial.py
This PR addresses #2651 by adding a `.magnitude` section to the units tutorial.
> DOCS: create .magnitude tutorial

- src/metpy/calc/thermo.py
Properly use math rendering for equations and bulleted lists + math mode for the description of terms.
> DOC: Improve some formatting issues in docstrings

- examples/formats/NEXRAD_Level_2_File.py
This was caused by not handling the 0 crossing when calculating the edge azimuths.
> DOC: Fix artifact in NEXRAD level 2 example

- src/metpy/calc/thermo.py
Fix `mixed_layer_cape_cin` use example.
> DOC: Correct mixed_layer_cape_cin example

- src/metpy/io/gempak.py
- tests/io/test_gempak.py
Fixes #2118
(But not of the latitudes and longitudes)
(No change to the gdxarray docstring seemed warranted)
> Add metadata to output of gdxarray

- src/metpy/calc/thermo.py
- src/metpy/interpolate/grid.py
It means starting at lower indices first, versus higher indices first.
> Clarify meaning of `bottom_up_search`

- docs/userguide/gempak.rst
This updates for a bunch of sounding indices that have been implemented, including: `k_index`, `total_totals_index`, `lifted_index`, `showalter_index`, and `sweat_index`.
> Update GEMPAK comparison guide

- src/metpy/calc/cross_sections.py
As it says on the tin. Adds a "See Also" section to point to `cross_section` and `cross_section_components`. Also moves the more detailed discussion of equation and science to the "Notes" section, while making explicit  in the main description that it needs to be given a 2D cross-section.
> Improve the docs for absolute_momentum

- docs/api/references.rst
They reorganized it into a multi-volume set and the original link is broken.
> Update reference and link for WMO#8 manual (Fixes #2737)

- tutorials/unit_tutorial.py
Fix broken link I missed in fixing up #2763.
> Update link for Pint temperature unit docs

- docs/api/references.rst
Looks like they sort of rolled back the 2020 edition for some reason.
> DOC: Update link to WMO8 again

- docs/userguide/citing.rst
- docs/userguide/index.rst
Update the citation page with the journal article. Also add a link on the landing page within the user guide.
> DOC: Add links to BAMS article 🎉 

- .github/workflows/docs-conda.yml
- .github/workflows/docs.yml
- .github/workflows/tests-conda.yml
- .github/workflows/tests-pypi.yml
- setup.cfg
Currently adds 3.11 for the PyPI-based builds. Let's see if there's enough packages up to make this work.
> Add Python 3.11 to CI

- docs/userguide/startingguide.rst
> MNT: Update link for TDS

- docs/conf.py
* Add an allowed redirect for the Gitter link; the original link seemed better, so I elected for an allowed redirect rather than just updating the link
* Add some more DOIs to our collection of links to skip. Trying a custom user agent wasn't resolving the issue.
> Address some linkchecker issues

- examples/plots/Simple_Fronts_Plot.py
Of course right after #2420 landed, I come up with a simple example showcasing the capability. Oh well, better late than never.
> DOC: Add simple example plotting fronts using path effects

- examples/plots/Station_Plot.py
This failed linkchecker (NCAR machine room shut down over the weekend). While it's back now, there's no need to point to the dev server since the data is available on the production TDS.
> Update METAR link to use production TDS

- src/metpy/calc/basic.py
Instead of doing all the calculations in the example for geopotential_to_height, just feed some values so that it's clear what function is being shown.
> DOC: Simplify docstring example

- .github/actions/install-conda/action.yml
Previous provision-with-micromamba action is deprecated.
> CI: Migrate to mamba-org/setup-micromamba

- docs/userguide/gempak.rst
> A couple typo fixes in the first paragraph

- LICENSE
> Bump the copyright year in the license file

- src/metpy/calc/kinematics.py
This helps make clear that we're returning -u dot del and matches the implementation.
> DOC: Add negative to equation in the advection docs

- CONTRIBUTING.md
Looks like Ruff updates their doc URL with the 0.1 series.
> MNT: Update link to ruff docs

- src/metpy/calc/basic.py
This adds some examples for a method that doesn't have any.
> Add heat_index calculation examples

- docs/conf.py
As it says. We already had an allowed pattern, just update for the new location.
> Update allowed redirect for conda docs

- ci/linting_requirements.txt
- examples/calculations/Smoothing.py
- examples/gridding/Inverse_Distance_Verification.py
- examples/gridding/Natural_Neighbor_Verification.py
- pyproject.toml
- setup.cfg
- src/metpy/calc/basic.py
- src/metpy/calc/kinematics.py
- src/metpy/calc/thermo.py
- src/metpy/calc/tools.py
- src/metpy/io/gempak.py
- src/metpy/io/nexrad.py
- src/metpy/plots/declarative.py
- tests/calc/test_thermo.py
* Migrate plugin configs to `tool.ruff.lint.*`
* Use ruff for copyright header check instead of `flake8-copyright`
* Enable `NPY` ruleset and address concerns for NumPy 2.0, which for us centers on the use of the numpy singleton random number generator
* Actually enable the `SIM` ruleset from `flake8-simplify` and address the issues, which are largely around making more se of the ternary operator
*
> Update Ruff config

- docs/conf.py
As it says above. This is getting a 403 on GHA.
> Skip checking Stack Overflow link (Fixes #3400)

- src/metpy/io/metar.py
> Note text-mode needed for METAR file-like objects

- .github/dependabot.yml
This is now [supported](https://github.blog/changelog/2024-06-25-simplified-dependabot-yml-configuration-with-multi-directory-key-directories-and-wildcard-glob-support/), so we no longer need to manually list our internal GitHub actions, we can just point to a directory.
> Use wildcards in dependabot config

- .github/workflows/tests-pypi.yml
- .github/workflows/unstable-builds.yml
We don't care about the Ubuntu version, so just avoid the version reference which will eventually be deprecated and removed from GHA.
> Replace ubuntu-20.04 with ubuntu-latest

- examples/Advanced_Sounding_With_Complex_Layout.py
- pyproject.toml
These catch some [nice simplifications](https://github.com/sbdchd/flake8-pie) in general, though seems like we only had one violation.
> Enable flake8-pie rules in ruff

- .github/workflows/nightly-builds.yml
- docs/conf.py
* Update linkchecker config for conda docs change
* Reduce frequency of "nightly" run to 1/week (early Tuesday morning) to reduce impact of temporary failures
> Fix up nightly

- .github/actions/install-conda/action.yml
Apparently broken by micromamba 2.0.3, so fix version back to something that works. Also go ahead and remove the manual environment name, since that's completely unused.
> Fix windows environment setup with micromamba

- SUPPORT.md
- docs/conf.py
- pyproject.toml
Start advertising our Bluesky account as much as Twitter. While we're not dropping the latter, I'm much more inclined to engage and track the former.
> Add Bluesky alongside all Twitter links

- docs/_templates/autosummary/module.rst
- docs/api/index.rst
- examples/remote/README.txt
Add some missing bits so that the API docs and the examples show up in the docs. 
This will need to be backported to the 1.7.x branch.
> Make remote client docs & examples visible

- .github/dependabot.yml
* Fix up ignore syntax so things will work properly
* Group up the patch-level updates for our core dependencies. These are unlikely to break anything, so a single PR should generally succeed and let us further reduce noise.
> More dependabot updates

- docs/conf.py
- docs/userguide/startingguide.rst
The Cartopy docs have a new home on ReadTheDocs
> Update Cartopy references
