Unidata/MetPy

MANIFEST.in, docs/source/conf.py, docs/source/developerguide.rst, docs/source/index.rst
A bunch of tweaks that were revealed doing the release. This includes excluding things in the manifest, optionally using the RTD theme when building docs locally, and most importantly, documenting the release steps (since I just did them.)
=> Post release tweaks

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
`masked_array` was shedding units, so we need to reattach.
=> Fix missing units on masked output from heat_index (Fixes #56)

metpy/plots/skewt.py
This adds a limited clip box around the location that the barbs are
plotted, with options to control just how big that region is.
Updated the docs, but no tests here; there's no easy way to test this without biting off adding full graphical testing. I'm not ready to bite that off yet.
=> Skew-T wind barb clipping

metpy/io/nexrad.py, metpy/io/tests/test_nexrad.py, metpy/io/tools.py
Fix a couple of glitches in the NEXRAD code. One was handling a `BitField` that has no values actually set; this came from a malformed file that has unfortunately gone missing. The other is data from KTLX that is missing a couple of message segments. We were getting the last one, which triggered decoding the entire message, which failed. This PR fixes that and warns when we have incomplete multi-segment messages.
=> Nexrad fixes

.travis.yml, min-requirements.txt, requirements.txt, setup.py
Rework our Travis set-up.
- Build wheels for new versions as needed and get/store in S3.
- Refactor build matrix to be a bit cleaner
- Only install pandoc for doc build
- Use the 'test' extra defined in setup.py to get dependencies.
- Move to 3.5 as main 3.x version, drop 3.2 (Fixes #87)
- Build against nightly and 3.5-dev versions of Python (Fixes #96) with pre-release packages
=> Travis updates

.coveragerc, .gitignore, .travis.yml, CONTRIBUTING.md, docs/source/developerguide.rst, environment.yml, metpy/calc/tests/test_basic.py, metpy/io/tests/test_cdm.py, metpy/io/tests/test_gini.py, metpy/io/tests/test_nexrad.py, metpy/plots/tests/test_ctables.py, metpy/plots/tests/test_skewt.py, pytest.ini, setup.cfg, setup.py
Fixes #113.
Seems like nose is no longer maintained, and py.test is the most popular community option.
Not too hard. Biggest change is to replace some classes that were only used for grouping tests with sets of functions (py.test doesn't like `staticmethod` test functions). Also replace nose `eq_` with `assert`, since py.test does a good job giving useful output for plain asserts.
=> Replace nosetests with py.test

.checkignore, .travis.yml, docs/requirements.txt, docs/source/conf.py, docs/source/index.rst, docs/source/notebook_gen_sphinxext.py, metpy/plots/station_plot.py
Alright, this is the last time read the docs is going to fail on me silently. So this:
- Makes the Travis set-up mimic RTD by not installing (thus relying on mocked modules)
- Captures sphinx standard error to get any warnings/errors and fails the build if it's not empty (displaying errors of course)
Also cleans up a dependency and adds a link to my AMS talk.
=> Documentation build updates

.travis.yml
Fixing running our examples. Now that cartopy 0.14 is on PyPI, it requires proj.4 4.9, which of course isnt' available on Travis' Trusty Ubuntu images.
=> Build proj4 for examples.

metpy/_version.py, setup.cfg
We're careful about wildcard imports, they're all in tests or setting up
package __init__'s.
=> MNT: Ignore flake8's new 405 errors.

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Needed to force pressure ratio to dimensionless so that we have sane
units coming out.
=> BUG: Fix #165 potential temperature with non-mb pressure

appveyor.yml
Default conda on AppVeyor is currently 4.0.5, which is too old. Need to
explicitly request 4.1.
=> MNT: Fix AppVeyor.

metpy/units.py
We were pulling `ScaleConverter` from the wrong namespace--and are
broken against current pint master. This adjusts that to use the proper
import, as used by pint itself.
=> BUG: Fix namespace from pint.

metpy/io/nexrad.py, metpy/io/tests/test_nexrad.py
GenericDigitialMapper was incorrectly using the maximum level as the
size of the table and as the end point for range. This is a valid value,
so the size/end of range needs to be this +1.
Test this by trying to map data out of the products that have data.
=> BUG: Fix mapping values for several products (Fixes #253)

metpy/calc/kinematics.py
Numpy added an extra check to gradient (#7618), so we can't pass in pint
Quantities any more. We're already wrapping gradient, so it's no big
deal to make sure to pass actual scalar values.
=> MNT: Fix for gradient change in numpy 1.12

.travis.yml, appveyor.yml, environment.yml, metpy/plots/skewt.py, pytest.ini, setup.cfg, setup.py
Instead of running flake8 manually, add it as another plugin to pytest. It's simpler and more automatic, and this way there's only one test to run. It also allows us to simplify our Travis config and shorten the build matrix (~2 minutes of build time).
=> Add pytest-flake8

metpy/calc/basic.py
The [get_wind_components](http://metpy.readthedocs.io/en/latest/api/basic.html#metpy.calc.basic.get_wind_components) doc string's `See Also` section points to a non existent function. Here's a quick fix. Feel free to edit as you like.
=> fix get_wind_components see also doc string

metpy/plots/skewt.py, metpy/plots/tests/test_skewt.py
Revised the syntax in the skewt.py script so that way instances of `ax` are replaced with `self.ax` when classifying the `Hodograph` object. 
The test_skewt.py script was also tweaked so that way it can catch bugs introduced when `ax` is not explicitly defined in the `Hodograph` object.
Thank you for allowing me to make some changes! I apologize for taking so long, it took me a few hours to learn how to use Git properly.
=> Fix bug in Hodograph Object

metpy/calc/basic.py, metpy/calc/tests/test_basic.py, metpy/calc/thermo.py, metpy/plots/tests/test_skewt.py, metpy/units.py
Fixes for a bunch of small issues in advance of 0.4.3:
- Fix `mixing_ratio` to match docstring #275 
- Add test for SkewT with gridlines pre-set #271 
- Fix units with masked array return from `windchill` #281 
Also did some docstring clean-up/improvement.
=> Small bug fixes

README.rst, docs/_templates/footer.html
Adds a link to "Say Thanks" under the "Important Links" section. Seemed an appropriate place, it was easy to loose underneath the badges and probably unseen at the bottom. Addresses #291, @dopplershift manages the account.
=> Add link to say thanks

metpy/io/tests/test_upperair.py, metpy/io/upperair.py
Keep the wind speed and direction info when retrieving soundings. Addresses #298
=> Wind speed direction

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
If we don't converge in `max_iter` we should fail loudly. Addresses #317
=> Raise exception if LCL does not converge

metpy/plots/station_plot.py, metpy/plots/tests/test_station_plot.py
The pint implementation of format will not take a non empty format string, so this would fail when units were included (#307). Currently solution is to check if there is a units attribute and turn it into a scalar.
=> Convert quantities to scalars before formatting

docs/api/thermo.rst, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Virtual temperature, virtual potential temperature, and density
calculations were added to the thermo module. This addresses need for
a density calculation to allow for computation of EPV. Tests for these
calculations were also added.
See also: #231
=> Added thermo calculations

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
If no LFC exists, this makes it return `None` just like `EL` does.
=> Fix return if no LFC exists

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Pulls out the EL calculation from #322
=> EL calculation

metpy/io/tests/test_upperair.py, metpy/io/upperair.py
Return masked arrays from the IA State archive and make sure that the first row returned has temperature and dewpoint so thermo calculations that use a surface parcel don't break.
=> IA State masked arrays

metpy/calc/tests/test_tools.py, metpy/calc/tools.py
Add a directionality capability to `find_intersections` to filter on sign change for things like LFC calculations (see related #350). Significantly improves test coverage as well.
=> Find intersections directionality

docs/api/thermo.rst, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Add capability to calculate the vapor pressure and relative humidity from wet and dry bulb temperatures. Supersedes #155
=> Psychrometric RH

metpy/io/gini.py, metpy/io/tests/test_gini.py
This pull request adds an attribute 'img_extent' when using the to_dataset() function when using a gini satellite image file.
I was working on creating a satellite image and it seemed that a nice attribute to have for any gini file would be the extent of the image in image coordinates. This alleviates the need of the user to bring in the x and y coords simply to use it in the extent keyword within imshow. This also allows easier use to use Cartopy coordinate transformation with set_extent by being able to use lat/lon values and convert to projection coordinates.
I also added a test to test_gini.py for this new attribute.
=> Adds new img_extent attribute to ginifile dataset

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Check that the intersection we find really is the LFC and not a capping inversion by using the new directionality filter on `find_intersections`
=> LFC Sign Change Check

docs/api/io.rst, docs/api/plots.rst, docs/index.rst, docs/references.rst, metpy/calc/basic.py, metpy/calc/thermo.py, metpy/calc/turbulence.py, metpy/gridding/interpolation.py
Improvements on documentation including references and method documentation. Addresses #314
=> Doc tweaks

docs/conf.py
Helps get us ready for the Windows example and doc builds. Will need to be rebased and merged post #364.
=> Use operating system agnostic path separators

metpy/calc/tests/test_tools.py, metpy/calc/tools.py
Adds a helper function and streamlines its use in `find_intersections`. It will need some tests of course, but let's start with talking about how we want to modify the inner workings.
=> Add ability to deal with masked arrays to find_intersections

metpy/calc/basic.py, metpy/calc/tests/test_basic.py, metpy/calc/thermo.py, metpy/tests/test_units.py, metpy/units.py
This adds a decorator that allows us to decorate functions with the dimensionality of arguments (as positional or keyword arguments):
- Decorated arguments need to be passed with appropriate dimensionality (will catch missing units)
- Undecorated arguments pass through
- Dimensionless arguments can be dimensionless or just not have units
Sane handling of positional and keyword arguments relies on function signature arguments added to the `inspect` module in Python >= 3.3. Thus this isn't available on Python 2.7, and at run time this is a no-op there.
Closes #175.
=> Unit message helper

.travis.yml, metpy/calc/basic.py, metpy/calc/tests/test_basic.py
Windchill formula uses direct values of Celsius. The hack we had in
there to make that work with units did not work properly with Kelvin.
Instead, just convert to Celsius, drop units, and attach proper units
after calc.
=> BUG: Fix windchill when given kelvin temperatures (Fixes #385)

metpy/io/gini.py, metpy/io/tests/test_gini.py
GINI raster data come ordered with the top (i.e. highest latitude) row
first. Before this fix, y coordinates were calculated increasing from
the lower left corner--thus having the y-coordinates flipped from the
ordering of rows in the image. This was not enountered frequently due to
the use of imshow() with extents and origin.
This reverses the y coordinates and adjusts tests to match.
=> BUG: Fix ordering of GINI y-coordinates

metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py, metpy/testing.py
Closes #389 . Adds a kwarg `dim_order` that can be set to either `'xy'`, `'yx'`, or `None`, which uses the default. Currently the default is left to `'xy'`, but a warning is issued if the default is used. Refactor all the calculations to use yx ordering internally (to be most efficient for the common case), and added a decorator to flip all incoming arrays based on dim_order.
Also added some more tests to ensure that we're handling the transposes correctly (old tests had a lot of symmetric data).
=> Array ordering for 2D calculations

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py, metpy/testing.py
If the LFC or EL do not exist, return `np.nan` instead of `None`. Had to add a test helper since `np.nan != np.nan` and we want to verify units.
=> LFC and EL NaN returns

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
We had the other way (pressure to height), but this will be useful when drawing scale bars, coloring things based on their height, etc. The equations smells like it could maybe be slightly simplified, but I haven't seen a way to do it that results in any fewer operations, just moves the logarithm around. Closes #407
=> Add height to pressure conversion

metpy/gridding/tests/test_gridding_functions.py, metpy/gridding/tests/test_interpolation.py, metpy/io/gini.py, metpy/io/nexrad.py, metpy/io/upperair.py, metpy/plots/ctables.py, metpy/plots/tests/test_station_plot.py
PyTest 3.1 handles warnings now, which means that it now unsilences `ResourceWarning`s about unclosed file handles (added in Python 3.2). This cleans up our IO code to explicitly close any file objects they use, as well as makes sure that tests are using `with` blocks to handle reading from files.
Also finally fix the false alarm I get locally on my mac with one of the image tests by raising the threshold slightly.
=> Be better about closing file handles

metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py
This PR adds total deformation calculation to the metpy suite. One test has been added to ensure correct calculation, more can be added if desired.
=> Adds total deformation calculation

.travis.yml, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Instead of our own fixed point iteration code, use the code in
`scipy.optimize`. While this is measurably slower, we're still only
talking tens of milliseconds for 90000-element arrays. This slowdown is
outweighed by leveraging a re-usable algorithm, and we were likely to encounter similar performance when we refactored to make our own implementation re-usable for other calculations.
This also fixes a minor bug in lcl where we were returning the dewpoint
corresponding to the next-to-last pressure value from the iteration. In
practice, we're talking about differences in the thousandth of a degree.
=> MNT: Refactor `lcl` to use `scipy.optimize`

metpy/calc/tests/test_tools.py, metpy/calc/tools.py
Adds a log interpolation function to make interpolating things in pressure coordinates easier. This is needed for the layer helper functions being developed, but that PR was already getting rather huge.
I don't like all the unit checking and munging here. Interpolate drops units silently and log throws errors. Open to suggestions on if we should force unit usage here or not.
=> Log interpolation

docs/references.rst, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Adds calculation for relative humidity from mixing ratio or specific humidity, also ads conversion to mixing ratio from specific humidity. Mixing ratio and specific humidity are common model output variables, while relative humidity may be desired. 
#65 
* Added calculation for RH from w, w from q, and RH from q.
=> Relative humidity 

docs/references.rst, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py
Adds a companion function to get_isentropic_pressure for the calculation of the Montgomery Streamfunction on isentropic surfaces.
=> Montgomery Streamfunction

environment.yml
Looks like conda packages updating to numpy 1.13 somehow broke us on Windows.
=> Fix tests on windows

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Fixes the LFC and EL calculations to account for uncapped cases where the LFC and LCL are equal.
=> LFC and EL calculations when LFC = LCL

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Adds a simple CAPE/CIN calculator. By specifying all sounding data and a parcel path any type of CAPE/CIN can be calculated. Complication of creating the different parcel paths will be migrated into the `parcel_path` calculation.
=> CAPE and CIN Calculations

metpy/calc/tests/test_tools.py, metpy/calc/tools.py
Addresses an issue identified by @mwilson14 in which the interpolation function was not called when it should have been. Also cleans up the test that should have seen that.
=> Get layer interpolation fix

.travis.yml, ci/deploy_docs.sh, docs/Makefile, docs/conf.py
Fixes #284
Ended up not using doctr, because that wouldn't let me update a simlink to the latest easily. I've already updated the gh-pages branch with multiple versions. This doesn't allow for selecting between versions on the web page, but it does ensure that the default docs people see are the latest *released* docs. We also have the current dev snapshot of the docs at https://unidata.github.io/MetPy/dev/
=> Versioned docs

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Calculates the most unstable parcel (pressure, temperature, dew point) by maximizing theta-e.
=> Most unstable parcel

metpy/calc/tests/test_tools.py, metpy/calc/tools.py
It turns out the numpy.interp() always returns float64, no matter the
input (except for complex). This causes problems when we try to append
the result of the interpolation to our float32 data, causing the array
to upcast. This in turn causes, depending on the truncation, checks to
consider the lowest layer to seem like it's outside the bounds of the
data.
=> BUG: Fix get_layer with float32 data

metpy/calc/tests/test_thermo.py, metpy/calc/tests/test_tools.py, metpy/calc/thermo.py, metpy/calc/tools.py
Adds functions to compare floating point values in a greater/less than or near to sense. I also removed the conversion in the CAPE/CIN test that helped @tjwixtrom find the bug initially. Closes #488
=> Floating comparisons

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Fixes a bug in EL where feeding it a sounding truncated below the EL with multiple parcel path-profile intersections makes it give back the LFC as the EL. Right now this fixes it by calling the LFC function in EL and making sure EL isn't trying to give back the LFC, but it would be nice to find a way to not need to call LFC. Found this while trying to plot sfc-3km CAPE.
=> El Bug Fix

metpy/calc/tools.py
Makes sure that a mix of units cannot pass through `find_intersections` and result in confusing behavior. Closes #466
=> Add unit verification to find_intersections

metpy/io/nexrad.py, metpy/io/tests/test_nexrad.py
- Fix #489 by ensuring the bz2 frame decompressor doesn't totally bail if we've succeeded in decompressing some data
- Improve tests to try to ensure we're parsing the full file
- Handle the large message size specification, used in type-M packets--partially addressing #95 , but not actually parsing the message within the Type-M packet
=> NEXRAD parser fixes

.travis.yml, docs/installguide.rst, setup.py
This gives us a few more features without needing to backport. It's been
out almost two years at this point...
=> MNT: Bump numpy requirement to 1.10.0

docs/index.rst
Add a link to the poster and repo.
=> ENH: Add link to MetPy poster and repo for SciPy 2017

docs/references.rst, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Adds calculation for isentropic surfaces from isobaric surfaces.  Assumes linear dependence of variables with respect to ln(p). Requires input data in three dimensions with units attached. Pressure on isentropic surfaces is calculated by determination of a first guess and iteration with spicy fixed point optimization. Other fields are linearly interpolated with numpy. Outputs a tuple of all data. Not sure how to write a test for this one.
Fixes #294.
=> Isentropic pressure

examples/isentropic_example.py
Adds an example showing the usage of isentropic_interpolation, Montgomery_streamfunction, and relative_humidity_from_specific_humidity with NARR data. Note that travis/appveyor will fail due to Flake8 errors, let me know if there is anything I can do about those. Another example showing a cross-section plot using #518 will be added later.
=> Isentropic Example

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Adding a fix so that, in the case where the parcel path never intersects the profile, the surface data point is ignored in determining whether the parcel path is ever warmer than the environment (and thus, whether the LFC exists). Currently, in some cases the parcel is identified as warmer at the surface than the environment, resulting in a spurious LFC being identified at the same pressure as the LCL.
=> Fixing minor LFC bug

docs/CONTRIBUTING.md, docs/installguide.rst
These were permanent redirects, so go ahead and update and save the
computers a bit of work.
=> MNT: Update some links that were redirecting

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Add warning if relative humidity in dewpoint calculation is >120%. Does not address the divide by zero case if 0% RH is used. Is that an obvious enough message as is? Closes #424
=> Dewpoint from RH input validation.

docs/references.rst, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py
This PR adds a 2D frontogenesis calculation to the MetPy suite with a test. Don't know if the equation in the docstring will render correctly. There was also a small error in the test for total deformation that I corrected. It was testing something in a backwards way, so now made it conform to the other deformation style tests.
=> adds frontogenesis calculation and test

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Adds calculation for most unstable CAPE by finding the must unstable parcel and calculating a parcel path and cape. Do to issue #488 the profile is converted to degC before passing to cape_cin. Most unstable parcel has been modified to output the index value for the most unstable parcel to avoid recalculating this value within mucape_mucin. Tests reflect current working condition, has also been checked against SharpPy and gives reasonable results, though not exactly the same due to lack of virtual temperature correction.
=> Most Unstable CAPE

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
Warn if the given wind direction is greater than 2Pi, indicating that the user is probably passing values in degrees without units attached. This is particularly thorny as we have to work with lists, arrays, and individual values with and without units. I don't love this implementation, but it is the least checking and if/else blocks. There must be a better way.... right? Maybe this gets ripped out into a helper in tools? Closes #547
=> Wind direction warning

metpy/deprecation.py, metpy/io/upperair.py, setup.cfg
Use the matplotlib deprecation framework and deprecate get_upper_air_data. We can/should decide on which version that is official. Closes #516
=> MNT: Deprecate get_upper_air_data

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
Similar validation to what we've done with wind calculations for a common gotcha with Coriolis.
Closes #423
=> Add warning when coriolis calculation latitude is over pi radians

metpy/plots/_util.py
Return figure object when adding MetPy and Unidata logos. This is the expected behavior so we can do further figure manipulation - it's also what the docs say.
=> Return figure object when adding logo

.travis.yml, CLA.md
MetPy is not a legal entity, so we need to use the UCAR/Unidata CLA
instead.
=> MNT: Update CLA

examples/formats/GINI_Water_Vapor.py
The old example didn't plot properly, this updates the norm using `get_with_range` and sets the value below to black. Closes #560
=> Update GINI Example with new color table values

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Fixes an issue where the EL could be mis-identified if we had tiny surface inversions. We know it's always going to be at the top of the sounding! Also, greatly simplifies that section of logic.
=> Simplify EL calculation

metpy/calc/tests/test_indices.py, metpy/calc/tools.py
What appeared to be an issue in `bulk_shear` was really it passing None as a kwarg to `get_layer` and short circuiting the logic that assigned a default value. Closes #568
=> Assign depth kwarg default value if it is None in `get_layer`

metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py, metpy/calc/tests/test_tools.py, metpy/calc/tools.py
Closes #576 - There was complication with `get_layer` and some non-ideal testing/methods. This PR cleans up the docs, adds the function `get_layer_height` for height only subsetting (`get_layer` requires and interpolates in pressure space only). 
Testing now uses a triangular hodograph with a simple solution.
We may need to do some refactoring of `get_layer`, but that likely doesn't belong here. Either way I'm sure we can still do some API tuning.
=> Storm Relative Helicity Improvements

docs/references.rst, metpy/calc/indices.py, metpy/calc/tests/test_indices.py, metpy/calc/tools.py
Precipitable water had a few worts. We were enforcing a 400 hPa top by default (because of SHARP), had no bottom argument, and there was an error in the formula displayed by the doc string.
cc @brianmapes @mwilson14
=> Cleanup precipitable water

metpy/calc/tests/test_tools.py, metpy/calc/tools.py
Closes #593 by ensuring that `get_layer` works with data that are in increasing pressure order.
Not necessarily that pretty - I have a feeling that a refactor for all of this bounds/layer code is in order, but not sure when given our upcoming data model work.
=> get_layer with data in increasing pressure order

metpy/calc/thermo.py
Closes #370 for all practical purposes I think? Integrate everything between surface and LFC, then LFC to EL, not area sign dependent.
=> Integrate all areas for CAPE/CIN

examples/Advanced_Sounding.py, examples/gridding/Point_Interpolation.py, examples/plots/Hodograph_Inset.py, examples/plots/Simple_Sounding.py, examples/plots/Skew-T_Layout.py, metpy/calc/tests/test_indices.py, metpy/calc/tests/test_thermo.py, metpy/gridding/triangles.py, metpy/io/gini.py, metpy/plots/__init__.py, metpy/plots/_mpl.py, metpy/plots/tests/test_mpl.py, metpy/plots/tests/test_skewt.py, metpy/plots/tests/test_station_plot.py, metpy/plots/tests/test_util.py, tutorials/upperair_soundings.py
Flake8 is catching more things and this should fix them. I did noqa several were comments or conditional imports were the issue.
=> [MNT] Fix flake8 import order issues

metpy/plots/_util.py
Closes #609 
* `add_timestamp` now returns the text instance
* `_add_logo` now returns the figimage instance.
=> Update returns of figure annotations

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
We have the opposite, but not this calculation. It's going to be useful for the MSE plots and should be in the suite. Also a doc typo.
Before merging I need a good page number from Salby - I don't have a copy.
In support of #606
=> Specific humidity from mixing ratio

AUTHORS.txt, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py
I'd like to get involved in helping to contribute to MetPy, so here's my first attempt at tackling one of the beginner issues: renaming the convergence functions to divergence. In doing so, I also noticed a few of the comments on the tests for the deformation and frontogenesis calculations seemed incorrect as they referenced convergence, so I went ahead and corrected those too.
As this is my first PR, please do let me know if there is anything I should be doing differently. Thank You!
Closes #617
=> Rename Convergence Functions to Divergence

docs/conf.py
Allows docs to build on vanilla sphinx_rtd_theme, see #644
=> DOC: check presence of patched rtd_theme prior to setting versions

docs/_static/theme_override.css, docs/_templates/breadcrumbs.html, docs/conf.py
Modify the ReadTheDocs 'breadcrumbs.html' template to include this link. The link in the docs will point to the Github source in "edit" mode (on the master branch). If the page is autogenerated, it will point to a new issue instead with the page name included in the title and some instructions in the body.
Fixes #673
=> Replace "View source" with "Improve this page"

metpy/calc/tests/test_indices.py, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
In the edge case that `part_pres` and `tot_pres` are in units of mb and hPa respectively, force a return of 'dimensionless' rather than mb/hPa, which is technically a dimensionless quantity but not very intuitive to the user. Also changes a test on precipitable water from `assert_array_equal` to `assert_array_almost_equal` to account for a machine precision error.
=> Make mixing_ratio return 'dimensionless'

environment.yml
Add sphinx_rtd_theme to development environment to make getting setup to develop and build docs locally easier.
=> Add RTD Theme

examples/isentropic_example.py, metpy/calc/thermo.py
As discussed in PR #669, for consistency with the rest of the library, relative humidity should be treated as a unitless ratio in [0, 1]. It was noticed that some previous functions in thermo.py treated it as a percentage. This aims to correct that.
=> Update to Treat RH as a Unitless Ratio in Existing Functions

metpy/calc/tests/test_indices.py, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py, metpy/constants.py
and fix some typos in docstrings of `calc/thermo.py`.
Addresses #623.
=> Ensure that appropriate constants and function results are dimensionless

docs/_static/pop_ver.js, docs/_templates/footer.html, docs/_templates/layout.html
There were quite a few problems with relative paths that needed fixing. Closes #675.
=> Fix versioned doc handling

metpy/calc/thermo.py
Closes #619 - Apparently attaching units the way we were does not play will with representation in all cases. I'm not sure how we could test for this as the print and string representations are fine. This does read nicer as well.
=> Change unit attachment to LCL pressure

metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py
A few respellings that are clearer instead of shorter. These could be up for debate, but it's more in line with the ethos we're working around here.
* `v_vorticity` -> `vertical_vorticity`
* `h_divergence` -> `divergence` (with options for 3D post X-array integration)
I still need to add some skeletons for the old names telling users that those have been renamed.
=> Respelling of `v_vorticity` and `h_divergence`

conftest.py, docs/references.rst, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py, metpy/calc/tests/test_tools.py, metpy/calc/thermo.py, metpy/calc/tools.py, metpy/tests/test_units.py, metpy/units.py, setup.cfg
This should be good to go now. This adds 1st and 2nd derivatives, as well as gradient and laplacian that work with irregular grids. This also updates the kinematics functions to use them rather than wrappers for numpy's gradient function.
Closes #174 .
=> Add gradient and derivatives for irregular grids

.mailmap, .travis.yml, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py
We already promised that we were going to do this, so we probably should.
=> MNT: Change default dimension ordering for kinematics functions

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Fixes issue #703 where `mixing_ratio_from_relative_humidity` returns in percent when RH is supplied in percent. Also adds a test to verify the unit on the returned value is indeed dimensionless.
=> Force `mixing_ratio_from_relative_humidity` to return dimensionless

examples/sigma_to_pressure_interpolation.py
This adresses issue #616.
Removed isobaric_levels variable and replace it with height and temp variables.
Correct the extend value in the colorbar call from a function max to a string 'max'.
=> Clean up sigma interpolation example

docs/gempak.rst, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
I'm sorry that my "later this week" turned into a couple weeks after finals and holidays!
But, in any case, here is a PR addressing issue #629, implementing the various Brunt-Väisälä frequency and period functions discussed in comments. This PR also makes a modification to the `kinematics._gradient` function, which previously had issues with the `axis` kwarg. Finally, it also updates the GEMPAK table to reflect these new functions.
Feedback is greatly appreciated! I especially wanted to ask about on the following:
- Should I be using "Vaisala" or "Väisälä"?
- Is the modification to `kinematics._gradient` acceptable, or is there a better approach to taking the derivative along a single axis that works with various array sizes?
- Is the test coverage sufficient, or are there additional …
=> Add Batch of Functions for Brunt-Väisälä Frequency and Period

examples/formats/GINI_Water_Vapor.py, examples/formats/NEXRAD_Level_2_File.py, examples/formats/NEXRAD_Level_3_File.py, examples/isentropic_example.py, examples/sigma_to_pressure_interpolation.py
Closes #708 
Added 'add_timestamp' to the imports in GINI example file then called 'add_timestamp' at the end of the code to display the timestamp on the product.
Could be added to these files:
=> Add calls to 'add_timestamp' to examples

metpy/plots/tests/test_station_plot.py
Looks like the newest matplotlib tweaked the end of the lines being drawn, so slightly bump up the tolerance.
=> MNT: Adjust test tolerance

docs/developerguide.rst, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py
Closes #699 - Adds a signed version of `lat_lon_grid_spacing` as `lat_lon_grid_deltas`.
The current testing setup isn't pretty, but I'd like to know if that's the only test case we need to worry about here or if anyone can think of any corner cases here. I'll then cleanup that test and rebase.
=> Add `lat_lon_grid_deltas` function to replace `lat_lon_grid_spacing`

docs/references.rst, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Add web bulb temperature calculation using Normand's rule. Closes #409 
A few implementation questions:
I'm getting within a few tenths of a degree of https://www.weather.gov/epz/wxcalc_dewpoint FWIW.
=> Wet Bulb Temperature

metpy/constants.py
While working on some problems using MetPy, I tried using the density constant, and found that it wasn't actually there, despite being in the documentation! This commit adds it in.
Also, I've simply added it as a calculation at STP, rather than a specified value. So, let me know if that is an okay approach or if I should find a value and corresponding citation. Thanks!
=> Add Dry Air Density Constant

.codeclimate.yml, metpy/io/nexrad.py, metpy/io/tests/test_nexrad.py
So when we refactored the handling of files, we removed the filename attribute from Level3File. This attribute, it turns out, is used in all of the logging for the class, as well as __str__. More disturbingly, not one test screamed about it being broken. Fixed all of that.
I'm also tweaking the Code Climate config in the hope of making it a bit more useful and less noisy.
=> Fix Level3File

metpy/plots/_util.py
Closes #701.
Fixed return types in docstrings for add_metpy_logo and add_unidata_logo functions.
=> Fix return types in docstrings of logo functions

.travis.yml, metpy/plots/tests/test_station_plot.py
Need to explicitly install Cython for CartoPy to build. This needs to be
a global extra package since we use CartoPy for at least one test.
=> MNT: Fix Travis testing with CartoPy

CONTRIBUTING.md, LICENSE, examples/formats/GINI_Water_Vapor.py, examples/formats/NEXRAD_Level_2_File.py, examples/formats/NEXRAD_Level_3_File.py, examples/isentropic_example.py, examples/sigma_to_pressure_interpolation.py, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py, metpy/calc/tests/test_thermo.py, metpy/calc/tests/test_tools.py, metpy/calc/thermo.py, metpy/calc/tools.py, metpy/constants.py, metpy/plots/_util.py, metpy/plots/tests/test_util.py
Update to 2018.
Also pull a fresh copy of the license text from GitHub to hopefully fix the license detection. The changes in the text, besides line wrapping were:
- Replace "MetPy Developers" with "copyright holder" and "any contributors" with "its contributors" in the no endorsement clause
- Replace "COPYRIGHT OWNER" with "COPYRIGHT HOLDER" in the warranty disclaimer.
=> MNT: Tweak license text and update year

metpy/calc/kinematics.py
Closes #755 
* Remove units in docstring
* Fix rendering of equation in TeX
* Replace `sf` with upper case Psi as is standard in most texts.
=> Fix rendering issues in Montgomery Streamfunction

examples/calculations/Dewpoint_and_Mixing_Ratio.py, examples/isentropic_example.py, examples/sigma_to_pressure_interpolation.py, talks/2015 Unidata Users Workshop.ipynb, talks/MetPy Exercise.ipynb
=> MNT: use `mpcalc` as import alias for `metpy.calc`

.codeclimate.yml, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py
Addresses #650 by adding a potential vorticity calculation that is versatile in terms of array ordering (x, y, levels) or (levels, x, y) for example. From my understanding of PV if the user gives us winds on an isentropic surface this is IPV (theta is constant across each of the three layers given, pressure varies) and if the user gives us winds on an isobaric surface it is isobaric PV (theta varies across three layers of constant pressure). A few things to consider here:
=> Potential vorticity

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
Closes #773 by forcing the output of Coriolis parameter calculations to be 1/s. This makes geostrophic wind units much more pleasant. It's also just a more useful default output.
=> Coriolis units to 1/s

examples/Four_Panel_Map.py
Closes #713. 
This pull request fixes the issue with the padding in the creation of the four panel example. 
It utilizes the newest versions of Cartopy and Matplotlib. The code has been modified to include:
- the use of the subplots function for generating the individual plots.
- the use of constrained layout in Matplotlib v2.2.0 to generate proportionate padding between plots.
- the use of set_constrained_layout_padding function for adding padding between figure and plot titles.
With the subplots function, the code can extract the figure and array of axes from the start then plot the background features. 
The number of lines in the code has been reduced from 41 to 33.
=> Four panel example edit

metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py
Closes #774. Users could specify a custom Earth major/minor diameter and the output of the function would not change as the default `ellps` kwarg is sphere and apparently `geod` ignores everything else after that.
=> Geod kwarg override

metpy/calc/tests/test_turbulence.py, metpy/io/nexrad.py, metpy/plots/ctables.py, talks/2015 Unidata Users Workshop.ipynb
Removing unneeded uses of the `dict.keys()` method.
=> Remove `keys()`

CONTRIBUTING.md, README.rst, SUPPORT.md, docs/index.rst
Updates all of the support, contact, etc. to include information about posting on Stack Overflow. Also mentions our support-python email.
=> ENH: Add Stack Overflow information (Fixes #782)

metpy/gridding/interpolation.py, metpy/gridding/points.py, metpy/io/_tools.py, metpy/io/gini.py, metpy/io/nexrad.py, metpy/io/tests/test_nexrad.py, metpy/plots/ctables.py
This tries to improve some diagnostic information. The difficulty was exposed in trying to understand an occasional exception that was causes by a file that was actually two concatenated together. This PR:
- Changes to use `logging.basicConfig()` to set up the default stream handler/formatting/level. This sets only the default level, so that our modules don't override user settings
- Adds some logging messages when searching for the WMO header and the footer bytes
- Changes an assert to a logged warning message (since we can recover in parsing some times)
- Changes a commented out print to a debug log message
=> Improve logging in NEXRAD Level 3

metpy/tests/test_units.py, metpy/units.py, setup.py
Closes #797 by providing a helper to make dealing with pandas data frames easier. It can attach units from a units attribute on the dataframe or from a dictionary provided by the user. Unspecified columns are returned as plain numpy arrays.
=> Pandas unit helper

README.rst, docs/index.rst, docs/installguide.rst, setup.py
Adds sections on semantic versioning (#802) and dropping Python 2.7 (#803). Also prepares `setup.py` for our future drop of Python 2.7.
=> Documentation updates

.travis.yml
With pip 10, we need an [extra flag](https://pip.pypa.io/en/stable/user_guide/#only-if-needed-recursive-upgrade) to make it blindly upgrade everything, which is what we want for our CI setup.
=> MNT: Fix travis doc build

docs/gempak.rst, docs/references.rst, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Implements the Q-vector and static stability calculations as discussed in #661, based of formulas from Bluestein 1992. Closes #661.
Also, I don't know what the best way to test these functions is, since I've only really worked with Q-vectors in a graphical context, and static stability in a qualitative context. So, feedback on the tests is especially appreciated!
=> Add Q-vector and Static Stability Calculations

metpy/calc/tests/test_tools.py, metpy/calc/tools.py
and its subfunction _abbrieviate_direction
parse_angle allows users to easily convert directional text into a degree/radian value
such as N becomes 0 deg, east becomes 90 deg, south_east becomes (135 deg) etc
First time contributing so a bit uncertain about the process!
=> Add new metpy/calc/tools parse_angle

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
A user emailed with the attached sounding data file in which the LFC calculated was below the LCL. After looking in the sounding manual and discussing with @kgoebber - it's safe to say that the LFC *must* be at or above the LCL. This adds a check for that.
Reading example:
```python
data= '04261800z.rtso'
df = pd.read_csv(data,sep='\s{1,}',skiprows=10,engine='python',names=["flightTime","pressure","temperature","relhumidity",\
"height","dewpoint","refractiveindex",\
"gradrefractindex","modrefracindex",\
"speedofsound","density","vaporpress",\
"potentialtemp","virtualtemp","spechum",\
"spare1","spare2","spare3","spare4",\
"utcsecs","speed","direction","vcomp",\
"ucomp","vertwind","long","lat",\
"geometricheight"],na_values=('/////./',\
'////./','///./','//./','/////.//'))
df = …
```
=> LFC above LCL

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Related to #750 - makes the parcel path actually modify the LFC/EL.
=> Pass parcel profile through cape_cin calculation

environment.yml, metpy/plots/tests/test_skewt.py, metpy/units.py, setup.py
Fixes #805 - sort of. We had a problem in unit handling of tuples and lists. This PR fixes that, but the next problem likes in matplotlib `set_ylim`. `self._process_unit_info(ydata=(bottom, top))` needs to be inserted at line 3225 of _base.py in matplotlib. This adds a failing test that can be easily switched from expected fail when the mpl issue is resolved. Opening another issue on that.
=> Hodograph units

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
Addresses #833 in a rather clunky way, but the only reliable way I could find. If we find we use the logic other places, it might be a good decorator, but that seems like overkill for now.
=> Apparent temperature working with scalars

docs/infrastructureguide.rst, docs/installguide.rst
Having the requirements text in the documentation doesn't really seem necessary:
* It's documented in `setup.py`
* Most users (if not all) install via pip or conda, so it's irrelevant.
* It is another place to manually update/forget to update.
=> Remove requirements text

README.rst, metpy/calc/tests/test_thermo.py, metpy/calc/tests/test_tools.py, metpy/calc/thermo.py, metpy/calc/tools.py
A lot of clean up of the existing code, as well as improvements to:
- Handling masked arrays/columns of nans (Fixes #769)
- Improved searching for isentropic levels to use a linear search rather than `np.searchsorted`, which isn't strictly correct. It doesn't impact the results in our example at all, but the new version is about 10% faster (due I suspect to the removal of `apply_along_axis`). (Fixes #798)
- Can now control which direction to search (which makes minimal difference in our example)
=> Isentropic updates

examples/XArray_Projections.py, metpy/__init__.py, metpy/calc/basic.py, metpy/calc/indices.py, metpy/calc/kinematics.py, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py, metpy/calc/tools.py, metpy/calc/turbulence.py, metpy/io/__init__.py, metpy/tests/test_xarray.py, metpy/xarray.py
This adds a decorator, which automatically converts `DataArray` instances to `pint.Quantity` instances (using the `.metpy.unit_array` accessor) to all the calculation functions. I added an independent test of the decorator, as well as a test for one calculation. Ideally we'd have tests for each calculation that `DataArray`s work (ensuring that the decorator has been added), but that seems a little repetitive to bite off right now.
I also moved the `xarray.py` out of `io` and into a top-level module, which is imported by the top-level `__init__.py`. This causes the accessors to be loaded with any import of metpy, which seems like a better solution than forcing random imports of `metpy.io`.
=> Xarray Conversion Decorator

.travis.yml, environment.yml, examples/Four_Panel_Map.py, examples/isentropic_example.py, examples/sigma_to_pressure_interpolation.py, metpy/calc/tests/test_tools.py, metpy/calc/thermo.py, metpy/calc/tools.py, metpy/plots/_util.py, metpy/tests/test_xarray.py, metpy/xarray.py, setup.py
- Fix weird warning "'numpy.float64' object has no attribute '_units’" in Advanced Sounding. Turns out we were comparing `Quantity` with a bare `array` and things didn't error.
- Make `add_timestamp` call the `strftime` method on the passed in datetime rather than force calling `strftime` from the `datetime` module. This paves the way for using "date times" from xarray
- Move the isentropic interpolation and four panel map examples to use xarray (and in the case of the former better use cartopy)
- Make the sigma interpolation example work with netcdf4 1.4 by hard-coding units rather than parsing. This seemed the least horrible of many horrible-looking solutions. Would be nice to use xarray, but alas there are complications.
Fixes #836 .
=> Clean up examples

.circleci/config.yml, .mailmap, .travis.yml, AUTHORS.txt, metpy/calc/tests/test_tools.py, metpy/tests/test_units.py, metpy/units.py, setup.py
Fixes #642.
The calculation propagates masked values fine, in that any calculation involving one more more masked values ends up as masked (similar to NaN propagation). The problem was using numpy's concatenate, which stripped masks. Use np.ma.concatentate instead, dropping to a regular array if there are no masked values.
Went ahead and also fixed our CircleCi build, which revealed an implicit testing dependence on a newer version of CartoPy than we listed.
Will rebase on master for release, but I want to see if the travis_wait change helps the build on travis python nightlies.
=> Fix mask propagation in gradient

metpy/calc/tests/test_kinematics.py, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Capitalized names are reserved for classes. Picked up by pep8-naming 0.7.
=> MNT: Fix some non-standard naming

.travis.yml, README.rst, setup.py
As a part of #813, I've removed 3.4 from the `.travis.yml` matrix. Is this all that has to be done?
=> Drop python 3.4

examples/calculations/Gradient.py, metpy/calc/tests/test_tools.py, metpy/calc/tools.py
Fixes #842 by replacing the `x` keyword argument in `_process_gradient_args` with `coordinates`, and including `x` as a deprecated option. Also adds tests to verify that use of `x` as a keyword argument raises the deprecation warning.
=> Change x to coordinates in gradient and laplacian interface

docs/index.rst, setup.py
As mentioned in #873, I didn't quite catch everything...this PR additionally takes care of needed changes in `docs/index.rst` and `setup.py`.
=> Additional changes to drop python 3.4

examples/Advanced_Sounding.py, examples/gridding/Wind_SLP_Interpolation.py, examples/plots/Hodograph_Inset.py, examples/plots/Simple_Sounding.py, examples/plots/Skew-T_Layout.py, examples/plots/Station_Plot.py, examples/plots/Station_Plot_with_Layout.py, metpy/calc/basic.py, metpy/calc/tests/test_basic.py, metpy/calc/tests/test_kinematics.py, metpy/testing.py, tutorials/upperair_soundings.py
This PR addresses two issues relating to the wind functions in `calc/basics.py`. First, fixes #865 by renaming the functions as described in the issue and deprecating the old functions. Additionally, fixes #794 by ~~adding a flag to specify the behavior for `wind_direction` (formerly `get_wind_dir`) in regards to calm and north winds~~ specifying calm winds as 0 degrees and north as 360 degrees.
Also, I think that we will need to open a "Removals/Deprecations in 0.12" issue once the renaming goes through.
Feedback, especially on the approach of handling the calm and north wind issue, is greatly appreciated!
=> Update Wind Functions

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
This PR adds two basic equations that assume hydrostatic balance in order to convert between omega (Dp/Dt) and w (Dz/Dt). I've found that I need this in an example or two for cross section analysis, but it is likely useful more generally as well.
One main question I have with this: what to name the functions? The terms "vertical velocity" and "vertical motion" are used, but inconsistently, to refer to the height- and pressure-based terms. "omega" and "w" are the only consistent terms I've seen used, but if I recall correctly we try to avoid abbreviations like these.
=> Add conversions between omega and w

metpy/plots/mapping.py, metpy/plots/tests/test_mapping.py, metpy/tests/test_xarray.py, metpy/xarray.py, tutorials/xarray_tutorial.py
A first cut at implementing #860, this implements systematic coordinate mapping utilities to the `Dataset` accessor according to CF standards/recommendations/options and uses those to assign appropriate `axis` attributes to the coordinates in `parse_cf`. This also adds some properties to the `DataArray` accessor to obtain easy access to the coordinates corresponding to a particular axis.
This PR is a work is progress, but I wanted to get it out there to run it by the checks, and to get some initial feedback. Once the initial implementation of everything (roughly) looks good, I plan on working on tests.
(Also, @dopplershift and @jrleeman, for now, I decided to go with `vertical` instead of `level` or `levels`, and `time` instead of `times`, as those seemed more natural as I was working …
=> Systematic Coordinate Identification

metpy/tests/test_xarray.py, metpy/xarray.py
This PR consists of two changes following up on #871:
- Update tests to use the xarray `.identical()` method instead of checking equality of values and attributes
- Allow dimension coordinates to take precedence in axis coordinate conflict resolution (fixes an issue I had in working with GOES16 output).
Also, since I forgot it in #871, closes #860.
=> xarray Coordinate Identification Cleanup

metpy/plots/mapping.py, metpy/tests/test_xarray.py, metpy/xarray.py, tutorials/xarray_tutorial.py
This PR changes the protected method `_make_cartopy_globe` in
CFProjection into a property, and exposes that property in our xarray
DataArray accessor as well.
Closes #859.
=> Expose cartopy globe in CFProjection and xarray accessor

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
When the United States switches to the metric system, we will skip Celsius and go directly to Kelvin.  This PR prepares us for that wonderful future.
also follows: #385
=> permit usage of temperature in Kelvin for heat_index calc

docs/_templates/breadcrumbs.html, docs/conf.py
Adds the sphinx-gallery configuration to the template so we can link to the Github edit page for the gallery .py files. The template also identifies the index.html files and directs them to the README.txt files.
Copied this from the [Verde repo](https://github.com/fatiando/verde). For a working example, see https://www.fatiando.org/verde/latest/gallery/block_reduce.html
=> "Improve this page" links for examples and tutorials

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
There is a bug when computing `apparent_temperature` when only the windchill calculation is used.
Code assumes that `windchill` returns a masked array, it may not if all values are defined as valid wind chills.  The traceback is like so 
```
metpy/calc/basic.py:340: in apparent_temperature
app_temperature = np.ma.where(wind_chill_temperature.mask,
...
E           AttributeError: Neither Quantity object nor its magnitude ([-18.93572062]) has attribute 'mask'
```
The change ensures that `wind_chill_temperature` has a mask, when needed
=> fix apparent_temperature when only windchill is calculated

.appveyor.yml, .travis.yml, docs/Makefile, docs/_templates/autosummary/module.rst, docs/_templates/overrides/metpy.calc.rst, docs/conf.py, docs/make.bat, docs/override_check.py
This PR reorganizes the `calc` API doc page to be broken down into categories, instead of just one long list (breakdown is currently from [this draft](https://docs.google.com/spreadsheets/d/14g8uyhTVySZ42aJigeaDZSRbspO7a7GsvKDayFyrmY0/) as mentioned in #809). It does so by adding a template override option to the module template, and then implementing a custom `metpy.calc.rst` file in the new `overrides` directory. It also adds a script to verify that all functions in modules that have template overrides are included in their respective doc pages. Closes #809.
Further discussion is likely needed on the best organization of the `calc` page itself, but I wanted to get this PR out there for review on the method, and to see how CI works with it. 
Some initial thoughts on the approach: …
=> WIP: Reorganization of calc docs (with module template override option)

docs/_templates/overrides/metpy.calc.rst, docs/installguide.rst, docs/override_check.py
After #889 and #882 were merged, there was a conflict where the override
doc page created in #889 had functions that were removed in #882. This
PR removes those functions and should restore the doc builds to working order.
Also cleans up a line from code review in #889.
Closes #897.
=> Remove removed functions from doc page override

.travis.yml, docs/_templates/overrides/metpy.calc.rst, docs/gempak.rst, docs/references.rst, metpy/calc/__init__.py, metpy/calc/cross_sections.py, metpy/calc/tests/test_cross_sections.py, metpy/interpolate/__init__.py, metpy/interpolate/slices.py, metpy/interpolate/tests/test_slices.py, metpy/testing.py, metpy/tests/test_xarray.py, metpy/xarray.py, setup.py
This adds a `cross_section` function to `interpolate`. It allows interpolation to a cross-sectional slice through gridded data along a geodesic path between two lat/lon points. It takes data as either an `xarray.Dataset` or `xarray.DataArray`, and utlizes xarray's own `.interp()` method.
Additionally, this adds in a number of supporting calculations:
- normal and tangential unit vectors along the cross section path
- normal and tangential components of vector field (closes #652)
- cross-sectional absolute/pseduoangular momentum (closes #654)
~~This PR is currently a work-in-progress, since I wanted to get the code of the implementation itself out for initial review, and ask about tests. I currently have some examples in notebooks that I plan on using for the unit tests, but, I'm unsure of …
=> Add cross section function and supporting calculations

metpy/calc/kinematics.py
Based on a comment in #893, documentation for the vorticity function hadn't been updated to reflect the fact that the function can handle varying grid spacings. This PR updates the documentation accordingly. Wording mirrors that found in the gradient docstring.
=> Update docstring for vorticity

docs/_templates/overrides/metpy.calc.rst, metpy/calc/cross_sections.py, metpy/calc/kinematics.py, metpy/calc/tests/test_calc_tools.py, metpy/calc/tests/test_kinematics.py, metpy/calc/tools.py, metpy/tests/test_xarray.py, metpy/xarray.py, tutorials/xarray_tutorial.py
While this was originally devised while working on isallobaric wind and thermal wind, I've also found that it would be needed for some of the cross-section examples I'm putting together (a couple forms of PV that our current implementations don't handle), so here it is now on its own.
This PR modifies the current derivative calculations to work with DataArrays themselves, rather than by conversion to (and output as) pint quantities. This includes automatic coordinate handling. With that, in order to support lat/lon non-uniform coordinates, the `lat_lon_grid_deltas` function also needed to be moved from kinematics.py to tools.py to make the imports work right.
Three implementation questions I'd like to ask right away:
- what should the default be for `first_derivative` and …
=> Make derivative calculations work with xarray DataArrays

metpy/calc/tools.py, metpy/tests/test_units.py, metpy/units.py, metpy/xarray.py, tutorials/xarray_tutorial.py
As brought up (and discussed at length) in #907, units like 'gpm' and 'degrees_north' are not handled by pint, which can necessitate workarounds in order to do calculations with geopotential height, or relating to latitude/longitude (see the [xarray tutorial](https://unidata.github.io/MetPy/dev/tutorials/xarray_tutorial.html) for examples).
This PR currently takes the approach of adding a few new units to the unit registry (~~`geopotential_meter`~~, `degrees_north`, and `degrees_east`) with appropriate abbreviations/aliases to handle these cases.
Discussion in #907 was not quite settled on this approach (the other option seemed to be changing the units in `parse_cf()`), but I wanted to put this out there as a PR since I was able to get this approach implemented. This seems like the best …
=> Make handling units like 'degrees_north' a little nicer

metpy/calc/thermo.py, metpy/calc/tools.py, metpy/calc/turbulence.py, metpy/cbook.py, metpy/interpolate/one_dimension.py
Since NumPy 1.15 came out, we have been getting pages and pages of warnings about our use of non-tuple based indexing. This PR converts all of our previous list-based indexing to tuple-based indexing. This doesn't yet clear out all the warnings (some of them are upstream in Pint and scipy), but it does drop the number down from 600-something to 10-something.
Closes #900.
=> Fix non-tuple NumPy indexing in MetPy

docs/api/index.rst, examples/README.txt, tutorials/README.txt
Closes #904 by clarifying the docs for readability/find-ability
=> Respell doc page names for clarity

metpy/plots/skewt.py
The previous default of 0.08 was just a little too tight.
=> BUG: Increase default x clipping radius for SkewT

metpy/__init__.py, metpy/interpolate/geometry.py, metpy/interpolate/points.py, metpy/io/_tools.py, metpy/io/gini.py, metpy/io/nexrad.py, metpy/io/tests/test_nexrad.py, metpy/plots/ctables.py
Fixes #866. No longer use `basicConfig()` because what it does is install a root handler if none is already installed. This breaks applications that also try to use it to set a different level. It's completely unnecessary on Python 3, since by default there is a handler that logs anything WARNING or higher to    stderr, which is really what we want. This isn't the case on Python 2, so what we can do in that case is put a StreamHandler (which defaults to stderr) for all of metpy (all submodules will defer to it by default). WARNING is already the default logging level anyway.
This also fixes up a logging test and installs a warning filter for all of those "numpy dtype size has changed" messages that are spewing *everywhere*.
=> Fix logging setup

metpy/tests/test_units.py, metpy/units.py
Closes #907 by defining gpm as a meter alias so any units assigned gpm will quietly be changed to plain meters.
=> Add gpm unit as an alias to meters

docs/gempak.rst, metpy/calc/kinematics.py, metpy/interpolate/slices.py, tutorials/xarray_tutorial.py
This PR contains a few documentation fixes:
- Fix the description of the `cross_section` and `interpolate_to_slice` functions to reference xarray's interpolation, not metpy's
- Clear up some usage details with Dataset.metpy.parse_cf() (see #909)
- Update `dx`/`dy` parameter descriptions (as in #901) for all applicable functions in kinematics
- Add notes to kinematics functions about handling of >2 dimensions (similar what `ageostrophic_wind` had in parameter descriptions)
- Update the GEMPAK table for closed issues
- ~~This includes #645, which isn't closed yet, even though it is implemented.~~
=> A Few Documentation Fixes

docs/_templates/overrides/metpy.calc.rst, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
1. Fix issue with SRH returning missing value instead of 0 for pos/neg parts of SRH. Works around numpy/numpy#11736
2. Fix #902. The sounding in question hits a corner case where the fact that were did not include the LCL in the calculated parcel profile significantly affected the intersection points with the sounding. The right thing to do is use the LCL in the profiles in these calculations (`lfc`, `el`, `surface_based_cape_cin`) by default. As a result, this PR significantly refactors the profile calculation and adds an API function for `parcel_profile_with_lcl` that returns (pressure, temp, dew point, profile) all with the LCL included.
Also fixes a couple tests impacted by the LCL change.
=> Calculation fixes

examples/cross_section.py, examples/gridding/Natural_Neighbor_Verification.py, examples/gridding/Point_Interpolation.py, examples/gridding/Wind_SLP_Interpolation.py, metpy/plots/tests/test_skewt.py, setup.py, tutorials/xarray_tutorial.py
- Update pinning for pooch 0.1.* I think we can trust bug fix releases. 😁 Also, apparently our `environment.yml` was already doing this (by accident IMO), but now `setup.py` will allow too.
- Tweak tests to pass on matplotlib 3.0. Small bug in a certain path of `MultipleLocator` (matplotlib/matplotlib#12313) broke the tests--but this path is only triggered with non-default matplotlib style (which happens to be used by pytest-mpl). Just adjusting our tests is good enough to avoid the bug.
I *expect* our tests to pass with this PR.
=> Update for requirements

metpy/plots/skewt.py
We were calling deprecated functions in our code. I'm working up a way for CI to catch this, but this is the essential bit for 0.9.2 and partially addresses #934
=> Replace deprecated interp with interpolate_1d

examples/plots/US_Counties.py
No longer needed in 0.9.2 and makes the example even shorter!
=> Remove edgecolor from county example

metpy/calc/tests/test_calc_tools.py, metpy/calc/tests/test_thermo.py, metpy/tests/test_xarray.py
While doing local dev with python 3.6 and pytest 3.81, I noticed lots of the following warnings spewed.
```text
/opt/miniconda3/envs/prod/lib/python3.6/site-packages/_pytest/fixtures.py:799: 
RemovedInPytest4Warning: Fixture "test_ds" called directly. 
Fixtures are not meant to be called directly, are created automatically when test functions 
request them as parameters. 
See https://docs.pytest.org/en/latest/fixture.html for more information.
res = fixturefunc(**kwargs)
```
So I attempted to address these and note that it is not easy to use fixtures in parameterize, see pytest issue 349
=> address pytest fixture warnings emitted by pytest==3.8.1

examples/isentropic_example.py, metpy/calc/basic.py, metpy/calc/cross_sections.py, metpy/calc/indices.py, metpy/calc/kinematics.py, metpy/calc/tests/test_calc_tools.py, metpy/calc/tests/test_indices.py, metpy/calc/tests/test_kinematics.py, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py, metpy/calc/tools.py, metpy/constants.py, metpy/interpolate/grid.py, metpy/interpolate/one_dimension.py, metpy/io/cdm.py, metpy/io/nexrad.py, metpy/plots/skewt.py, metpy/plots/station_plot.py, metpy/tests/test_units.py, metpy/xarray.py, setup.cfg, tutorials/xarray_tutorial.py
- Pin pycodestyle  to < 2.4 in `environment.yml` to avoid installing newer version that conda-forge allows. This new version starts complaining about breaking lines with binary operators at the end rather than beginning (which I'm coming around to); more annoying is that this set of versions is not what you get from PyPI, which is why we only fail on windows ATM. For now, let's pin. Once flake8 > 3.5.0 is out on PyPI, we can revisit (at which point we'll see errors on Travis to remind us)
- Clean up warnings from tests by using pytest's warning filter rather than `warnings.simplefilter`
- Remove filtering our deprecation warnings from `test_indices`; these should be errors now anyway.
=> Test cleanup

metpy/plots/station_plot.py
Numpy 1.16 will deprecate numpy.asscalar.
=> MNT: Remove use of numpy.asscalar

metpy/deprecation.py, metpy/interpolate/tests/test_points.py, metpy/tests/test_deprecation.py, metpy/tests/test_units.py
Feel free to take this or send it to the bitbin in the sky...
Perhaps the most questionable change here is my code removal in `metpy/deprecation.py`.  For the life of me, I could not come up with a test case that deprecated a `@classmethod` and was able to trigger that logic block in the code.  The upstream code in `matplotlib` does not have this code block either.  I did add an additional explicit `test_deprecation.py` that covered some more lines.
No worries if all this gets rejected.
=> Marginally increase testing coverage

metpy/io/__init__.py
=> MNT: Make io module docstring conform to standards

.appveyor.yml, metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py
This PR updates the `potential_vorticity_baroclinic` function to work properly for both isentropic as well as isobaric data. It adds the appropriate additional terms needed to calculate the isobaric version properly. This closes #895.
As a result of this re-write it will require the function to have input data in (p, y, x) format in order to work properly; I could not think of or construct a method to be more amenable - this is partly due to needing to know the axis to perform the proper derivatives (comments welcome). This new function will work for either isentropic or isobaric driven data without any additional keyword arguments.
Some tests removed as a result of needing specific axes format, but added some for read datasets for both isentropic and isobaric level data.
=> Update PV calc for isobaric

metpy/tests/test_xarray.py, metpy/xarray.py
Using log.warning instead of  warnings.warn
=> Change XArray projection warning to a logged message

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py, metpy/plots/skewt.py
Moist and dry adiabats on the Skew-T now go through 1000 mb (fixes #85).
As a side consequence, `moist_lapse` and `dry_lapse` now take an optional reference pressure. If not specified, it defaults to the first element in the pressure array, the same functionality as before.
=> Skew-T adiabat reference pressure

environment.yml, setup.py
=> relax pooch requirement to >=0.1

metpy/tests/test_xarray.py, metpy/xarray.py, tutorials/xarray_tutorial.py
This PR adds `.loc[]` and `.sel()` to both the DataArray and Dataset accessors to allow for unit-aware indexing/selection. Also, for DataArrays (for which axis types are uniquely determined), I also added in selection via the axis name ('time', 'vertical', etc.).
As an example, now something like this can be done:
```python
temperature.metpy.sel(vertical=500 * units.hPa)
```
Closes #970.
~~Also, I reused some code from xarray with modification for this (the `loc` indexers). What is the proper way to cite this in the code given [their license](https://github.com/pydata/xarray/blob/master/LICENSE)?~~
=> Add unit- and axis-aware selection to the metpy accessors

metpy/calc/tools.py, metpy/tests/test_xarray.py, metpy/xarray.py
Previously, any existing `axis` attribute was removed in `parse_cf()`. Now, with this PR, the axis is tracked in `_metpy_axis` to avoid collisions.
Closes #981.
=> Change axis-tracking attribute from axis to _metpy_axis

metpy/interpolate/slices.py, metpy/interpolate/tests/test_slices.py
As discussed in Unidata/MetPy#949, the error message from the cross
section function could be made clearer in the case where coordinate
information is missing. This catches the AttributeError that was raised
and instead raises a more informative error. The docstrings have also
been updated.
=> Make necessary coordinate information for cross sections clearer

.travis.yml, docs/conf.py, docs/installguide.rst, environment.yml, metpy/deprecation.py, setup.py
Pin pint to have a green build while failures with pint 0.9 are being investigated.
=> Pin pint <= 0.8.1

setup.py
This is breaking everything: tests, doc builds, etc.
=> MNT: Disallow pyproj 2.0.0

metpy/calc/kinematics.py
This PR updates the documentation of kinematic calculations to be clear that latitudes are needed in either radians or as an appropriately united array. Fixes issue #1010. Comments on a different formation of the wording is welcome.
=> updates docs for latitude units

.travis.yml, CONTRIBUTING.md, docs/index.rst, docs/installguide.rst, docs/units.rst, setup.cfg
Sphinx-gallery changed their output and it completely buggers doc8.
Probably shouldn't be running doc8 on generated files anyway. This does
eliminate checking some of our index.rst files, but it's a small price
to pay to have things working again.
=> MNT: Update doc8 configuration

CONTRIBUTING.md
Replace some rst style links with markdown syntax.
=> Fix RST style links in the Contributing Guide

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
This PR depends on #1022 and addresses additional problems with the `lfc()` calculation. Parts of the logic in `lfc()` assume the parcel for which the LFC is desired is the surface parcel. One test case is updated, and another is added to show the differences.
The first example:
Because the current code uses the surface parcel when computing the LCL internally, the LFC is determined to be over 1000 mb. However, the LCL of the mixed parcel is under 1000 mb. With this PR, the correct value of 982 mb for the LFC (and LCL) is returned.
The second example:
Without the fixes to the find_intersections() logic that this PR includes, the LFC is computed to be 990 mb (which is the LCL), but the actual value is 983 mb, as indicated in the new test.
=> Fix poor assumptions in lfc() logic

docs/references.rst, metpy/plots/tests/test_station_plot.py, metpy/tests/test_units.py, metpy/xarray.py
Build was failing, this is a maintenance pull request to fix errors with quote marks in three different files.
=> MNT: fix flake8 errors

metpy/cbook.py
matplotlib.cbook.iterable was deprecated in Matplotlib 3.1
=> migrate mpl.cbook.iterable to numpy.iterable

metpy/tests/test_xarray.py, metpy/xarray.py
Because pint does not support '%' as a unit, this update converts DataArray units that are provided as such to 'percent'.
Fixes #1038.
=> Units: convert '%' to 'percent' for within the xarray MetPy accessor

metpy/plots/_mpl.py
Update to test_mpl.py to update deprecated function for matplotlib 3.1 to address #1044
=> Updated deprecated function in matplotlib 3.1

metpy/plots/declarative.py
This is a work in progress that partially addresses #1016 with improved documentation for the declarative syntax. Feedback welcome from all.
One question: there are a number of attributes that are listed in the online documentation that can't actually be set by the user, is there a way to not include those? I have left those attributes with the default language. Some examples of these attributes are: cross_validatation_lock, griddata, name, parent, and plotdata.
=> first pass at better docs for declarative

metpy/calc/cross_sections.py, metpy/calc/tests/test_calc_tools.py, metpy/calc/tools.py, metpy/interpolate/slices.py, metpy/interpolate/tests/test_slices.py, metpy/tests/test_xarray.py, metpy/xarray.py, tutorials/xarray_tutorial.py
This PR changes how the systematic coordinate identification is done: previously, the parsing was a part of `parse_cf()` on the Dataset accessor, but now, as requested in #1030, it is done on-demand within the DataArray accessor. This allows the coordinate identification features to be used even when someone only has a DataArray and doesn't have a Dataset. These changes also come with a rename of the accessors to `MetPyDataArrayAccessor` and `MetPyDatasetAccessor`, and changing `check_axis()` from being a class method on the Dataset accessor to a function in the xarray module (since it is now used several times in calc and interpolate). Since it was an easy change along the way, this PR also sets the `keep_attrs` option on `xarray.Dataset.apply()` to `True` in `parse_cf()` to keep the …
=> xarray Coordinate Identification Refactor

metpy/interpolate/grid.py
Improves documentation of the interpolate_to_grid function to specify that the coordinates of the grid can be in linear distance or degrees.
Fixes #1060.
=> Interpolate_to_grid doc update

metpy/xarray.py
Adds a simple warning that latitude_longitude projection is being assumed if no CRS is found and file has lat/lon variables. 
Closes #1039.
=> Xarray: Add warning if lat/lon is assumed for projection

metpy/calc/thermo.py
A quick fix to the docstrings for `vertical_velocity` and `vertical_velocity_pressure`, since the equations weren't rendering in the docs. Also, corrects one other typo I stumbled upon.
=> Fix docstring for vertical velocity functions to render equations

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
This update to the lfc() function allows for multiple LFCs to be found in soundings with multiple unstable layers. This change fixes #992 and begins to address #862. The current method only finds the lowest LFC, which is usually not the one of interest. The updated method adds a new Boolean variable to the LFC function allowing either the lowest-pressure LFC or all LFCs to be returned. Default is the return of the lowest-pressure LFC only.
=> Provide identification of multiple LFCs and ELs

metpy/xarray.py
Xarray v0.12.2 changed how it handles the DatetimeAccessor. As a result, a conditional import is needed to allow for Python 2 support. This can be updated back to a simple import of the v0.12.2 version once Python 2 support is dropped.
Fixes #1077.
=> Conditional import of the DatetimeAccessor due to xarray update

examples/cross_section.py
Per feedback from an eSupport question, a note was added at the end of the cross-section example that the x-axis variable can be anything of the same length (mainly providing clarification that this can be latitude as well as longitude) and that the axis can be relabeled to look like the NCL example of lat/lon pairs if so desired.
=> DOC: Clarify x-axis variables in cross section example

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
Previous implementations was a naive implementation that directly translated formulas from source material. It included a lot of division and subtraction, resulting in catastrophic cancellation and severe loss of floating point precision. New formulation is just an algebraic reformulation that avoids these problems.
In fixing #1075, I went ahead and refactored `height_to_geopotential` as well to address similar problems with floating point precision.
=> BUG: Fixup geopotential<->height calculation (Fixes #1075)

metpy/_vendor/__init__.py, metpy/_vendor/xarray.py, metpy/tests/test_xarray.py, metpy/xarray.py
As suggested in #1077, this PR vendors `either_dict_or_kwargs`, `expanded_indexer`, and `is_dict_like`, which are used in `metpy/xarray.py`, instead of using them from the internal API of `xarray.core` (`DatasetAccessor` is handled in #1078).
This is the first time I've tried vendoring code like this, so please do let me know if this is the right approach to take or if the code and/or license should be included elsewhere. Also, should I add tests of the vendored functions?
=> Vendor internal imports from xarray.core in xarray.py

metpy/calc/basic.py
In looking at #1075, I noticed that the reference for the geopotential <-> height conversions didn't match the page/equation that was in Wallace and Hobbs (looks like it was page/equation from Holton given in [#678](https://github.com/Unidata/MetPy/pull/678#issuecomment-351031816)), and the exact formulas used are not in the docs. This is a quick PR to make those changes.
=> Add formulas to geopotential functions in docs and correct reference

metpy/plots/skewt.py, metpy/plots/tests/test_skewt.py, setup.py
This fixes up some issues caused by matplotlib 3.1:
- Thresholds for images tests--there were some subtle pixel level changes, not clear why, but really minor changes to image results
- Fix up ticking changes, implementing #987
=> Matplotlib 3.1 fixes

docs/installguide.rst, environment.yml, setup.py
See previous discussion with #978, my issue is that conda-forge has `pooch=0.4` now which ends up downgrading metpy to an old version that did not have pooch pinned :)  So will see if we can march pooch forward here and then with another PR to the conda-forge recipe.
=> allow any pooch >= 0.1 to be used

environment.yml, metpy/cbook.py, metpy/interpolate/one_dimension.py, metpy/tests/test_units.py, metpy/units.py, setup.py
As discussed in #997, there were two main issues with pint 0.9 and MetPy: `@units.wraps` and single value Quantities being evaluated as iterable. This PR implements an alternate way of ensuring matching units (and stripping the units) for the interpolation functions that previously used `@units.wraps`, as well as an `iterable` function that checks against the magnitude of the argument.
The two tests with matplotlib and scalar Quantities remain broken. I marked them as skipped for pint 0.9, but if a monkey patch of some kind based on the fix discussed in https://github.com/hgrecco/pint/issues/751 is preferred, I can see what can be done.
Fixes #997.
=> Fix pint 0.9 errors from units.wraps and iterable

metpy/calc/basic.py
Presently, there is no mechanism to control the `mask_undefined` behaviour of the `apparent_temperature` helper.  This commit allows the API user to control this for the underlying `heat_index` and `windchill` methods.
=> allow mask_undefined control on apparent_temperature calc

metpy/plots/station_plot.py, metpy/plots/tests/test_station_plot.py
As raised by an eSupport issue, x and y need to be arrays in order for CartoPy to transform wind barbs within StationPlot.
=> Force x and y to be np.arrays within StationPlot

docs/_templates/overrides/metpy.calc.rst, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Calculate specific humidity from dew point temperature and pressure. Leverages existing computations for saturation mixing ratio and specific humidity from mixing ratio. Test uses same values as in test_dewpoint_specific_humidity. Closes #791
=> Specific Humidity From Dewpoint

README.rst, docs/index.rst, docs/installguide.rst, examples/README.txt
Given conversations at SciPy, we should have more links to the Python Gallery throughout the documentation (until we decide what to do with the gallery in the long-term). I think I caught more of them, but happy to add more as desired.
=> More links to Python Gallery

metpy/plots/mapping.py, metpy/plots/tests/test_mapping.py
Drop `central_longitude` from `attrs`, similar to what's done in `make_geo`.
Closes #1101.
=> Drop central_longitude from mercator projection

.appveyor.yml, .travis.yml, docs/references.rst, metpy/calc/basic.py, metpy/calc/tests/test_basic.py
- adds additional corrections used by the NWS operational heat index
- removes default lower bound of 40% Relative Humidity for undefined HI
- updates tests as this change produces different test results
- closes #1096
=> modify heat_index to replicate NWS algorithm

metpy/calc/tests/test_calc_tools.py, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py, metpy/calc/tools.py
Updated LFC, EL, and _find_append_zero_crossings to calculate intersections via log-pressure interpolation in the vertical. This fixes #932, where linear pressure interpolation was causing the EL to be misplaced from the visual crossover on SkewT plots. Since the LFC, and resultantly CAPE/CIN are calculated using the same method, I updated those functions as well. This update will more greatly affect calculations for coarse vertical-resolution data, with minimal changes to the results from dense data. Note that the data from #932 was already a test case, so no new test cases were added.
=> Calculate intersections with log-p interpolation (LFC, EL, CAPE/CIN)

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
PR #1095 introduced a bug with how mask_undefined behaved. This fix
also updates one previous test to reflect the corrected logic.
=> correct mask_undefined apparent_temperature logic

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Previously, the SBCIN and MUCIN did not match values. This was due to the exclusion of the LCL as a point in the MU profile, while it was included in the SB profile. This PR adds a conditional statement to examine if the most unstable parcel starts below the LCL, and if so, includes the LCL in the profile path. Otherwise, the calculation remains the same as before. 
Closes #1108.
=> Include LCL in MUCIN calculations if parcel starts below LCL

metpy/tests/test_xarray.py, metpy/xarray.py
This PR implements the suggested fix in #1092, with a test based on the example provided.
Closes #1092.
=> Wrap check_axis unit checking to not fail on bad unit

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Add a default, basic PR template. Also move from legacy singular issue template to the newer, "select an option" issue template style on GitHub.
No way to really test this before merge, but are there any suggestions on wording? Things to add? More options?
=> Update GitHub issue/PR templates

.codecov.yml, metpy/calc/tests/test_basic.py, metpy/calc/tests/test_calc_tools.py, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py, metpy/interpolate/geometry.py, metpy/interpolate/one_dimension.py, metpy/interpolate/tests/test_geometry.py, metpy/testing.py, metpy/tests/test_units.py
* Update implementation of `assert_nan` to actually assert rather than call `pytest.fail()`.
* Add some tests for failing cases in test code--these weren't covered before
* Make `testing.py` count as part of the `tests` target for codecov. This way we can ensure we're actually running all of it
I expect this to fail right now because we have an `ignore_deprecation` decorator that's not used. Once I prove that codecov fails, I'll be updating to rename and use that decorator across the test suite.
**Update**
So now I've also:
* Used the decorator for tests of deprecated functionality
* Added a couple more tests to hit a few uncovered lines
* Completely blew away an unnecessary function in `geometry.py` and improved coverage there
* Reworked a bit of `isentropic_interpolation` to remove an …
=> Updates for testing

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
Deprecate `tmpk_out` argument in favor of `temperature_out` in the `isentropic_interpolation` function. This will be added to the removal list for 1.0.
=> Deprecate `tmpk_out` in favor of `temperature_out`

examples/plots/Hodograph_Inset.py, metpy/plots/skewt.py, metpy/plots/tests/test_skewt.py
Update to docstring to be more informative, and to rename bounds to cint to more accurately describe what this method is doing. Also redid the example using `plot_colormapped` to plot by height, which is more informative for a user (similar to SharpPy). 
This should go in before #1117.
=> plot_colormapped update for Hodograph

docs/_templates/overrides/metpy.calc.rst
Unindent section headers in the `MetPy.calc` docs, so sphinx doesn't try to import them. Removes warnings in sphinx<2.2.0, removes failure in sphinx=2.2.0. 
I still can't believe this was all that was broken.
=> Unindent section titles in metpy.calc docs to prevent sphinx from failing

metpy/calc/kinematics.py, metpy/calc/tests/test_kinematics.py, metpy/future.py
Adds a FutureWarning for the next two releases before reordering the variable order of `ageostrophic_wind` and breaking in 1.0.
=> Add FutureWarning to ageostrophic_wind for variable reorder

metpy/calc/basic.py, metpy/calc/tests/test_basic.py
Adds a `convention` kwarg to `wind_direction`, which allows for the oceanographic (to) direction to be returned if specified. Defaults to 'from', which is the meteorological convention. Returns a KeyError if something other than 'to' or 'from' are passed to `convention`.
=> Add convention to wind_direction

metpy/interpolate/grid.py, metpy/interpolate/tests/test_interpolate_tools.py, metpy/pandas.py
Fixes https://github.com/Unidata/MetPy/issues/1029
```
import numpy as np
import xarray as xr
import pandas as pd
from metpy.cbook import get_test_data
from metpy.interpolate import interpolate_to_grid
df = pd.read_csv(get_test_data('station_data.txt'))
df = df.iloc[:, [2, 3, 5]]
df.columns = ['lat', 'lon', 'tmp']
gx, gy, img = interpolate_to_grid(df['lon'], df['lat'], df['tmp'], interp_type='natural_neighbor', hres=1)
```
I didn't use hasattr(var, 'values') because it picks up on the dict.values() too, but the `values` in dict are methods, not attributes, leading to an uninstantiated builtin-function.
This decorator is only useful for operations that doesn't require units since `pd.Series([0, 1, 2]) * units('K')` doesn't actually add the units or store them anywhere, so any function that …
=> Pandas support for interpolate grid

metpy/tests/test_xarray.py, metpy/xarray.py, tutorials/xarray_tutorial.py
**Motivation:** When using `xr.open_dataset` with OPeNDAP to access model/analysis data on a THREDDS server, or really open any large dataset with many different variables/vertical coordinates, I like to trim down on the number of variables kept in the dataset to have cleaner output. Subsetting before `ds.metpy.parse_cf()` makes it easy to forget the grid mapping variable, and subsetting after is not as efficient, so, it would be nice to pass a list of variable names to `ds.metpy.parse_cf()` to only parse the variables needed. This could also make it easier to work around having multiple grid mappings in the same dataset by being able to subset on the variables that share a common grid mapping (xref https://github.com/Unidata/MetPy/issues/965).
This PR modifies `parse_cf()` to accept an …
=> Allow lists of variable names in parse_cf

metpy/tests/test_xarray.py, metpy/xarray.py
This is a slight refactor to the axis search and parsing functionality to assign auto-parsed coordinates on a type-by-type basis, rather than all at once. Follows up on https://github.com/Unidata/MetPy/pull/1058. Implements a test that replicates the issue observed in #1124, which is expected to fail before this PR, and pass with it.
=> Refactor xarray axis search to resolve dataset shared coordinate issue

docs/references.rst, metpy/calc/basic.py, metpy/calc/tools.py
Update citation for the standard atmosphere to the U.S. 1976 standard published by NOAA/NASA/USAF. While there are minute differences to the international standard, these only occur above the stratosphere. Additionally, this spec is readily available online, unlike the international one which is hidden behind paywalls frequently.
=> Update standard atmosphere reference to U.S. 1976

.travis.yml, examples/cross_section.py, metpy/calc/basic.py, metpy/calc/indices.py, metpy/calc/kinematics.py, metpy/calc/tests/test_basic.py, metpy/calc/tests/test_calc_tools.py, metpy/calc/tests/test_kinematics.py, metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py, metpy/calc/tools.py, metpy/cbook.py, metpy/plots/skewt.py, metpy/tests/test_cbook.py, metpy/tests/test_xarray.py, metpy/units.py, metpy/xarray.py, tutorials/xarray_tutorial.py
There were *many* places in the code base where passing pint Quantities to numpy functions was assumed to return a plain ndarray. This behavior will no longer necessarily be the case after pint implements `__array_function__` in a future version, and so, this modifies usage to explicitly request magnitude where it is assumed that quantities are stripped. Also, makes some miscellaneous changes with regards to the split between scalar and sequence quantity classes. (xref https://github.com/Unidata/MetPy/issues/1111)
Similarly, there was one place where the xarray accessor assumed that a pint Quantity being inserted into a DataArray would cast to a plain ndarray. This will no longer be the case with xarray's next release and the implementation of `__array_function__` in pint.
Also, makes …
=> Updates to pint/xarray master branch (and xarray v0.13) compatability

.travis.yml
We were accidentally uploading wheels from the development builds of
xarray and pint. Still not sure why pip thinks it can install the
development version of xarray 0.13 on Python 2.7, but it does. This
should keep those from uploading.
=> MNT: Fix Travis build failures from weird dependencies

docs/_templates/autosummary/module.rst, docs/_templates/overrides/metpy.xarray.rst, docs/api/index.rst, docs/override_check.py, metpy/xarray.py, setup.cfg
This adds docstrings to attributes and methods on the xarray accessors where they were missing, and tweaks a few others. Also adds the xarray module to the Reference Guide via autosummary.
This is an early attempt at getting this set. Beyond going back through all the docstrings, still need to figure out the proper way to link to CF website and the xarray tutorial, as well as how to avoid the `__init__` docstring being added to the docstring displayed for the overall class (or alternatively, find the best way to let users know not to instantiate these classes directly).
=> Add xarray module to Reference Guide

metpy/calc/tests/test_thermo.py, metpy/calc/thermo.py
First, allows for return of LCL/LFC/EL temperature in the units of the input temperature. There may still be a bug in `SkewT.plot` that I need to investigate more, as I don't think things are getting auto-converted to the same units when you plot multiple things. 
Second, this disallows a LFC below a LCL when an "EL" is also below the LCL. This bug was causing CAPE to calculate as the LFC was being adjusted to the LCL, and it didn't see an end to the profile (ending up in very large values of negative CAPE).
=> Return input temperature units for LCL/LFC/EL temperature, disallow LFC if EL below LCL

.travis.yml
This changes how we handle credentials for uploading to PyPI. We used to have my PyPI password, encrypted, in `.travis.yml`. Now that PyPI has support for tokens (which have only *upload* access), we can use that instead. This is set as an encrypted environment variable, `PYPI_PASSWORD` over on our Travis repo config (not in `.travis.yml`). This also makes it easy to update if there's something wrong with it at release time. Huge win to our security. It does seem like the token is attached to my account rather than the project, but at least it's not my own password nor does it have *all* permissions.
I've played with this on the PyPI test instance on the `test-travis` branch, since it needs to be a live branch to use Travis' deploy support. Everything seems to be working. You can see it …
=> Update PyPI upload

docs/_templates/autosummary/module.rst, docs/_templates/overrides/metpy.plots.ctables.rst, examples/formats/NEXRAD_Level_2_File.py, metpy/plots/ctables.py, metpy/plots/tests/test_ctables.py
Deprecate the viridis colortable and suggest usage of the matplotlib version.
=> Deprecate the viridis colortable

metpy/calc/tests/test_calc_tools.py, metpy/calc/tools.py
Update `parse_angle` to allow arrays, `pandas.Series`, etc. Includes additional tests for these types and for single input, which was previously allowed but not tested for.
=> Update `parse_angle` to allow any array-like object

.travis.yml
This should keep the wheels from getting deleted when Travis cleans up
for deploying releases. Deleting them otherwise causes them to be
"re-downloaded" when building the final wheels, resulting in mass
upload to S3 on release.
=> MNT: Change wheel directory on Travis

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
Ah, precision issues. This bug was due to the LCL pressure having rounding issues and being greater than the surface profile pressure in the helper function for `parcel_profile_with_lcl`. A simple rounding to take care of the precision issue solves this.
=> Fix precision issue with interpolation in profile helper

src/metpy/calc/kinematics.py
This change removes the requirement that divergence must take wind speed. There are other variables that the divergence of a vector can be taken, which is not wind components. The prime example is Q-vectors.
- [x ] Fixes #1196
=> fix divergence unit requirement

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
Adjusts the use of `np.isclose` to support grids, as arrays can be passed to `lcl` and it will return arrays. This may solve #1199, depending on what others want from there. This preserves functionality without clarifying docstrings at all. That could be added to this PR as well. 
-->
=> Add support for grids when surface is LCL

src/metpy/calc/indices.py, src/metpy/calc/thermo.py, src/metpy/calc/tools.py, tests/calc/test_calc_tools.py, tests/calc/test_indices.py, tests/calc/test_thermo.py
Remove NaNs if present in dewpoint or pressure and calculate PW.
=> Allow PW calculation when NaNs present

src/metpy/xarray.py
With xarray v0.14 (in particular, after https://github.com/pydata/xarray/pull/3234), MetPy's usage of `xarray.Dataset.apply` in `parse_cf` results in a duplicated coordinate issue, like that observed in 2fe00b6. It seems like it is a very subtle index issue with xarray, however, it can be avoided entirely through using `xarray.merge` instead. ~~The likely upstream issue remains, but this at least fixes MetPy for now.~~
=> Quick fix for test_narr_example_variable_without_grid_mapping test (broken by xarray v0.14)

src/metpy/io/gini.py
Adds a try/except block to support xarray v0.14 with the renaming of FrozenOrderedDict to FrozenDict. Addresses one problem in #1203.
=> Fix GiniFile import of xarray FrozenDict

src/metpy/calc/basic.py
As mentioned in passing with #1209, `pint.Quantity` appears to have an issue when `numpy.asarray` is called with it as the argument.  This change hopefully avoids the pint plumbing and allows direct usage of the magnitude, which is what the code wants to do anyway.
I also removed the no longer valid comment about operating on arrays without units.
=> avoid pint trouble with np.asarray

src/metpy/calc/tools.py
Future proof code to allow `metpy.calc.basic` to import functions in `metpy.calc.tools` without a potential circular import.
=> avoid potential circular ref by lazy import

docs/_templates/overrides/metpy.calc.rst, src/metpy/calc/thermo.py, tests/calc/test_thermo.py
As discussed in #1113, `dewpoint_rh` is inconsistently named with the rest of the thermo calculations; it should instead be `dewpoint_from_relative_humidity`. This deprecates the old function name in favor of the new one, with removal planned in v1.0.
=> Deprecate dewpoint_rh in favor of dewpoint_from_relative_humidity

src/metpy/calc/tools.py, src/metpy/xarray.py, tests/calc/test_calc_tools.py, tests/test_xarray.py
In working with some high-temporal-resolution data with MetPy and xarray, I realized that the xarray time derivative only allows precision to the nearest second, since I had implemented it via conversion to a Unix timestamp in #899. Oops!
This PR modifies this to use `np.timedelta64[us]` to permit microsecond precision instead, which should be fine enough for any meteorological application I can think of, but also coarse enough to fit climatological timescales in 64 bits (if I'm interpreting https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#datetime-units correctly).
Since `DataArray.metpy.as_timestamp()` was previously documented in the public API in #1175, I also deprecated it instead of removing it in favor of `DataArray.metpy.time_deltas`.
Also, should this be a property …
=> Update xarray time derivative for subsecond precision

.travis.yml
- Code Climate apparently changed tools on us, so update that to avoid a traceback
- Tweak CodeCov to use the coverage.xml we generate anyway and avoid it search for other files
=> Update test coverage services

src/metpy/calc/indices.py
Adds an example to the PW doctoring on usage to clarify that an array of points is needed to calculate PW, due to the fact that it's derived via integration.
=> Add example to PW docstring

src/metpy/calc/cross_sections.py, src/metpy/calc/tools.py, src/metpy/interpolate/slices.py, src/metpy/xarray.py, tests/test_xarray.py, tutorials/xarray_tutorial.py
To resolve #1090, this commit changes the CF-axis-based labeling of coordinate identification ('T', 'Z', 'Y', 'X'), to a more general labeling system (currently with labels 'time', 'vertical', 'y', 'latitude', 'x', and 'longitude'). This also permits the needed changes of #1090, which are adding lat/lon coordinate identification and setting the stage for x/y to be 1D only. Also, explicit tests are added for the following cases in regards to coordinate identification:
- 1D latitude/longitude (which should also be assigned as y/x)
- 2D latitude/longitude with existing 1D y/x coords
- 2D latitude/longitude without 1D y/x coords (which assigns to y/x as well as deprecated behavior)
=> Modify xarray coordinate identification from CF axis to generic labels, permitting latitude/longitude identification

.appveyor.yml, .travis.yml, examples/gridding/Find_Natural_Neighbors_Verification.py, examples/gridding/Natural_Neighbor_Verification.py, src/metpy/interpolate/geometry.py, src/metpy/interpolate/points.py, tests/interpolate/test_geometry.py, tests/plots/test_declarative.py, tests/plots/test_skewt.py, tests/plots/test_station_plot.py, tests/plots/test_util.py
Fixes to tests due to changes in:
* SciPy 1.4.0rc1
* Matplotlib 3.2.0rc2
Also fixes Travis to use local checkout of test data rather than fetching it all again.
=> Fixes for pre-releases

src/metpy/calc/basic.py, src/metpy/calc/thermo.py, tests/calc/test_basic.py, tests/calc/test_thermo.py
Follow-on from #1059 (see that PR for discussion about changes within this PR). Adds the `most_cape` and `wide` options for `lfc` and `el`. The `wide` implementation is pretty straightforward. The `most_cape` is pretty hacky at the moment, and could probably use some refactoring. Tests have been added based on the one case provided in #862, but additional test cases could be good if anyone has any to contribute.
Also adds options to specify which LFC and EL to use to calculate CAPE and CIN. It defaults to `bottom` and `top`, respectively, which was the previous implicit assumption before #1059 was merged. 
Finally, cleans up a couple docstrings that still stated we interpolated intersections linearly, which was changed to logarithmically in #1062.
=> Add 'wide' and 'most_cape' options for LFC/EL, options for CAPE

src/metpy/plots/wx_symbols.py, tests/plots/test_wx_symbols.py
This PR adds a function to robustly find an appropriate numeric weather code based on the first grouping of current WX METAR code (e.g., BR, RA, +RA, etc.) for plotting on a surface station plot.
May need to add a test or two to get coverage up. Open to changes in naming conventions.
=> Adds function to get numeric wx code

src/metpy/calc/thermo.py, src/metpy/calc/tools.py, tests/calc/test_thermo.py
As mentioned in https://github.com/Unidata/MetPy/issues/1115#issuecomment-567320228, there were a number of issues that came up when running the test suite against the current state of pint's master branch. This PR restores the tests (except those in #1174) back to passing (that is, locally; I'm not sure what's going on with CI).
=> Further updates to pint master branch compatibility

.travis.yml, setup.cfg, src/metpy/plots/declarative.py, src/metpy/plots/station_plot.py
- Fix declarative `show()` implementation: we were trying to avoid `pyplot.show()`, but `figure.show()` is insufficient. Also, we use `pyplot` all over the place now, so no need (#1207)
- Remove outdated CartoPy work-around code in `StationPlot`. This was for CartoPy <= 0.14.3. CartoPy 0.15.0 is almost 3 years old now. (#1229)
=> Plotting fixes

docs/_templates/overrides/metpy.calc.rst, src/metpy/calc/thermo.py, tests/calc/test_thermo.py
This PR adds a `mixed_layer_cape_cin` function. Given that this hasn't existed before and the numerous (almost unimaginable) number of caveats and special cases that could exist, I know this is a Pandora's box of potential issues. That being said, I think this is something that is frequently desired and currently takes users more lines of code than is probably desirable, so I took a crack at it to see what it could look like. Unfortunately, I don't think the answer in this [StackOverflow answer](https://stackoverflow.com/questions/52737277/sounding-mixed-layer-cape-calculation) is the fully appropriate solution, as the parcel profile won't include the LCL, which caused issues in MUCAPE (see #1108 and #1109) and would likely cause the same problem here too. Additionally, the documentation …
=> Add mixed-layer CAPE

src/metpy/calc/basic.py, tests/calc/test_basic.py
As referenced in https://github.com/Unidata/MetPy/pull/1144 and https://github.com/Unidata/MetPy/issues/1115, pint's change in the value of `G` has been problematic for the tests of the geopotential <-> height functions.
It was suggested to change these functions to utilize standard gravity. However, after doing a deep dive into the [original implementation](https://github.com/Unidata/MetPy/issues/663) and the [finer points of gravity](http://glossary.ametsoc.org/wiki/Acceleration_of_gravity), it appears that the original implementation was based on assumptions of a spherical Earth and no centrifugal force effects. By basing these calculations on standard gravity instead (along with the below approximation for altitude adjustment), the formulation now includes the average effects of …
=> Change geopotential <-> height formulas to use standard gravity

src/metpy/io/metar.py, tests/io/test_metar.py
In testing the new metar parsing capabilities with the SAO WMO files that come across the LDM I ran across a problem when the date/time field was incorrect in the metar. An example is `266170`, which threw a `ValueError` from the datetime function when the hour fell outside of the range `0..23`. I was able to add another error to the try/except around determining date time and was successful in reading in a full file containing over 9000 observations.
Modified one test to cover this issue.
=> add exception catch

conftest.py, src/metpy/__init__.py, src/metpy/calc/basic.py, src/metpy/calc/thermo.py, src/metpy/calc/tools.py, src/metpy/units.py
In what is becoming a recurring pattern (#1144, #1250), MetPy has conflicts with the current state of Pint's master branch! This PR
- cleans up missing `None`s for non-unit arguments with `@units.wraps` (without this, pytest will not run due to an `ImportError`)
- fixes `wet_bulb_temperature` to not assume unit is stripped
- sets `PINT_ARRAY_PROTOCOL_FALLBACK` environment variable to '0' to disable Pint's problematic `__array_struct__` and `__array_interface__` fallback (xref https://github.com/hgrecco/pint/issues/924)
- creates a dummy array Quantity within a warning filter context to bypass Pint's NEP 18 warning
This is likely needed ASAP, since [Pint v0.10 is expected out soon](https://github.com/hgrecco/pint/issues/955)
=> Still further updates to pint master branch compatibility

src/metpy/plots/declarative.py, tests/plots/test_declarative.py
In further testing of reading a data file of METAR with the new parser functionality, the naming convention used in that portion of the code was not captured in the declarative plotting code for the time dimension name and the station dimension name. I've added a few other options and made the loop-up more robust. In addition, I raise an `AttributeError` if one is not found in the set list. It is relatively easy to remedy if a data frame does not contain the right name by either re-naming a column or creating a new column with one of the names. With the latest additions we cover what I know to be the most common names from the available data sources. This could likely be made more robust in the future, but without a CF convention used for surface observation data, it will be a larger …
=> Update PlotObs for time and station dimension naming

src/metpy/units.py, tests/units/test_units.py
Now that Pint v0.10 has been released, the string preprocessor option in https://github.com/hgrecco/pint/pull/911 is available. So, let's use it as discussed in #1134.
=> Add percent sign and UDUNITS exponent syntax support via Pint's new preprocessor option

src/metpy/xarray.py
Refactors `parse_cf` to not modify coordinates (which may be tied to immutable indexes) inplace, and instead reassign the coordinates in the recommended way. If this goes as my tests locally lead me to believe, this should fix the issues created with xarray in https://github.com/pydata/xarray/pull/3519.
=> Refactor parse_cf to not modify coordinates inplace

src/metpy/io/station_data.py, tests/io/test_station_data.py
This PR adds a simple function to use the `station_info` to add latitude and longitude values to a `pandas.DataFrame`, which will add plotting. This is useful for data obtained from sources that do not send lat/lon information with observations.
=> adds function to lookup and add station lat/lon to dataframe

src/metpy/plots/declarative.py
Closes #1277 with a minor documentation fixup to clarify how the colorbar actually works.
=> Fix the documentation around the declarative colorbar

docs/_templates/overrides/metpy.calc.rst, docs/gempak.rst, examples/calculations/Smoothing.py, src/metpy/calc/basic.py, src/metpy/calc/tools.py, tests/calc/test_basic.py, tests/calc/test_calc_tools.py, tutorials/xarray_tutorial.py
~~I've had a good part of this sitting in my repo for a while, and I've neglected to do anything with it since I don't have tests yet. While I *still* don't have tests yet, #1221 gave me the idea of going back to it and put it up as a PR to get any early feedback on it, since it does strip and reattach units in the smoother. Plus, this may motivate me to finally put together the tests.~~
This PR adds an arbitrary window smoother that utilizes a weighted sum over offset array subsets. Convenience methods for rectangular and circular windows are also added, along with refactoring the n-point smoother to use the new window smoother (which allows more flexible dimensionality). In an attempt to be compatible with base ndarrays, pint Quantities, and xarray DataArrays, there is also a array …
=> Add arbitrary window smoother and refactor existing smoothers

src/metpy/xarray.py, tests/test_xarray.py
Added the actual dataset to the call to xr.assign_coords() in assign_latitude_longitude() for the DatasetAccessor to resolve MetPyDatasetAccessor error. Relevant dialogue can be found in #1090.
=> Fix MetPyDatasetAccessor error in assign_latitude_longitude()

src/metpy/plots/mapping.py, tests/plots/test_mapping.py
- [x ] Closes #1343
- [x ] Tests added
=> added albers_conical_equal_area projection

src/metpy/units.py, tests/calc/test_calc_tools.py
=> Fixed a problem with diff'ing masked_arrays with units.

tutorials/xarray_tutorial.py
As suggested in #1358, this adds documentation regarding the requirement in pre-1.0 MetPy that units be in the attributes of your xarray object, and that `pint.Quantity` inside xarray will behave poorly.
I've made this to the 0.12.x branch, but I'm not sure if that's the best place to go for doc updates for 0.12 or not.
=> Add warning to xarray tutorial to avoid Quantity-in-xarray in pre-1.0 MetPy

docs/_templates/overrides/metpy.calc.rst, docs/references.rst, src/metpy/calc/thermo.py, tests/calc/test_thermo.py
=> Added function to calculate richardson number.

examples/formats/NEXRAD_Level_3_File.py
* Use NWS 8-bit colormaps instead of 16-level colormaps.  16-level data will still render correctly, but now we can plot the full resolution from 8-bit data such as the files for this example.
* Convert the data array to dBZ or m/s using the scaling indicated in the file header.  Calling `colorbar` to add a scale bar will now draw a scale with meaningful physical units.  Changes to the data encoding will no longer affect our ability to plot colors correctly.
* This also fixes a bug where the example was rendering small positive velocities in green when they should in fact be red.
=> Improved data and colormap scaling for Level3File example.

.github/dependabot.yml, src/metpy/plots/ctables.py
Enables [Dependabot](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#pull-request-branch-nameseparator) to update our pinned dependencies (and versioned GitHub workflow actions). This is a first cut at it to see what happens with some of our versions that are on older versions. There are certainly some tweaks to make, but there's no way to test this without committing something.
I also found a commit lurking on my old branch for this that improves an error message from parsing colortables. In lieu of submitting a PR for that, I'm throwing it on here.
=> Dependabot

src/metpy/units.py
Just a tiny quick fix for https://github.com/hgrecco/pint/pull/1123, which currently breaks a couple tests with Pint master. No tests or documentation needed to be modified.
=> Fix _check_argument_units for pint __eq__ returning duck array

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
Fixes the equivalent potential temperature issue noted in #1364 with masked arrays by not reconstructing quantity with multiplication (instead, reconstructing directly).
Tagging this for 1.0 (and basing on master branch), but should probably get cherry-picked for 0.12.2 as well?
Replaces https://github.com/Unidata/MetPy/pull/1373 due to needing to recreate my MetPy fork.
=>  Fix masked array issue in equivalent potential temperature

src/metpy/calc/basic.py, tests/calc/test_basic.py
Modify the `wind_direction` function so that masked arrays are supported when identifying directions <= 0.
=> Fix masked arrays breaking wind_direction #1390

ci/Current.txt, src/metpy/calc/tools.py, tests/calc/test_basic.py, tests/calc/test_calc_tools.py, tests/interpolate/test_slices.py
Fix some mixing of quantified and units-on-attribute DataArrays which breaks `xr.testing.assert_allclose` in xarray 0.16.0. This allows us to bump the current CI build to xarray 0.16.0.
=> Fix quantified/units-on-attribute mixtures in tests and derivative calculations for xarray 0.16.0

README.md, src/metpy/calc/basic.py, src/metpy/calc/thermo.py, src/metpy/io/metar.py, tests/plots/test_skewt.py, tests/units/test_units.py
A few clean-ups to some tests:
* One test that was marked as expected fail now passes (Thanks to pint 0.10.1). This closes #832.
* Removed a bunch of out-dated `skipif`s that apply to versions of things we no longer support.
* Removed warnings triggered in some calculations for a variety of reasons
* Slightly refactored `equivalent_potential_temperature` to use our own `potential_temperature` function
=> Test maintenance

src/metpy/interpolate/slices.py, tests/calc/test_cross_sections.py, tests/calc/test_kinematics.py, tests/test_xarray.py
As alluded to in https://github.com/Unidata/MetPy/pull/1430#issuecomment-665418689, bumping xarray's minimum version to 0.14.1 allows us to clear out some `PendingDeprecationWarnings` due to our usage of `Dataset.apply` and `Dataset.drop`, so that's what I've done here. From running the test suite locally, it goes from
```
1040 passed, 68 warnings in 60.24s
```
to
```
1040 passed, 42 warnings in 58.61s
```
Not sure if I should add any direct testing that these warnings are no longer issued?
=> Replace use of Dataset.apply and .drop to clear PendingDeprecationWarnings

docs/references.rst
RST formatting was not correct for Smithsonian tables.
=> Fix formatting of link in references

.github/workflows/docs-conda.yml, .github/workflows/docs.yml, .github/workflows/tests-conda.yml, ci/doc_requirements.txt, docs/conf.py
More updates to our GitHub Actions workflow, this times for building documentation:
- Move 3.6 build to macOS with conda
- Move 3.7 build to Windows with conda
- Add machinery to upload built docs (on main repo) to GH Pages. This has the benefit that it will work with tags *and* branches named e.g. 0.12.x. This gives us the capability to update the live/released docs just by pushing to the appropriate branch.
This gives us additional platform coverage for examples *without* adding additional builds to the overall matrix, which is a little large.
=> New GitHub Workflow for Docs

.github/workflows/tests-pypi.yml, conftest.py, src/metpy/plots/cartopy_utils.py, src/metpy/plots/declarative.py, src/metpy/plots/mapping.py, src/metpy/testing.py, src/metpy/xarray.py, tests/calc/test_calc_tools.py, tests/calc/test_cross_sections.py, tests/calc/test_kinematics.py, tests/interpolate/test_slices.py, tests/io/test_gini.py, tests/plots/test_cartopy_utils.py, tests/plots/test_declarative.py, tests/plots/test_mapping.py, tests/plots/test_station_plot.py, tests/test_xarray.py
* Make it possible to run tests without cartopy/pyproj
* Add CI run to check this configuration
* Refactor XArray support to no longer unconditionally import CartoPy
While it's nice to be able to have people run the tests with our so-called minimum dependencies, more importantly this allows us to have a CI configuration that proves to us that this is the case. This is not theoretical, at various points we've accidentally had a top-level import of pyproj (even though it's supposed to be "optional"), and before this PR on master we could not import MetPy without CartoPy installed.
This also makes it clear how much of our functionality relies on "optional" dependencies, which is a discussion for another issue...
=> Improve testing framework and infrastructure

ci/Current.txt, ci/Minimum, pyproject.toml, setup.cfg, src/metpy/_version.py, src/metpy/cbook.py, src/metpy/plots/_util.py, src/metpy/plots/ctables.py, src/metpy/plots/mapping.py, src/metpy/plots/skewt.py, src/metpy/plots/wx_symbols.py, src/metpy/testing.py, src/metpy/units.py
Overall goal is to remove the uses of `pkg_resources` since this requires `setuptools` at runtime. This can have performance consequences and there are now better ways to achieve the same functionality coming to the standard library.
* Update `pyproject.toml` to allow using `setuptools_scm` without a `setup.py`; we can still use `setuptools` but this gets us closer (#1321)
* Fix setting path to static data for registry on development
* Use `importlib.metadata` instead of `pkg_resources` to get version on installed copies; this has a backported version `importlib_metadata` that we need on Python < 3.8.
* Use `importlib.resources` instead of `pkg_resources` to get files (e.g. fonts, images, colortables); this has a backported version `importlib_resources` that we need on Python < 3.9
* Use …
=> Remove uses of pkg_resources

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
This is to explicitly fix passing masked arrays to surface_based_cape_cin, but really fixes some low-level helper functions, so this likely fixes all of the CAPE/CIN calculations.
=> BUG: Fix passing masked arrays to CAPE/CIN calcs

.codecov.yml, .coveragerc, .github/workflows/tests-conda.yml, .github/workflows/tests-pypi.yml, .travis.yml, ci/test_requirements.txt, setup.cfg, src/metpy/io/gini.py
This fixes some issues in our test coverage reporting. In recent versions of pytest, it seems the warning filter is initialized early on. This is a problem for us because that ends up importing `metpy.deprecation` before pytest-cov has a chance to set up coverage. Thus, currently, `metpy`, `metpy._version`, `metpy.xarray`, `metpy.units`, and `metpy.deprecation` aren't included in the coverage--at least any code that executes at import time. 😭 This was *really* annoying to figure out. 
Fix this by running coverage manually. As a result, we no longer need to install pytest-cov for CI--it's still fine to use locally (so long as you're not running a warning filter on the `MetpyDeprecationWarning`).
* Tweak our GitHub Actions workflows to upload coverage reports with an appropriate name to aid …
=> Fix test coverage reporting

src/metpy/calc/kinematics.py, src/metpy/calc/tools.py, src/metpy/cbook.py, src/metpy/xarray.py, tests/test_cbook.py
Removes `iterable` and `result_type` from `cbook.py` since they wrap numpy functions to support units, and now Pint has been updated to support them.
=> Cleanup cbook

docs/gempak.rst
This PR is a documentation update related to testing of GEMPAK calculations with MetPy. The Jupyter Notebooks that contain all of the comparison calculations are available at https://github.com/kgoebber/compare_metpy_to_gempak and clicking on the binder link will allow someone to run the MetPy calculations and compare them to the GEMPAK output previously generated.
There are a lot of superfluous elements on this page that aren't really calculations done by GEMPAK. Especially all of the variables given in the Parameters section. These are a list of variables that could be available in a GEMPAK surface or upperair file, so we might want to remove them. I also don't know if we want to continue to include decoders as that is not what MetPy is really seeking to reproduce at this time. …
=> MNT: Docs update GEMPAK conversion

src/metpy/io/metar.py, tests/io/test_metar.py
`parse_metar_to_dataframe` and `parse_metar_file` relied on defaulting `year`, `month` to `datetime.now` sequentially on import. Now defaults to `None` on import and sets unspecified year and/or month to simultaneous `now` on function call. Updated these to keyword-only arguments. Other than that, behaves identically to before, and not sure if we want to discuss any further default changes while already here. e.g. currently if only one of year/month is specified, this will just set the other to `now` and carry on with its business.
=> Update metar.py default year, month to keyword-only and None

src/metpy/calc/kinematics.py, tests/calc/test_kinematics.py
Make grid arguments for divergence and vorticity keyword-only in anticipation of 3D support later in 1.x series as described in #1519.
=> Make grid args for divergence and vorticity keyword-only

src/metpy/plots/declarative.py, tests/plots/test_declarative.py
Fixes some issues with the level trait in `PlotObs`, as noted in #1474:
* Make `None` the default
* Allow passing in level values that do not have units
=> Fixing handling of level in PlotObs

LICENSE, docs/conf.py
I noticed reading through the documentation (trying to figure out #1445) that the copyright only includes 2019, but there's been code written this year, so I've updated the copyright statement.
Let me know if there's some reason this shouldn't be done.
- [ n/a ] Closes #xxxx -- *Do you want me to create a ticket?*
- [ n/a ] Tests added
- [ n/a ] Fully documented
It would be simple to parametrically update this to the current year the docs are generated (perks of sphinx being configured with a Python file!). Let me know if you would rather than approach.
=> Update copyright year to include 2020

.github/workflows/docs-conda.yml, .github/workflows/tests-conda.yml
Our `scipy==1.5.0` specification for conda tests and docs workflows on Windows is no longer necessary, and retaining it alongside strict channel priority causes conda to fail to solve the environment (reproducible locally.)
=> CI: Remove Windows+conda scipy dependency adjustment

.github/workflows/docs-conda.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/tests-conda.yml, .github/workflows/tests-pypi.yml, ci/Current.txt, setup.cfg, src/metpy/plots/skewt.py
Formalize support for Python 3.9. Local testing suggests that we already work.
* Add 3.9 to testing matrix
* Add 3.9 to versions in `setup.cfg`
* A bit of cleanup (things I had hanging around)
* Fix GitHub Actions problems with `setup-miniconda` due to its use of removed functionality. Turns out that action we're using has a new canonical home, and a new version that already fixes it for us.
* Fix building PyProj (since there are not 2.6.1 wheels for Python 3.9) by bumping to Ubuntu 20.04 (which is a "preview" image 😬 ) and installing `proj-bin`
* Go ahead and bump ci traitlets to 5.0.5 (as in #1538). This is the only sane thing we can do to get the packages for conda-forge; just add a hack for Python 3.6 that goes away when we drop it
* Also bump scipy on ci to 1.5.4 (as in #1562). This …
=> Python 3.9 support

src/metpy/calc/kinematics.py, src/metpy/xarray.py, tests/calc/test_kinematics.py
Fixes passing just `DataArray` instances to `advection`.
=> Fix xarray support in advection

src/metpy/plots/cartopy_utils.py
Instead of just importing `cartopy.feature`, explicitly import the two names we need. The result is that on older Cartopy, where `Scaler` is unavailable, we fail cleanly (and not interrupting users) as if CartoPy is not installed rather than failing hard when creating our map features--which allows users with old CartoPy to still use e.g. SkewT.
No tests because there's no obvious way to do so.
=> Make CartoPy import more robust

src/metpy/xarray.py, tests/test_xarray.py
Passing keep_attrs=True to Dataset.map on xarray master is causing us to
lose needed attribute updates. Not passing it causes the tests to pass
on master and seems to work with the last release as well.
Tests added to validate other attributes are preserved.
=> BUG: Fix for xarray master

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
This fixes `wet_bulb_temperature` to no longer error out on saturated conditions. This was caused by some corner cases in moist_lapse (not handling inputs of uniform pressures due to strict > and < checks). The best fix is to use the fact that `moist_lapse` (now) supports passing in explicitly the starting pressure, separate from the desired pressure(s). Also fix `moist_lapse` to work with all scalars.
While here, refactor `wet_bulb_temperature` for performance. Use the fact that `lcl` works on grids to pull that calculation out of the loop. Improves performance by ~10% for a profile with 120 levels.
=> Fixes and improvements for wet_bulb_temperature

src/metpy/calc/indices.py, src/metpy/calc/thermo.py, src/metpy/calc/tools.py, tests/calc/test_calc_tools.py
We've fixed this before, but this case involves the paths taken when we have no heights provided. Also the culprit here is that while float32 * float -> float32 for arrays, for scalars this is float64. Apparently (See numpy/numpy#17816). The easiest workaround for now is to force it out of the scalar path.
Also remove some places where we had been working around the fact that `nanmin` and `nanmax` didn't support Quantities--this all works fine now.
=> Fix get_layer for float32 data again

.gitattributes, src/metpy/_version.py
Fixes a couple things I ran into while trying to debug on Windows the other day:
* Ensure hashes for our test data files match on Windows by enforcing line endings
* Fix version numbering so that local builds appear as such--using "dirty tag" only appends "+dirty" if files have been changed, otherwise dev builds from git look like "1.0.0rc2.post68". This can lead to pooch trying to download static data from a tag matching it rather than master.
=> Windows development fixes

.mailmap, AUTHORS.txt
Further to https://github.com/Unidata/MetPy/issues/1522, this updates the list of contributors to date. I've also added myself to this list, in anticipation of this being merged.
- [ n/a ] Tests added
- [ n/a ] Fully documented
I supposed this could be automated in the future, but I haven't dug into the CI pipeline to figure out what would be needed to make that happen.
For future reference, the base data can be pulled from Git:
```
git shortlog -s -n
```
It might make sense to add a note to `CONTRIBUTING.md` to add your name to this list, but I don't see an obvious place to do so.
Hope this is helpful!
=> Contributors List

.gitignore, setup.cfg, src/metpy/xarray.py, tutorials/xarray_tutorial.py
Overhaul the xarray with MetPy tutorial given the substantial changes in xarray support for the 1.0 release. Part of the remaining effort towards https://github.com/Unidata/MetPy/issues/1385. This makes extensive use of HTML reprs for xarray and Pint, so it is nice that we've gotten that working seemingly well with the new theme.
- ~~Closes~~
- ~~Tests added~~
=> Redo xarray with MetPy tutorial for 1.0

docs/conf.py, docs/userguide/citing.rst
Leave the regular BibTex entry, but add an AMS-specific BibTex entry
that follows their suggesttions and matches the rendered version at the
bottom.
=> Improve the citation information 

src/metpy/calc/basic.py, src/metpy/calc/cross_sections.py, src/metpy/calc/indices.py, src/metpy/calc/kinematics.py, src/metpy/calc/thermo.py, src/metpy/calc/tools.py
I have made a plethora of changes with the goal of making the calc functions look more cohesive on the MetPy Unidata website.
Some particular conflicts that need to be reviewed are:
smooth_guassian - I made a change to the equation EXP[-D^2], it looks funky on the website so I modified the code. I may be wrong so I want to double check that I did it correctly or it could have been right in the first place, not sure.
gradient_richardson_number - this function is included in my fork but is not on the MetPy page, so I am not sure if it is supposed to be there or not. 
friction_velocity - this function is on the MetPy page but I am unable to find it on my forked version
relative_humidity_wet_psychrometric - I changed the 'relative humidity' wording to RH because it looked funky, once again I …
=> Edits to MetPy; adding capitals, making website look more cohessive

ci/linting_requirements.txt, setup.cfg, src/metpy/calc/basic.py, src/metpy/calc/thermo.py, src/metpy/io/_tools.py, src/metpy/io/nexrad.py, src/metpy/plots/declarative.py, src/metpy/xarray.py, tests/io/test_gini.py, tests/plots/test_cartopy_utils.py
This adds flake8-simplify to our suite of linting plugins. This catches various miscellaneous things, like those I'm fixing here:
* Use `contextlib.suppress` to ignore a certain exception
* Yoda conditions (e.g. `if 3 == b:`)
* Using `enumerate` instead of incrementing a separate counter in a loop
* Using `all`/`any`
* And many others
=> Enable flake8 simplify

setup.cfg, src/metpy/calc/basic.py, src/metpy/calc/cross_sections.py, src/metpy/calc/indices.py, src/metpy/calc/kinematics.py, src/metpy/calc/thermo.py, src/metpy/calc/tools.py, src/metpy/units.py, tests/calc/test_thermo.py
Augment the `check_units` decorator to detect errors from functions that have changed and add that information to the error message.
=> Handle changed functions in check_units decorator

src/metpy/calc/indices.py, src/metpy/xarray.py, tests/calc/test_indices.py, tests/calc/test_thermo.py
A couple of fixes for functions with `DataArray` input
* Fixes `precipitable_water`--just an oops in how it was decorated
* Fixes `isentropic_interpolation`. `preprocess_and_wrap` was not handling parameters coming in as `*args`--with a bit of refactoring, now it does.
=> DataArray Fixes

src/metpy/calc/indices.py, tests/calc/test_indices.py
This PR is a fix to the bug reported in issue #1635. The issue revolved around the use of a temperature variable in generating a weighted mean value. The fact that the `np.trapz` function now accepts unit arrays this fix simply allows the units to pass through the function and yield proper units at the end instead of stripping and reapplying units.
A test has been added to account for using temperatures to compute a mean weighted value. The input is in Celsius with the output in Kelvin.
The only question, which I raised in a comment on the issue, is whether we desire to have the output come back this way, or force it back to the input units. The current behavior in this PR is similar to that of the `parcel_profile` function.
=> fix bug in issue 1635

src/metpy/xarray.py, tests/test_xarray.py
As reported on StackOverflow and in https://github.com/Unidata/MetPy/issues/1648, it is incorrect to fallback to a lat/lon CRS when a CF grid mapping is missing and 2D lat/lons are present (as this means we instead have data on a projected grid of unknown CRS and not data on a lat/lon grid). This PR changes the lat/lon fallback to only occur when the identified latitude coordinate is also considered a y coordinate and likewise longitude is considered x (so that we truly have a lat/lon grid represented).
This did require some additional tweaks to the `grid_deltas_from_dataarray` utility, which assumed that a `metpy_crs` was always present (which never was really the case, but is especially important to not assume now since we no longer [mistakenly] inject a lat/lon CRS in the 2D lat/lon …
=> Remove misleading fallback to lat/lon CRS when only 2D lat/lon present

examples/meteogram_metpy.py
Observed an error emitted with development matplotlib 3.4.0
```
File "/home/runner/work/MetPy/MetPy/examples/meteogram_metpy.py", line 213, in <module>
meteogram.plot_winds(data['wind_speed'], data['wind_direction'], data['wind_speed_max'])
File "/home/runner/work/MetPy/MetPy/examples/meteogram_metpy.py", line 82, in plot_winds
ax7.set_yticks(np.arange(45, 405, 90), ['NE', 'SE', 'SW', 'NW'])
File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 73, in wrapper
return get_method(self)(*args, **kwargs)
TypeError: set_ticks() takes 2 positional arguments but 3 were given
```
Just updated the example to use the more common `set_yticklabels` API
=> use set_yticklabels in examples/meteogram_metpy

src/metpy/calc/tools.py, src/metpy/io/nexrad.py, tests/calc/test_calc_tools.py
Updates MetPy code to not use the now deprecated numpy.{bool,int,float} aliases of builtin python types.
- Tests added
- Fully documented
=> address numpy 1.20 deprecation of np.{bool,int,float}

src/metpy/calc/indices.py, tests/calc/test_indices.py
As I mentioned in issue #1361, the bunkers storm motion was using a pressure weighted mean wind for its calculations, making the output incorrect. I removed the concatenate(mean_pressure_weighted()) function calls and replaced them with the get_layer function and a simple numpy mean in the line below. I used the output to modify the testing function. I was originally going to use the values from sharppy with a larger range of error, however, after a decent amount of testing, I found out they use the 0-6 shear instead of the (0-500m mean wind) - (5500-6000m mean wind) shear.
=> Non-pressure weighted bunkers storm motion

.github/workflows/draft-release.yml
Fixes the URLs to the PRs/issues in genereated release notes. We were mistakenly using an API url instead before.
=> Use HTML API for release note links

src/metpy/xarray.py, tests/test_xarray.py
- Removes `check_axis` check in no gridmapping fallback in `parse_cf` (unnecessary via #1651)
- Points `.metpy.units` to `xarray.Variable._data` instead of `.data` in checking for quantity with units to avoid loading data into memory
- Test to see if `.metpy.units` touches `.data`. If there are any thoughts on more thorough tests for this situation let me know
- Not sure if we want to leave open for larger discussion
=> Fix `.metpy.units` checking `.data` for units and loading data into memory

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
This required fixing lcl and moist_lapse to work with nans, or at least
work better.
=> Fix wet_bulb_temperature with nans

.github/workflows/doc-versions.yml
On any push to the `gh-pages`, this runs a Python script that looks at all the available `v[0-9]*` directories and sets the latest link to the highest one, and keeps in the listing the most recent 4.
The only way this workflow is able to run triggered by pushes to the `gh-pages` branch is by being present on the `gh-pages` branch, which is why this is going there. I (with @dcamron) considered instead triggering on `page_build` events in order to keep this with the rest of the MetPy GHA workflows on `main`, but:
* This wouldn't allow us to skip running on updates to the dev documentation
* `page_build` isn't really the right action to be triggering this, it's only a consequence of the push, which is what we want
=> CI: Add workflow for managing version listing

.github/workflows/docs.yml, .github/workflows/draft-release.yml, .github/workflows/linting.yml, .github/workflows/release.yml, docs/devel/infrastructureguide.rst, setup.cfg, src/metpy/calc/thermo.py
Started out to fix the handling of docs on release, but has a few other things:
* Only deploy docs from Python 3.9 build
* Make sure we deploy docs explicitly when a release is made (to take `main` and put in a versioned directory)
* Tweak draft release announcement to set that we want to [automatically create a discussion item](https://github.blog/changelog/2021-04-06-releases-support-comments-and-reactions-with-discussion-linking/) for the release
* Sets our release action to use the PyPI environment, which is the only environment now that has access to our PyPI upload token
* Tweak linting workflow to make sure a failure by `flake8` fails the workflow
* Fix a problem with formula rendering in a couple docstrings
* Update the infrastructure guide for the workflow added to `gh-pages` in …
=> Misc release items

src/metpy/io/station_data.py
Presently, the import of `metpy.io.station_data` causes four station tables to always be loaded, which cascades into making POOCH requests if necessary.  This change makes the loading of station table data lazy and only when necessary to fulfill a lookup request.  No functional change.
- Tests added
=> lazy load station_info only when used #1320

.github/workflows/docs.yml, .github/workflows/nightly-builds.yml
This addresses part of #1843 by moving pre-release testing and doc builds to a nightly CI job. It removes that portion of the testing from the regular PR matrix, and adds a nightly workflow. This workflow runs on a schedule, does the runs, and if they fail should open an issue, making sure to re-use an existing open issue if one exists.
For obvious reasons, this is going to need some testing once merged. Success here only means that the we're no longer running in the CI for the pull request, but haven't broken the rest of the workflow.
For testing I've got this set to run every 10 minutes (so only click merge if I'm available to observe it). Once I'm convinced it's working properly, it's ready to go to run overnight (3am MDT).
=> Move pre-release tests and docs builds out of PR CI

src/metpy/calc/basic.py
Was changed in c7b0b9b to remove multiplication by units and slightly change the operations used--this runs afoul of upstream changes in Pint where a Quantity is passed as the data in a constructor. Instead, change the units on a constant to produce the required dimensionality properly.
=> BUG: Fix unit-handling in heat_index (Fixes #1867)

src/metpy/io/_tools.py, src/metpy/io/nexrad.py
It turns out that `+=` for `bytearray` is implemented efficiently (unlike strings)--originally this was even faster than `extend()` (See [this video](https://youtu.be/z9Hmys8ojno?t=2325). Also update one last use of `Struct()` to unpack a single integer.
I was kinda hoping this might get some minor performance gain, but alas, no such luck. The code is still better this way, though.
=> Minor simplifications for the IO code

src/metpy/plots/declarative.py, tests/plots/test_declarative.py
Adds a `.copy()` method to just about every class in `declarative.py`. This includes `Plots2D` (and hence all of its subclasses), `MapPanel`, `PanelContainer`, and `PlotObs`. The only class excluded is `Panel`, since it is currently empty.
This `obj.copy()` is equivalent to using `import copy` and `copy.copy(obj)`, expect when `obj` is a MapPanel.
The `.copy()` method for MapPanel required some additional changes in order to get it working. @dopplershift and I found that we needed to set `allow_none=True` for the `parent` trait of `MapPanel` in order to accommodate the process of copying a MapPanel that may not have been assigned a parent yet. A `__copy__()` method was written explicitly for MapPanel since a deeper copy of MapPanel's `plots` trait is needed in order for the copy to work …
=> Copy method for declarative interface

examples/plots/Station_Plot.py, examples/plots/Station_Plot_with_Layout.py, src/metpy/io/metar.py, src/metpy/plots/station_plot.py, tests/plots/test_station_plot.py, tutorials/declarative_tutorial.py
This PR is set to address issue #1758 where we do already distribute the weather codes via the metar_parse_file function. This issue is a bug that resides between the documentation, which states a different name, and the variable name generated in the function. This PR chooses to go with the naming convention of the documentation, which is more appropriate for what the those values actually are. In METAR, there is not a present and past configuration to the weather being reported. It is all current wx as there can be multiple phenomenon happening at one time.
There would still need to be some work on the documentation end for how the notes of the function display on the MetPy webpage. The current format is nearly unreadable.
https://unidata.github.io/MetPy/latest/api/generated/metpy.io.par …
=> fixes bug in issue 1758

ci/doc_requirements.txt
We could roll this up into a larger PR of small docs changes, but we can also just kick this in and close #1797. sphinx-gallery has better specified its dependencies and so we no longer have to handle this pillow dependency in `docs_requirements` ourselves.
=> Drop our explicit pillow dependency for sphinx-gallery

src/metpy/io/metar.py, tests/io/test_metar.py
After further review of #1918 with @dopplershift, we determined that Pint quantities were being used in `eastward_wind` and `northward_wind` columns of dataframes coming out of the METAR parser functions, and this was causing problems down the road when it came to plotting wind barbs. In this PR, we change how `eastward_wind` and `northward_wind` are created so that they are floats instead of Pint objects. This should solve the original issue #1916 related to the nightly build failing.
This PR also adds a new test that makes sure that none of the columns in the dataframes created by METAR parsers contain Pint quantities.
=> Remove any Pint objects from METAR parser output

src/metpy/calc/tools.py, src/metpy/plots/skewt.py
Found 5 places in MetPy where we use `.dimensionality ==` to check the dimensionality of a quantity. Pint offers `.check()` to accomplish the same task, which we first used in #1912, and @dopplershift suggested we replace `.dimensionality ==` to `.check()` across the project where possible.
=> Refactor dimensionality comparisons to check()

conftest.py, src/metpy/calc/__init__.py, src/metpy/interpolate/__init__.py, src/metpy/io/__init__.py, src/metpy/package_tools.py, src/metpy/plots/__init__.py, tests/test_packaging.py
Fixes #968. Resets the `__module__` on our exported functions so that they appear from the proper namespace when printed in IPython/Jupyter notebook. Also fixes a couple places where we were incorrectly putting the objects themselves, rather than their names, into `__all__`. (Found because those cases break this new code.)
=> Set __module__ for exported functions.

src/metpy/calc/indices.py, tests/calc/test_indices.py
In issue #1549, `precipitable_water()` raises an error because the pressure passed to `top` is outside the bounds of the pressure and dewpoint profiles, only because missing values have been removed. This PR provides more descriptive error messages, which could save some time for users who run into the same issue in the future.
=> More descriptive errors for precipitable_water

src/metpy/io/metar.py, src/metpy/plots/__init__.py, src/metpy/plots/cartopy_utils.py, tests/plots/test_cartopy_utils.py
* Reduce import load of `metpy.io.metar`. This is currently causing importing `metpy.io` to trigger imports of `metpy.calc` and `metpy.plots`, which can add almost half a second to the total import and currently triggers warnings when Cartopy isn't installed
* Move handling of our Cartopy map features to only warn (when Cartopy isn't installed) upon *access* of the relevant attributes. This uses the module-level `__getattr__()` we have available now that we're only supporting Python >=3.7.
=> Improve some import handling

src/metpy/calc/tools.py, tests/calc/test_calc_tools.py
It appears we were removing the units and only using the magnitude of `bound`, `height`, and `pressure` when interpolating pressure at a given height in `_get_bound_pressure_height()`, which is used in `get_layer()`. Therefore, when the height profile and bottom/top bound were in different units, the function failed miserably. Keeping those units in place resolves the issue.
=> Units bug fix for _get_bound_pressure_height

conftest.py, docs/conf.py, setup.cfg, src/metpy/io/metar.py, src/metpy/io/nexrad.py, src/metpy/plots/cartopy_utils.py, src/metpy/testing.py, tests/interpolate/test_grid.py, tests/interpolate/test_points.py, tests/io/test_nexrad.py, tests/plots/test_cartopy_utils.py, tests/plots/test_declarative.py, tests/plots/test_mapping.py, tests/plots/test_mpl.py, tests/plots/test_skewt.py, tests/plots/test_station_plot.py, tests/plots/test_util.py, tests/units/test_units.py
Fixing up some style issues from CodeQL, including one real bug (in code for a NEXRAD product that likely no one uses).
* Clean up some imports
* Put `set_agg_backend` with the rest of the fixtures in `conftest.py` and only use on the one test that requires it (`test_show` in `test_declarative.py`, because otherwise it opens a window).
* Enable a commented-out test in `test_mapping.py`--this was waiting on CartoPy>0.16 (0.17 came out November 2018). This is why, boys and girls, you don't comment things out but use `skips` and stuff.
* Clean up some spots where file objects weren't being explicitly closed
=> Cleaning up analysis warnings

src/metpy/plots/mapping.py, tests/plots/test_mapping.py
Currently, pyproj CF output is not accepted by metpy.assign_crs(). The relevant logic in in /metpy/plot/mapping.py, property cartopy_globe. The error is occuring because the conversion from PyProj to CF produces a value of 0 for inverse_flattening. 
This PR updates mapping.py to not pass on a value of 0 for inverse_flattening by interpreting it as a spherical datum. Currently, it passes all tests except for test_globe_spheroid() in test_mapping.py.
=> Interpret inverse_flattening = 0 as spherical datum in mapping.py

src/metpy/calc/cross_sections.py, tests/calc/test_cross_sections.py
- Implements @jthielen's solution to issue #1948, which converts `u` and `v` to m/s before passing to `normal_component()`.
- Refactors one line of `absolute_momentum()`, but I'm not familiar with the absolute momentum calculation. I'm willing to include more refactoring in this PR, but I would need some more specific direction on what to adjust/remove.
=> Absolute momentum units bug fix

CONTRIBUTING.md
`CONTRIBUTING.md` had some room to catch up on our environment specification process to be more in-line with how we have it set up for CI and to more fully encompass what a user's development environment setup might look like (and preempt some potential headaches.)
=> Clarify environment installation steps in CONTRIBUTING

src/metpy/plots/declarative.py, tests/plots/test_declarative.py
Okay, so try number 2 to get the reorganization, started by @jthielen to allow for a more flexible syntax to add other types of plots  (e.g., SkewT, Hovmoller, Line Plots, etc.). This is largely based on the reorganization that @jthielen produced and supplied in the discussion about changes to the declarative syntax.
In future PRs we'll work to add these new plotting abilities, which may then require further, albeit hopefully smaller changes, to the structure to allow for maximum functionality.
=> Reorganization of declarative syntax

src/metpy/calc/tools.py, tests/calc/test_calc_tools.py
This PR resolves #1970 by adding some unit handling and issue a warning if ranges and/or azimuths are supplied without units to alert the user to the assumed behavior. Test slightly updated to account for different use cases of units or no units attached to arrays.
=> Add unit-awareness to azimuth_range_to_lat_lon function

src/metpy/calc/basic.py
Decorates `geopotential_to_height` with `@check_units` to provide appropriate error on non-united input, thanks #1998!
- ~[ ] Tests added~ (bugfix, tests pass locally)
=> Add check_units to `geopotential_to_height`

src/metpy/calc/__init__.py, src/metpy/calc/exceptions.py, src/metpy/calc/thermo.py, tests/calc/test_thermo.py, tutorials/xarray_tutorial.py
This commit addresses #1339 using ideas from #1654.  A new exception
is added on the theory that parcel calculations are complicated, so
there may be other problems with input soundings (extreme
supersaturation?) that might want to be flagged in the future.
-------
See commit message above.
=> Check that pressure decreases monotonically in parcel calculations

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
This was incorrectly lifting a surface parcel to the LCL calculated from the 850 point. Instead, eliminate all of the manual calculation and just use parcel_profile. The new values are with 1% of those from Wyoming--which is now what's used in the test (the original test value was off by 50% of the new value). Also fix the function parameter name (`dewpt` -> `dewpoint`) and clean up a bit of the docstring.
=> Fix up Showalter Index calculation

src/metpy/calc/tools.py, tests/calc/test_calc_tools.py
This makes `reduce_point_density` much easier to use with real data when we do not have station information. This also works around a crash with SciPy 1.7.1--and it's unclear if it actually worked correctly before. This is why I have elected *not* to hide this behind a flag.
=> ENH: Ignore bad points in reduce_point_density

.codespellignore, src/metpy/io/gempak.py, tests/io/test_gempak.py
#1656 came before we had these checks in place.
=> Clean up some lint in the GEMPAK reader

.github/workflows/docs.yml
Saw two doc builds for 1.1--one of which fails because they're running concurrently. Need to specify one of published or released, since published fires for both released and prereleased.
=> CI: Fix duplicate doc builds on release

.github/workflows/docs.yml
Jobs authed with GITHUB_TOKEN will not kick off
other jobs triggered on push. Switch docs deploy
to an environment SSH key so that doc-version.yml
should work on release.
=> Change from GITHUB_TOKEN to secret SSH key in docs deploy

src/metpy/io/gempak.py
Found by GitHub code analysis. Rather than not store the return, for symmetry with the rest of the uses in the function save the value to `_`. This value is not used by any subsequent calls.
=> Denote unused return value as such

src/metpy/calc/thermo.py, src/metpy/io/_tools.py
* Replace unnecessary dict comprehension (grabbed from #1785). Closes out #1933.
* Remove "flux" from the `gradient_richardson_number` docstring since based on some reading ([AMS Glossary](https://glossary.ametsoc.org/wiki/Flux_richardson_number) among them) it seems like flux Richardson number is different and relies on the prototypical boundary layer perturbations rather than gradients.
* 
=> Misc cleanups

ci/test_requirements.txt, conftest.py, setup.cfg, src/metpy/calc/basic.py, src/metpy/testing.py, tests/calc/test_basic.py
This PR adds a fixture, `array_type`, that provides array types for tests. The fixture is used in test functions where appropriate (I think I covered all test cases without extending the length of time to run the test suite). `dask` was added as a test requirement (version is arbitrary).
Two bugs were discovered and fixed:
- When `wind_direction()` was given masked arrays that contained calm values (u=0, v=0), the boolean indexing of the array to find these values and assignment caused masked wind speeds to become unmasked.
- `smooth_gaussian()` returned a `numpy.ndarray` when given a `numpy.ma.array` as input.
The following functions are xfailed for dask arrays:
- `wind_direction()`: the boolean mask used to index values needs to be the same size as the array it is indexing, which is a …
=> Add a fixture that provides numpy, masked, and dask array functions

src/metpy/calc/thermo.py, src/metpy/xarray.py, tests/test_xarray.py
Implements the argument name check suggested in #2069, and fixes the spelling error in the decorator on `dewpoint_from_specific_humidity`.
I'm marking this as closing #2069, but if the intent for #2069 was broader than just this particular function's issue, then I'll edit that out. Also, not sure where to log the suggestion to "audit" all the decorator usage for broadcasting order and the like.
=> Add argument name check in preprocess_and_wrap, and fix dewpoint_from_specific_humidity

.github/workflows/nightly-builds.yml
This should allow the linkchecker to fail a nightly build and have the `output.txt` file appear in the log in the issue. This also fixes a bug in the workflow where the doc log wasn't being found due to a path issue.
This hits another item in #1843 to reduce CI flakiness. We can then completely remove the linkchecker from PRs (and rely on the CI nightly check), or possibly check any failures in a PR against the git changes. We need to do something because I'm tired of PRs hanging up on this kind of stuff.
=> Add linkchecker to nightly CI run

docs/userguide/gempak.rst
Closes #2080.
Apparently at some point the `api` directory moved from being a
subdirectory of the `userguide` directory to a sibling directory.  In
addition, a few links had a duplicated `generated` directory.
I didn't test every single link, but the ones I did try all work with
these changes.
=> Fix broken links in GEMPAK Comparison Guide

src/metpy/calc/thermo.py
This commit relaxes the monotonicity check that had been performed, as
real data has a tendency to repeat pressures, especially in the stratosphere.
Closes #2077
=> Allow adjacent points in sounding to have the same pressure

src/metpy/io/_metar_parser/metar_parser.peg, src/metpy/io/_metar_parser/metar_parser.py, src/metpy/io/metar.py, tests/io/test_metar.py
Adds wind gusts, which were already part of the grammar to the parsed output. Had to slightly tweak the grammar so that gust became a labelled node in the tree. Otherwise, it was just a matter of wiring it up to end up in the output. As requested in #2074.
=> Add wind gusts to parsed METAR output

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
Fix lifted_index function error when data at 500 hpa is missing by change np.where to interpolate_1d.
- [ X ] Tests added (Re-test already)
- [ X ] Fully documented (Only edit in comment code part)
=> Fix lifted_index cannot calculate when data at 500 hpa is missing

src/metpy/calc/basic.py, tests/calc/test_basic.py
This PR fixes bugs discovered in #1935 related to passing dask arrays as arguments to `wind_direction`, `heat_index`, and `apparent_temperature`. `dask` needs to know the resulting dimensions of the indexed array when performing item assignment, so boolean indexes are converted to ndarray to solve this.
With this PR, it seems safe to say that the basic module now supports dask arrays. Should this be included in the documentation, or do we want to wait until most of the calc module has support for dask arrays?
=> Convert instances of boolean indexing to ndarrays to pass dask tests in basic module

src/metpy/interpolate/grid.py, src/metpy/interpolate/points.py
Default search radius is 5 times the average spacing, not the averagespacing itself.
Also went ahead and capitalized Barnes/Cressman as appropriate.
=> Correct docs for search_radius in interpolate functions

.github/workflows/docs.yml
Docs `Deploy` workflow had a mismatch in artifact download location with expected deploy directory. Download the artifact to the expected subdirectory to get the dev docs back.
=> Fix `dev` docs deploy

.github/ISSUE_TEMPLATE/bug_report.yml
Per a mention at last week's dev call, add a dedicated field for errors and tracebacks to our bug report issue template. I've included an example traceback in the placeholder.
=> Add field for traceback to bug report template

.github/workflows/tests-conda.yml
See if MetPy can be tested with python 3.10 on conda now.
-  Tests added
- Fully documented
=> run conda tests on python 3.10

src/metpy/interpolate/grid.py
A [recent StackOverflow question](https://stackoverflow.com/questions/70077232/grid-x-and-grid-y-dimension-in-natural-neighbour-to-grid) pointed out some errors in the array shapes given in the docstring for `natural_neighbor_to_grid`. This PR is a quick correction to those.
- ~~Closes #xxxx~~
- ~~Tests added~~
- ~~Fully documented~~ (doc clean-up only)
=> Correct array shape typos in natural_neighbor_to_grid

.codecov.yml, .github/actions/build-docs/action.yml, .github/actions/install-conda/action.yml, .github/actions/install-pypi/action.yml, .github/actions/run-tests/action.yml, .github/actions/setup-proj/action.yml, .github/workflows/code-analysis.yml, .github/workflows/docs-conda.yml, .github/workflows/docs.yml, .github/workflows/linting.yml, .github/workflows/nightly-builds.yml, .github/workflows/release.yml, .github/workflows/tests-conda.yml, .github/workflows/tests-pypi.yml, ci/filter_links.py
1. Fix linkchecker for nightly builds
We were always filtering based on the (assumed) current merge. Instead, just pass true/false based on whether the build is a PR, and find the appropriate commits within the script.
2. Update action version numbers
Replace explicit versions for actions with only major where possible. This will hopefully reduce dependabot churn (assuming it supports this--[unclear](https://github.com/dependabot/dependabot-core/issues/2304) but has seemed to be working for us), and also compensates for the fact that dependabot is not issuing updates for actions versions within our own composite actions. This also updates the `install-pypi` action to use a version of `setup-python` that supports caching.
3. Add `concurrency` setting which uses concurrency groups to cancel …
=> Updates for CI pipeline

.github/actions/build-docs/action.yml, .github/actions/run-tests/action.yml, .github/workflows/linting.yml, .github/workflows/nightly-builds.yml
Nightly is currently failing (and not reporting) because it can't find the logs for the doc build. Fix that and:
* Vastly simplify logic by just using `failure()` as the condition rather than the poorly named and manually managed `log_available` output (logs are always available)
* Ensure that the Report job always succeeds by ensuring even an empty log is available (and the step succeeds)
Also simplify a bit of syntax around `always()` and `failure()`.
The real test of this PR is in running the nightly workflow, but since this changes the `run_test` and `build_docs` actions, thought best to at least sanity check those in a PR.
=> Fixes for nightly CI run

CONTRIBUTING.md, docs/api/references.rst, docs/conf.py, examples/gridding/Point_Interpolation.py
Fix some redirecting links:
* Open source contributing guide was redirecting to GitHub's generic help--found correct link
* Instead of linking to the natural neighbor interpolation report that was uploaded to a MetPy issue, there's now a link on the Colorado School of Mines page. There's also a copy up on researchgate. This eliminates an ugly redirect
* Update allowed redirect patterns for the other URLs. This includes a blanket redirect for doi.org to go to any https site. I'm not sure what would be a better allow.
* Clean up ordering of our ignore list to group things a bit better
=> Fix linkchecker build

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
The indexing math wasn't quite correct if the reference index was 0 (0 - 1 = -1 is very different from 0). Fortunately, it works just to always use the right side index from searchsorted. Added some more exhaustive testing to validate this.
=> BUG: Fix handling of reference level for moist_lapse (Fixes #2128)

src/metpy/xarray.py
CF Conventions allow you to omit a grid_mapping when data are natively on lat/lon coordinates. Therefore we should not be warning users about our assumption of a lat/lon coordinate system. Just decrease to a debug message (in case we need it for debugging).
=> Reduce warning to a debug log message

tests/plots/test_skewt.py
Really should just be using `warnings.catch_warnings` for this case. Per pytest-dev/pytest#9002.
=> Replace pytest.warns(None)

src/metpy/io/_metar_parser/metar_parser.py, src/metpy/io/metar.py, tests/io/test_metar.py
Sometimes the METAR parser chokes, but it isn't so easy to see what it
is doing under the hood.  This PR implements the `__repr__` special
method to the `TreeNode` class (and those classes which inherit from it)
to make debugging easier.
No test has been added; please let me know if this is desired.
```python
from metpy.io._metar_parser.metar_parser import parse
str1 = 'METAR ORER 172000Z 30006KT 0400 FG VV// 12/12 Q1013 NOSIG='
tree = parse(str1)
print(repr(tree))
```
Output w/o PR:
```
<metpy.io._metar_parser.metar_parser.TreeNode1 object at 0x7f2a24e92bb0>
```
Output w/ PR:
```
TreeNode1(text='METAR ORER 172000Z 30006KT 0400 FG VV// 12/12 Q1013 NOSIG=', offset=0, metar=TreeNode(text='METAR', offset=0), siteid=TreeNode(text=' ORER', offset=5), datetime=TreeNode2(text=' 172000Z', …
```
=> Add `__repr__` to TreeNode objects

src/metpy/plots/declarative.py, tutorials/declarative_tutorial.py
Fixes #2136
This is essentially a copy/paste of the docstring into the tutorial
document.
Unable to test due to errors below, but this is trivial so hopefully
it works!
```
preparing documents... WARNING: unsupported theme option 'navbar_start' given
WARNING: unsupported theme option 'navbar_center' given
WARNING: unsupported theme option 'navbar_end' given
done
writing output... [  0%] api/generated/metpy.calc
Theme error:
An error happened in rendering the page api/generated/metpy.calc.
Reason: TemplateNotFound('versions')
```
=> Add description of `scale` to declarative tutorial

docs/conf.py
Allows MetPy versions in the form of x.y to not trip up version parsing in `docs/conf.py`
- ~~Tests added~~
=> support versions like x.y in docs/conf.py

src/metpy/plots/declarative.py, tests/plots/test_declarative.py
This PR addresses a portion of #2016
Right now, typos in the names of attributes used by the declarative
plotting interface lead to strange errors that can be difficult to
debug.  Here, a new mixin class is defined to provide
validation of attribute names against a whitelist.
This approach was inspired by a [Stack Overflow question](https://stackoverflow.com/questions/20406363/setattr-versus-slots-for-constraining-attribute-creation-in-python/20406443#20406443)
and the nearest-string function was stolen from Rosetta Code.
~~Since this is a proof of concept, validation is only applied to the
MapPanel object.~~
Validation is extended to all publicly facing objects in the decalarative interface, and a test has been added.
Here is a motivating example:
```python
from datetime import datetime, …
```
=> Validate declarative interface attributes

src/metpy/interpolate/points.py, tests/interpolate/test_grid.py, tests/interpolate/test_points.py
Add support for units throughout the inverse distance weighting and natural neighbor interpolation code. Also ensure that `interpolate_to_grid` returns values with the same units as input for all methods.
=> Unit support for interpolation functions

setup.cfg, src/metpy/calc/thermo.py, src/metpy/constants/__init__.py, src/metpy/constants/default.py, src/metpy/constants/nounit.py, src/metpy/io/gempak.py, src/metpy/units.py, src/metpy/xarray.py
I noticed that there have been two major performance bottlenecks caused by the existing approaches to unit handling: iteration in `moist_lapse`/`lcl` (#1169) and looping of `thickness_hydrostatic` in `io.gempak`'s `_interp_*` functions (#2062). In an attempt to improve this situation, this PR takes the approach of refactoring the relevant thermo calculations to have private versions that only use base units (no `pint.Quantity` handling), and wrapping those while handling units. No robust benchmarks were evaluated, but this did speed up `pytest tests/calc/test_thermo.py` on my workstation from about 3.5 seconds to 0.69 seconds (similar to #1980), and @akrherz's test file in https://github.com/Unidata/MetPy/issues/2041#issuecomment-904920081 from 35.88 seconds to 1.78 seconds.
I tried to be …
=> Improve some thermo calculation bottlenecks by refactoring how units are handled

.github/actions/build-docs/action.yml, .github/workflows/docs.yml, .github/workflows/nightly-builds.yml
A collection of various GitHub action workflow fixes that were surfaced by the recent release:
* Don't run the nightly builds on new tags
* Don't build docs on both release and tags--just use tags since we're already restricting those to the proper version
* Fix doc version for upload directory. Some `-` vs. `_` typos kept that from flowing through correctly
* Fix version in built docs. The built docs were detecting a dev build because the version came back as "dirty" because we were modifying one of the requirements files.
=> GHA Workflow fixes from release

src/metpy/cbook.py
This allows us (when using the latest pooch) to disable updates to downloaded data. This means our current minimum build (using 0.1) won't fail when someone updates data without the registry, but the other jobs should so that's fine.
This cleans up the hack that was added in #2283 and replaces it with the newly added argument for Pooch.
=> Use new allow_updates arg for pooch

src/metpy/xarray.py, tests/test_xarray.py
When using `MetPyDataSetAccessor.quantify`, I noticed the global attributes being deleted. This didn't seem 
I added the `keep_attrs = True` argument to the `.map` operation in `MetPyDataSetAccessor.quantify` as I don't see any reason why the global attributes of a dataset should be deleted upon quantification.
Closing #2311
=> Retaining global attrs on MetPyDatasetAccessor.quantify()

setup.cfg
This keeps within our support window and avoids building scipy and pandas from source on our 3.8 minimum job. Right now the 3.8 Minimum CI job is taking ~40 minutes (~32 minutes just installing) because of this.
=> Bump scipy and pandas minimum versions

.codespellignore, src/metpy/xarray.py, tests/test_xarray.py
Over the course of working on https://github.com/ncar-xdev/xwrf/pull/14 and recieving feedback on it, bugs arose in some edge cases of the regex coordinate criteria, particularly, `XTIME` got interpretted as an `x` axis coordinate (which is very much not right). To resolve this, I tightened the criteria with start and end matching, and then filled in what I'd otherwise expect to be allowed in between. WRF/xwrf-motivated test dimension names have also been added.
- ~~Closes~~
=> Update coord criteria regex so that X prefixes or _ infixes don't break it

src/metpy/units.py, tests/units/test_units.py
MetPy's CF/UDUNITS-style power handling regex failed on parentheses (as noted in https://github.com/Unidata/MetPy/issues/1362#issuecomment-863476636 ~~and https://github.com/Unidata/MetPy/issues/1362#issuecomment-1051310199~~ ). This fixes it and adds tests against those previously failing examples!
- ~~Closes~~
=> Fix unit power regex for parentheses handling

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
As identified via [this StackOverflow question](https://stackoverflow.com/questions/71655087/metpy-wet-bulb-temperature-function-returns-error-when-output-of-most-unstable-p), `wet_bulb_temperature` currently fails on (Quantity-wrapped) NumPy scalars since they *do* have a `shape` attribute (albeit empty), but are not "at least 1D" or indexable, which ends up in an `IndexError`. Changing
```python
if not hasattr(pressure, 'shape'):
```
to
```python
if not getattr(pressure, 'shape', False):
```
resolves this. So, this is the change that is implemented and tested here! 
- ~~Closes #xxxx~~
=> Fix wet_bulb_temperature for NumPy scalars

src/metpy/io/__init__.py, src/metpy/io/station_data.py, tests/io/test_station_data.py
This allows iteration, membership, etc. directly on the station information rather than needing to use the `tables` property. The abstract base class gives us some things like `get()`, `keys()`, and `values()` for free.
=> Make StationLookup a proper Mapping

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
For values not handled by the existing is-close-to-reference-pressure massaging in `moist_lapse`, this will make `solve_ivp` happy in line with some suggestions and discussion in #2309. Thoughts on the warning messaging are welcome.
~My remaining question for behavior: do we reinsert duplicate values into the profile to match the original pressure dimensions? @ktyle @kgoebber if you have quick thoughts, let me know!~
Will return temperatures at each specified pressure, including original duplicates.
=> Drop repeat pressures in moist region of `parcel_profile`

.github/actions/install-pypi/action.yml, .github/workflows/docs.yml, .github/workflows/nightly-builds.yml, .github/workflows/tests-pypi.yml
Since cartopy is the only "extra" we have right now, just key an install of extra_requirements.txt. This allows us to remove the hacky cat-ing of requirements files, which was triggering the version in the built docs to become "1.xdev".
Hopefully with this and 513bdd07 our next release will finally have everything work automatically.
=> Make install-pypi action handle extra requirements

examples/isentropic_example.py
When working on some examples and looking through the ones we currently have, I noticed that there were no contours on the Montgomery Streamfunction example. Needed to convert to base units in order for the desired output to plot. This PR makes a small change to ensure the data are in base units and then scaled accordingly.
=> fix isentropic example

src/metpy/xarray.py, tests/test_xarray.py, tutorials/xarray_tutorial.py
This PR adds to the metpy xarray accessor to have a `convert_to_base_units()` function, which will allow for the simplification of complex units following calculations using quantify xarray DataArrays.
Added a test and a simple example to the xarray tutorial.
=> add accessor convert to base units

ci/filter_links.py, docs/conf.py
Work-around GitHub docs failing linkchecker. For some reason the GitHub docs site is giving a 403 for things like cURL and the Sphinx linkchecker. Give it a "real" user agent to get around this for now.
Also tweak our linkcheck handler script for CI to give better output. In this case, "code" was 0, so might as well just use "info" instead.
=> Fix linkcheck

src/metpy/io/nexrad.py, tests/io/test_nexrad.py
One of the threshold blocks had a value of 65535, which got interpreted as -1--thus breaking our construction of the lookup table.
=> Fix value mapper for NEXRAD DPR product

tests/io/test_nexrad.py
This fixes missing the file Level3_FTG_N0B_20220304_1820.nids in any of the tests. None of the tests were functionally different, so just run all of the NIDS files through the main level3 test.
=> TEST: Collapse the NIDS tests together

src/metpy/plots/declarative.py, tests/plots/test_declarative.py
This PR adds a new attribute to the declarative syntax to indicate the plotting of an RGB image through a boolean setting. This preserves the check for 2D for all data, adds new check for if `rgb_image` is set to `True` and check to ensure it is 3D.
Open to suggestions on naming and description of attribute.
=> adds RGB image ability to declarative

ci/extra_requirements.txt, ci/linting_requirements.txt, setup.cfg
This helps catch times we don't have libraries properly declared in `setup.cfg`--it's not configured currently to checkout files in `ci/` since you can't do both.
This caught us missing an explicit dependency on Shapely (we were getting it transitively through Cartopy) as well as not listing geopandas in `setup.cfg` for the examples.
=> Add flake8 requirements to linting

src/metpy/units.py
Pint has restructured and removed the `.unit` submodule. We were only using that to get around defining a percent unit, which works using standard syntax now--and we don't need to support older Pint versions
with our workaround any more.
=> Fix compatibility with future Pint

src/metpy/testing.py, src/metpy/units.py, tests/plots/test_skewt.py, tests/plots/test_station_plot.py, tests/units/test_units.py
"united" doesn't mean what we want it to in these contexts. Let's go with "unit-ed" at least. I am open to changing to things like "quantity with units" or...?
=> Remove "united" as meaning "having units"

.github/dependabot.yml
This configures Dependabot to check for GitHub Actions updates within our composite actions (which it supports now). Hopefully one day dependabot/dependabot-core#5137 is addressed and we can avoid listing ALL our actions, but this is at least a nice step forward that keeps us from getting out of date (which has actually caused us to miss a useful update to actions/cache@v3).
=> Configure dependabot for our composite actions

.github/actions/setup-proj/action.yml
With #2525 merged, we're properly storing the PROJ build into cache. This PR aims to fix loading that cache.
~Just as soon as I figure out what's wrong.~
EDIT: So the core problem is that apparently at some point the path that got cached was `~`. When you request based on a key, but with a different path, it helpfully just says "Nope didn't find it", but then when it tries to save it says "This already exists". Combined with the non-existent UI, it was essentially chance that I figured out what the problem was.
This PR changes from explicitly doing things relative to `~`/`$HOME` and instead just does it relative to the workspace directory, which is the default. This should keep this from happening in the future--I'm still not at all clear on how this happened.
This also bumps us to the …
=> Fix caching of PROJ build

.github/actions/install-pypi/action.yml
Tweak Shapely installation so that the dependencies it installs matches our desired versions *and* not force them to be built from source. This will hopefully reduce the *7* minutes we spend every CI installing Shapely.
Also eliminate updating `pip` and `setuptools`, it just seems superfluous since we're not relying on any new stuff there.
=> Shapely build

setup.cfg
Both Twitter and YouTube are [explicitly supported](https://github.com/pypi/warehouse/blob/39daea188d2e1e6494c50753cd48cb5a8da3e8c4/warehouse/templates/packaging/detail.html) by PyPI (Warehouse) with icons, and they seem like useful resources to feature on our PyPI page.
=> Add links to Twitter and MetPy Mondays on PyPI

src/metpy/io/_metar_parser/metar_parser.py
Whilst working on a METAR fix, I ran `canopy` locally and found its generated `metar_parser.py` had a rather hefty diff.  Perhaps it would be good to take this diff now to perhaps prevent any future PRs from having a non-atomic change included when they reran `canopy` too?  Shrug.
- Closes #xxxx
- Tests added
- Fully documented
=> rebuild metar_parser with canopy 0.4.0

src/metpy/io/metar.py, tests/io/test_metar.py
Prevents an invalidly encoded visibility with a 0 denominator from tripping up the METAR parser.  For example:
> KGYR 072147Z 12006KT 1/0SM FEW100 SCT250 41/14 A2992
Visibility is `np.nan` in this case.
PS.  I attempted to adjust the PEG parser to require a non-zero denominator, but that has a side effect of causing the entire METAR parsing to fail, so the valid cloud, temp, and pressure data is lost.
=> catch metar visibility with zero denominator

src/metpy/constants/default.py
Per an esupport ticket, the unit definition of our constants' `R_v` (and discovered `Cp_l` while in there) were inconsistent with the documentation and the values many might expect to see by default.
=> Fix inconsistent R_v and Cp_l unit definitions

src/metpy/plots/skewt.py
An internal method we use (to fix tight bboxes) was renamed in Matplotlib 3.6. Update the name and add an alias for older matplotlib versions.
This, together with us now using the recently released Cartopy 0.21, should fix all issues with nightly builds.
=> MNT: Update SkewXAxis for Matplotlib 3.6

examples/calculations/Absolute_Vorticity.py, examples/calculations/Advection.py, examples/calculations/Divergence.py, examples/calculations/QVector.py, examples/calculations/Shearing_Deformation.py, examples/calculations/Stretching_Deformation.py, examples/calculations/Total_Deformation.py, examples/calculations/Vorticity.py, examples/calculations/Wind_Speed.py, src/metpy/cbook.py, tests/test_cbook.py
This PR adds example calculations using fake data, which has been added to the cbook as a function. This was done to reduce the amount of code needed for each calculation to define the same data and put into an xarray format.
Examples included are:
- Vorticity
- Absolute Vorticity
- Shearing Deformation
- Stretching Deformation
- Total Deformation
- Divergence
- Wind Speed
- Advection
- Q-Vector
=> add 2D calculation examples

src/metpy/interpolate/grid.py, tests/interpolate/test_grid.py, tests/interpolate/test_interpolate_tools.py
`interpolate_to_grid`, due to an off-by-one error, was not actually generating grids with the requested resolution. Instead, they had one fewer point than that needed to generate the requested resolution. The previous implementation calculated the number of steps needed, but essentially omitted the starting point.
In order to avoid regenerating a bunch of test data, I adjusted the test to request a resolution matching the previous reality.
This also cleans up the documentation for some of those internal functions.
=> Fix resolution of grids generated by interpolate

tests/plots/test_declarative.py, tests/plots/test_skewt.py, tests/plots/test_station_plot.py
These tolerance bumps allow tests to pass in an osx-arm64 environment with testing Matplotlib. Some of the artifacts do seem non-spurious, notably across some contours and barbs. A shallow debug dive into Matplotlib's quiver/barb Python code didn't yield any immediate value differences in paths, lengths, etc. Here is probably the worst offender, in `test_nws_layout`; notice the edge of the farthest line on the barb:
We should hopefully aim to see this resolved and trim these tolerances again in the future.
=> Bump image test tolerance for osx-arm64

docs/_templates/overrides/metpy.calc.rst, src/metpy/calc/indices.py, tests/calc/test_indices.py
This pull request fixes #2094 by adding in the function for pressure-weighted vertical average from Holton 5th Edition 2012 page 86. The reference to Holton 2012 was also added into the references sheet.
=> Add mean pressure weighted equation

docs/_templates/overrides/metpy.calc.rst, src/metpy/calc/thermo.py, tests/calc/test_thermo.py
This PR implemented the convective condensation level (CCL), with options to use either the surface mixing ratio or the average mixing ratio over a shallow layer near the surface, according to the definition of CCL by [AMS](https://glossary.ametsoc.org/wiki/Convective_condensation_level). 
I also wrote a bunch of tests to make sure that what I implemented is correct using UWYO sounding. I can't find any existing software to compare my CCL calculations to, so I just eyeballed the desired values from the Skew-T diagrams. 
Sorry for creating a new PR -- it turns out that I messed up with git for the last PR, and opening a new one seems the best option.
=> Implement convective condensation level (CCL)

docs/conf.py, docs/userguide/startingguide.rst, examples/gridding/Natural_Neighbor_Verification.py, src/metpy/calc/basic.py, src/metpy/calc/kinematics.py, src/metpy/calc/thermo.py, src/metpy/calc/tools.py, src/metpy/calc/turbulence.py, src/metpy/cbook.py, src/metpy/interpolate/geometry.py, src/metpy/interpolate/grid.py, src/metpy/interpolate/one_dimension.py, src/metpy/interpolate/points.py, src/metpy/interpolate/slices.py, src/metpy/interpolate/tools.py, src/metpy/io/__init__.py, src/metpy/io/gempak.py, src/metpy/io/nexrad.py, src/metpy/io/station_data.py, src/metpy/plots/_mpl.py, src/metpy/plots/_util.py, src/metpy/plots/ctables.py, src/metpy/plots/skewt.py, src/metpy/plots/station_plot.py, src/metpy/plots/wx_symbols.py, src/metpy/testing.py, src/metpy/units.py, src/metpy/xarray.py
Had fun playing whack-a-mole to enable nitpicky for sphinx. This is going to be a good thing to have to clean up our docs, as it caught some legitimate typos and inconsistencies that were good to resolve. However, there are some remaining warnings that I can't seem to appease, and I don't necessarily want to throw them in `nitpicky_ignore`. If anyone has ideas about how to fix them let me know. 
The only one that should be silenced, but can't figure out how is `default: 'change'` with the apostrophes. I think I've tried every combo I know of ", ', and \'.
=> Enable sphinx nitpicky

src/metpy/interpolate/slices.py, src/metpy/units.py, src/metpy/xarray.py, tests/calc/test_thermo.py, tests/io/test_metar.py, tests/test_xarray.py, tests/units/test_units.py
Instead of blindly creating our own registry and using it, instead use the application registry and modify it to our needs. I'm not wild about modifying global objects shared by different libraries, but I think it is better than us insisting on our own registry--which has no hope of playing well with another library.
Also bumping our minimum Pint version to 0.11 to let us clean up some warning handling.
=> Use Pint Application Registry

src/metpy/io/metar.py
closes #2700
METAR is a horrible format that provides just a UTC day, so we have to make life choices to figure out what the month and year is for this day.  MetPy previously assumed a default year and month matching the current system localized date and not the current UTC date.
- ~~Tests added~~ 
- Fully documented
No idea how this can be tested outside of doing naugthy things to python's datetime module?
=> set default METAR year, month from UTC date

examples/Advanced_Sounding.py, examples/plots/Simple_Sounding.py
This "documents" how to change the default Skew-T axis labels. It intentionally shows one hard-coding the units, including the appropriate unicode syntax, as well as one using Pint to format it based on the input data. This way both approaches are out there for users to see.
This was motivated by a support question asking about this and noted that they (correctly) couldn't find any documentation.
=> Add axis labels to some sounding examples

tutorials/unit_tutorial.py
This will need to point to `https://pint.readthedocs.io/en/stable/user/nonmult.html` if/when they release with these doc changes; I believe they're still iterating for now.
Closes #2721
=> Point nonmult units link to pint stable

src/metpy/calc/thermo.py, src/metpy/calc/tools.py, src/metpy/cbook.py, src/metpy/interpolate/one_dimension.py, tests/interpolate/test_one_dimension.py
Fixes `inteprolate_1d` to properly handle the necessary broadcasting, at least for the source location (levels). I chose not to deal with broadcasting all source data since I think it's far less common and would require needing to manually do a bunch of unit manipulation.
This also tries to improve `broadcast_indices` to be at lease a bit more clear what it's doing (and reduces its call complexity).
=> Interpolate broadcasting

.github/actions/build-docs/action.yml, .github/workflows/backport-prs.yml
GitHub [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) the `set-output` command for security reasons. The [new way](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter) is to echo to `$GITHUB_OUTPUT`.
=> Remove use of deprecated set-output in actions

examples/gridding/Natural_Neighbor_Verification.py, src/metpy/interpolate/geometry.py
During a refactor (I did) the example was broken, in terms of the visual output. A use reported this recent in esupport BQP-167169. This restores what was incorrectly dropped in the refactor, as well as fixes up a bit of debris in the relevant function.
=> Fix Natural Neighbor Verification example

tests/plots/test_declarative.py
Looks like running against numpy 1.24.0rc1 has tweaked the starting point of the barbs by a pixel. Just bump the threshold here.
=> Bump image threshold

src/metpy/io/_metar_parser/metar_parser.peg, src/metpy/io/_metar_parser/metar_parser.py, tests/io/test_metar.py
As on the tin. Apparently this is a valid visibility for manual observations.
EDIT: Should clarify that 1/16, 3/16, and 5/16 are valid by the Federal Meteorological Handbook (and FAA handbook). This modifies the parser to just blindly allow a two-digit denominator.
=> Parse 1/16SM visibility in METARs

src/metpy/units.py
Pint 0.21 added a definition of percent so we don't need to define our own going forward.
=> Conditionally define percent unit

src/metpy/io/gempak.py, tests/io/test_gempak.py
Per discussion in #2759, the option to parse SPECI observations was made into a user parameter and is off by default.
This was the most reasonable approach to extracting METAR data that I could think of. Sometimes GEMPAK will also have the standard METAR data as text. If I parsed that, the timestamps would be more precise. However, as @sgdecker had alluded to, users do not want to have to dig for the top of the hour observations. You do have AWOS that do standard reports every 20 minutes, but those are going to be less susceptible to the GEMPAK file time bin issue than SPECI reports. Unless there is a strong desire to also have the ability to parse standard observation text, then this should work for most people.
=> Change default SPECI parsing

src/metpy/xarray.py, tests/test_xarray.py
We intentionally want to assume degrees for our various lat/lon handling with e.g. `lat_lon_grid_deltas`, but for xarray we by default were giving 'dimensionless' units when no unit attribute is present (which can happen when attributes are dropped by various xarray functionality).
See also #2811, #2836, and #2848.
The solution here ended up being more clean than I feared. (cc @jthielen)
=> Ensure degree units by default for lat/lon in xarray

src/metpy/calc/thermo.py
Adds a note that virtual temperature may be used as input to the `density` function and rewrites the mathematical expression to put it in terms of the inputs to this function.
=> Clarify density documentation

examples/gridding/Point_Interpolation.py, src/metpy/calc/indices.py
* Fix typo in "Point Interpolation" example (#2970)
* Make some improvements to the `mean_pressure_weighted` docstring based on [these](https://stackoverflow.com/questions/69045234/calculation-of-the-mean-pressure-weighted-function/6912380) Stack Overflow [questions](https://stackoverflow.com/questions/75848644/metpy-get-layer-returns-only-the-the-first-three-values/75859722)
* Clean up some formatting in the `weighted_continuous_average` docstring
=> A few doc fixes

ci/requirements.txt
Xarray only supports pandas 2 on current `main`, so that will require a new release. conda-forge patched metadata and now there's no environment to resolve with xarray + pandas v2. With xarray dropping 3.8, we'll have to follow suit for in order to enable pandas 2 on CI as well (still not enough IMO to do this for the next release).
=> CI: Roll back to Pandas 1.5.3

.github/dependabot.yml
The "dependabot" tab on GitHub flagged "setup-proj" as not found, which makes sense since we deleted this awhile ago.
=> CI: Remove deleted setup-proj action from dependabot

src/metpy/units.py, tests/units/test_units.py
The issue has arisen with older model output data where the stored vorticity unit is `/s`, which will then fail on any action with a unit with the error `pint.errors.DefinitionSyntaxError: missing unary operator "/"`. This solution adds a small fix in the units module to replace `/s` with `s**-1`. An example dataset that this occurs with is older GFS data available through the RDA archive.
Minimum example to produce error:
```python
from datetime import datetime
from metpy.units import units
import xarray as xr
ds = xr.open_dataset('https://rda.ucar.edu/thredds/dodsC/aggregations/g/ds083.2/1/TP')
ds.Absolute_vorticity_isobaric.metpy.sel(time=datetime(2000, 1, 4, 12), vertical=500*units.hPa).metpy.quantify()
```
=> unit redefinition help for /s

src/metpy/calc/thermo.py
The example for this function accidentally got placed in the middle of the Returns section. Also expand out the multiple returns to be more in-line with how we usually do it.
=> Fix formatting of "Returns" from most_unstable_parcel

.github/workflows/release.yml
Instead of using a fixed, shared API secret key, you [configure a GitHub actions workflow](https://docs.pypi.org/trusted-publishers/) (and environment) on PyPI to be allowed to publish to the project. Through this GitHub and PyPI exhange short-lived tokens for publication. Thankfully this is automatic when using the [PyPA publication action](https://github.com/pypa/gh-action-pypi-publish#trusted-publishing) that we've already been using.
I've already deactivated the previous API key (which was tied to my personal PyPI account) and removed it from our GitHub configs. Another benefit of this is that everything is tied to project infrastructure rather than individual users.
I've already configured our PyPI project to use our GitHub actions workflow and environment.
=> CI: Swap over to PyPI trusted publishing

src/metpy/plots/mapping.py, tests/plots/test_mapping.py
The problem is that the original GEMPAK CED and MCD ([modified] cylindrical equidistant) projections, while supported by PROJ, aren't defined in the CF metadata spec (as of 1.10). This is a work-around that makes __str__ not fail, and gives a better error, when CFProjection is given a set of metadata it can't handle.
This fixes the notebook experience so that just trying to print/take a repr doesn't result in errors. Fixing plotting is out of scope because I'm loath to try add things that aren't supported by the CF spec within our "CFProjection" class. I'm actually not even sure what the right one to use in Cartopy would be.
=> Improve GEMPAK "thinned GFS" files

src/metpy/calc/indices.py, tests/calc/test_indices.py
From recent discussions and https://github.com/Unidata/MetPy/issues/2092#issuecomment-1487738864, a quick update to use `weighted_continuous_average` in `bunkers_storm_motion` for the layer wind averages instead of `np.mean`. Opening this up to any discussion before updating any test values (and making sure a small change works back to Minimum.)
=> Use weighted_continuous_average in bunkers_storm_motion

ci/test_requirements.txt, pyproject.toml, src/metpy/calc/thermo.py, tests/calc/test_thermo.py
The scipy solver doesn't raise an error, but has some return codes that indicate success or failure. Use these to raise an appropriate error in that case. This avoids confusing behavior in downstream calculations, like parcel_profile.
=> BUG: Raise error in moist_lapse on solver fail

pst-versions.json
Enables #2974 to pass and go in. After release we can update this to generate via workflow a la `versions.json`. These two will need to separately exist until we stop "supporting" doc versions using the old version switcher.
=> DOC: manually add PST version json

src/metpy/io/__init__.py, src/metpy/io/text.py
The code to export and set __all__ was missing. The function was still available from the * import, but it wasn't showing up properly in the docs.
=> Export parse_wpc_surface_bulletin

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
EL and LFC are functions that take a pressure profile, temperature profile, dewpoint profile, and an optional parcel temperature profile. When a missing value (np.NaN) is found in any of the profiles, the data point is removed, along with the data point at that level in _all_ the other profiles as well.
A bug described in #2921 shows that a missing value in any of the ambient profiles did not lead to the removal of a data point in the optional parcel temperature profile (when the user chose to provide that optional profile).
This PR introduces some rearrangements to the EL and LFC calculations to resolve that issue. Four new tests for NaN values in these calculations are also added.
=> Adjust user-provided parcel temperature profile for NaN values in EL and LFC

src/metpy/calc/kinematics.py
Improves the documentation of `mpcalc.advection`.
=> Improve advection docstring

src/metpy/interpolate/one_dimension.py, tests/interpolate/test_one_dimension.py
When given a DataArray and a numpy array, neither with units, a Quantity would be passed into the core calculation, triggering an exception on `apply_along_axis`. Instead, handle trying to convert and drop units on a "dimensionless" Quantity, since that's what we get for a DataArray with no units.
=> Fix interpolation with mixed types

.github/workflows/docs-conda.yml, .github/workflows/docs.yml, .github/workflows/tests-conda.yml, .github/workflows/tests-pypi.yml, README.md, ci/requirements.txt, docs/index.rst, docs/userguide/installguide.rst, pyproject.toml, src/metpy/interpolate/one_dimension.py, src/metpy/io/gempak.py, src/metpy/plots/_util.py, src/metpy/plots/ctables.py, src/metpy/plots/wx_symbols.py
* Declare supported Python as >=3.9
* Remove 3.8 from CI builds
* Remove no-longer-needed `importlib_resources`
* Run `pyupgrade --py39-plus`
* Bump minimum versions for Python 3.9 support
- Numpy 1.20.0
- Scipy 1.6.0
- PyProj 3.0.0
- Pandas 1.2.0
* Clean up some lingering work-arounds for Python 3.11 in CI configs
* Update `interpolate_1d` to use `np.broadcast_shapes` since we're now on numpy >=1.20
This paves the way to rebase and merge a bunch of dependabot updates.
=> Drop Python 3.8

src/metpy/constants/default.py
Updates units for dry adiabatic lapse rate `Quantity` from 'K * kg * m / J / s **2' to 'K / km'.
=> Practical units for dry adiabatic lapse rate constant

tutorials/unit_tutorial.py
Added short string formatting section with examples (pretty, compact, combined with float precision) to unit_tutorial.py.
=> Add string formatting information to unit tutorial

src/metpy/calc/thermo.py
Update the docstring of `ccl`, `el`, and `lfc` to reflect that `pressure` should be monotonically decreasing.
=> Update CCL/EL/LFC docstring to reflect that pressure should be monotonically decreasing

.github/dependabot.yml
Dependabot now has support for [grouping](https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/) dependencies for PRs. This adds a group for flake8 and friends, since they generally need to go in together. This should allow a single PR that stands a chance of working.
=> Add a dependabot group for flake8 and friends

tests/calc/test_thermo.py
Original patch form Bas Couwenberg <sebastic@debian.org>. See https://salsa.debian.org/debian-gis-team/metpy/-/blob/7a187608c6a65a2f6686fb11ad286913a9b979cb/debian/patches/arm64.patch
Fixes a test failure on arm64.
Issue detected in debian/sid.
See also https://ci.debian.net/data/autopkgtest/testing/arm64/m/metpy/36313527/log.gz
```
149s ============================= test session starts ==============================
149s platform linux -- Python 3.11.4, pytest-7.4.0, pluggy-1.2.0
149s Matplotlib: 3.6.3
149s Freetype: 2.13.0
149s Dep Versions: Matplotlib 3.6.3, NumPy 1.24.2, Pandas 1.5.3, Pint 0.19.2, Pooch v1.7.0
149s 	PyProj 3.6.0, SciPy 1.10.1, Traitlets 5.5.0, Xarray 999
149s rootdir: /tmp/autopkgtest-lxc.r4cyxgxh/downtmp/autopkgtest_tmp/build
149s plugins: mpl-0.0.0
149s collected …
```
=> Use xfail for test that doesn't fail on arm64.

src/metpy/calc/indices.py, tests/calc/test_indices.py
This fixes bunkers storm motion returning nan when given a nan in the input data. 
I don't believe any documentation is necessary for this as it is not documented in other functions that remove nans automatically.
=> remove nans from bunkers input

.github/workflows/cffcheck.yml, .github/workflows/docs-conda.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/tests-conda.yml, .github/workflows/tests-pypi.yml, .github/workflows/unstable-builds.yml
* Remove redundant specification of default fetch-depth
* Eliminate manual fetching of tags since actions/checkout v3.6.0 now has `fetch-tags` as an option
=> Checkout updates

examples/Complex-Sounding-Plot.py, examples/Skew-T_Advanced-Layout.py
Adds a more advanced Skew-T layout example to `examples\`. Closes issue #2460. Uses the existing `Advanced_Sounding.py` example to build into a more complex plot. The same imports needed for the aforementioned existing example are used in this new example. Some simple adjustments and additions, mostly through Matplotlib manipulation, help improve the readability and complexity of the base MetPy functionality. 
This example produces this plot from MetPy test data:
=> Add Complex Sounding Layout Example

src/metpy/io/nexrad.py
=> ENH: Move xdrlib inside metpy

src/metpy/io/station_data.py, tests/io/test_station_data.py
This PR seeks to fix issue #2872 by explicitly declaring the type of the latitude and longitude columns of the Pandas DataFrame that gets returned when using the `add_station_lat_lon` function.
=> define dtype for station info lat-lon

pyproject.toml
The `tools` (as opposed to `tool`) table is not valid in `pyproject.toml`. Doesn't look like we'd gain anything from correctly specifying `zip-safe` and `platforms`.
setuptools was also [automatically discovering](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#auto-discovery) our project layout since `where` was inappropriately considered. I've removed all these; I'm glad to re-add `where` correctly if we feel the explicitness helps.
=> Remove unused setuptools config

.codecov.yml, .github/actions/run-tests/action.yml, .github/workflows/tests-conda.yml, .github/workflows/tests-pypi.yml
Switch CodeCov upload to use its own job on GitHub Actions rather than as a step after running tests. This effectively batches the upload after running the Conda/PyPI tests. This should reduce the number of calls, putting less stress on the system (the error is about API calls) and result in fewer opportunities to fail. It also makes it easier to retry just the upload with no need to re-run the tests.
Inspired by cylc/cylc-flow#5459.
=> Move codecov upload to a separate job

tests/calc/test_thermo.py, tests/interpolate/test_geometry.py, tests/plots/test_declarative.py, tests/plots/test_patheffects.py
This gets the suite passing on my M2. There are a couple contour tests that need a higher threshold for some reason, but manual inspection confirms tests are behaving as expected.
Need to fix a couple other tests.
=> Make tests pass on macOS M2

pyproject.toml, src/metpy/calc/thermo.py, src/metpy/units.py, tests/calc/test_thermo.py
Standardize RH calculations on [WMO8](https://library.wmo.int/viewer/41650/download?file=8_I_2021_en.pdf&type=pdf&navigator=1) definition of relative humidity as
$$ RH = \frac{e}{e_s} $$
(eq 4.A.15)
such that any RH calculation with input of mixing ratio is made consistent with above as
$$ RH = \frac{w}{w_s} \frac{\epsilon + w_s}{\epsilon + w} $$
(eq 4.A.16)
As part of this process, we can also simplify `dewpoint_from_specific_humidity` to not require a temperature input. I've tried to do this in a way that allows arg and/or kwarg specification in a backwards compatible way. @dopplershift let me know your thoughts on the verbage here and how to best document this change and alert to an eventual deprecation. This does break our "check for versionchanged 1.0 and provide helpful error" …
=> Standardize RH calcs on WMO8

.github/actions/install-pypi/action.yml, .github/workflows/docs-conda.yml, .github/workflows/docs.yml, .github/workflows/nightly-builds.yml, .github/workflows/tests-conda.yml, .github/workflows/tests-pypi.yml, .github/workflows/unstable-builds.yml, docs/api/references.rst, docs/conf.py, docs/make_areas.py, pyproject.toml, src/metpy/io/_tools.py
* Add 3.12 to CI and to package metadata
* Fix metpy import failure on 3.12 due to now inability to effectively subclass `Struct` (python/cpython#94532)
* Fix Codecov not failing CI job when upload fails
* Make sure nightly workflow runs on a PR if we change the underlying "unstable" workflow
* Other CI workflow cleanup
=> Support Python 3.12

docs/_static/theme-unidata.css, docs/conf.py, docs/index.rst, docs/userguide/index.rst, examples/plots/surface_declarative.py, src/metpy/units.py
Fix theme styling, remove the unhelpful doc source link and add source links throughout, and add some calendar links to shout out our dev call.
=> DOC: Theme fixes, source links, and calendar

src/metpy/calc/basic.py, tests/calc/test_basic.py
This pull request updates the heat_index calculation to return the same units as the temperature used in the calculation. This change ensures parity across similar equations like wind_chill and apparent_temperature where the return value has the same units as the input temperature.
=> return heat_index with temperature units

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
A duplicate-level check is added, using the same approach as in `_parcel_profile_helper`.
=> Check for duplicate levels in isentropic_interpolation_as_dataset

CONTRIBUTING.md
As indicated in #3321, sometimes `make clean html` fails.  In those instances, `make cleanall html` may work, so this commit provides that additional information in the Contributor's Guide.
=> Provide alternate recipe to build docs

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
This addresses some limitations in `isentropic_interpolation` and `isentropic_interpolation_as_dataset` identified in #3315, which is trying to use the functionality on WRF output natively on a sigma vertical coordinate.
* Don't blindly assume that the vertical coordinate is pressure in `isentropic_interpolation_as_dataset` but check the dimensionality and issue a more useful `ValueError`
* Tweak the handling of pressure in `isentropic_interpolation` to work with a *passed-in* 3D pressure field, since internally we were already using a 3D pressure field
* Allow `isentropic_interpolation_as_dataset` to work with data on non-pressure coordinates by accepting a `pressure` kw-only argument in this case, which overrides using the vertical coordinate.
*
=> Improve isentropic interpolation

src/metpy/calc/thermo.py
Adapt example from [comment](https://github.com/Unidata/MetPy/issues/3279#issuecomment-1813045844) in #3279 to update docstring example to use mixed parcel, and update docstring to highlight that as common use in Lifted Index.
=> Update LI docs to reference and demonstrate mixed parcel usage

tests/calc/test_basic.py
Apparently with Pandas 2.2.0 (tested with the just released rc0) freq='H' is deprecated, in favor of freq='h'. Since this works across our versions, go ahead and change.
Otherwise we see:
```
=================================== FAILURES ===================================
_______________________ test_smooth_window_1d_dataarray ________________________
def test_smooth_window_1d_dataarray():
"""Test smooth_window on 1D DataArray."""
temperature = xr.DataArray(
[37., 32., 34., 29., 28., 24., 26., 24., 27., 30.],
dims=('time',),
>           coords={'time': pd.date_range('2020-01-01', periods=10, freq='H')},
attrs={'units': 'degF'})
tests/calc/test_basic.py:712: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
=> Avoid pandas warning

docs/_templates/overrides/metpy.calc.rst, docs/api/references.rst, examples/calculations/Sounding_Calculations.py, src/metpy/calc/thermo.py, tests/calc/test_thermo.py
Adds calculation for [Galvez-Davison Index for tropical convection](https://www.wpc.ncep.noaa.gov/international/gdi/).
- Docstrings (src and test)
- Added function to `/docs/_templates/overrides/metpy.calc.rst`
- Added function example to `/docs/examples/calculations/Sounding_Calculations.py`
This is all visible in the changelist but wanted to document the things I had to change. I didn't see any of this in the Contributor's Guide, ideally we can add it under documentation to make it easier for contributors to document future feature additions.
=> Add Galvez-Davison Index calculation

.gitignore, src/metpy/interpolate/slices.py, tests/interpolate/test_slices.py
The fixup in #3255 inadvertently added unit parsing to all code paths in `interpolate_to_slice`. This breaks any usages that passed in data with unknown units, such as dBZ with pyart. Since `interpolate_to_slice` has no need to do any unit handling, avoid this unless we're actually given a quantity.
Also update `.gitignore` for a new file being spit out by sphinx-gallery (or at least new outside the existing ignored directories).
=> Fix interpolate_to_slice unit handling

src/metpy/units.py, tests/units/test_units.py
Fixes #3341 
Adds "dBZ" as a unit within the unit registry, with this being equivalent to dB, while still being its own separate unit.
=> ENH: Add dBZ as a unit in the registry

tests/calc/test_basic.py, tests/calc/test_thermo.py, tests/units/test_units.py
Broken currently on Pint git (See #3368). Don't rely on the string representation of dimensionless quantities, but rely on proper object equality. This is better regardless of whether it represents a long-term change for Pint, since `units('dimensionless') == units('')`.
=> Fix checking dimensionless units in tests

src/metpy/_version.py
Try to avoid pulling in setuptools_scm for better import time by directly checking for a pip file that indicates whether the install is editable and only using the git-based version in that case; otherwise, depend on the distribution metadata.
Alternative to #3363.
=> Update version detection

.github/actions/build-docs/action.yml, docs/conf.py
1. Make use of the `DOC_VERSION` variable we already set in CI, and use this to override what `conf.py` finds from version. CI can determine, based on being on not-a-PR and not-on-main that it's not a dev build.
2. The version switcher should not have a leading "v" on the match, because we put the "v" only on the name (not matched), not the version.
=> Fix version for docs on maintenance branch

docs/userguide/gempak.rst
@jthielen's CSS fix is applied to the GEMPAK Comparison Guide, and some text from the days prior to #2743 is cleaned up.
=> Clean up GEMPAK Comparison Guide

src/metpy/calc/basic.py, src/metpy/calc/tools.py
Add simple examples in the doc strings of a couple of funtions
=> Doc: wind examples

src/metpy/xarray.py, tests/test_xarray.py
This works around an issue where some ERA5 data had lat/lon with a "positive" attribute that, according to the CF specification, should indicate a vertical coordinate. We can fix this up by making sure each coordinate variable is only associated with a single option, and making use of Python's key-ordered dictionaries to prioritize the matching order. Having lat be y and lon be x is already handled by a later block.
=> Make coordinate detection more robust

src/metpy/calc/tools.py, tests/calc/test_calc_tools.py
=> angle_to_direction handle ndarray

src/metpy/calc/indices.py, src/metpy/calc/thermo.py, src/metpy/calc/tools.py, src/metpy/testing.py, tests/calc/test_thermo.py, tests/plots/test_declarative.py
Various changes to get things to work without warnings/errors on numpy 2 since I was able to put together a local pip-based numpy 2 environment. Mostly avoiding a `DeprecationWarning` for using `trapz` instead of `trapezoid`, otherwise a bunch of silly stuff. This includes an error caught by Matplotlib 3.9.0rc2, which I'm not at all clear why didn't flag on the nightly build (though it had other image-based failures). 
This PR (plus hgrecco/pint#1971) leaves us with 4 failing tests. 2 seemingly due to some xarray+cartopy challenges:
<details><pre>
___________________________________________________________________________________________________________ test_declarative_events ___________________________________________________________________________________________________________
args …
=> Numpy 2 compatibility

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
Fix galvez_davison_index error when missing data at 950 hPa. In raise ValueError at:
`f'\n{np.max(pressure, axis=0)[indices_without_950]}'` 
It show error message: "invalid index to scalar variable". This cause from [indices_without_950] behind the np.max().
=> Fix galvez_davison_index error: invalid index to scalar variable

ci/requirements.txt, examples/meteogram_metpy.py, src/metpy/calc/thermo.py, src/metpy/plots/declarative.py, tests/plots/test_declarative.py
As it says above.
* One last commit to clean up a problem with `DataArray` "scalars" not working with linspace (done by cartopy for imshow).
* Fix `meteogram_metpy.py` for numpy 2--no longer need manual `decode()` call
* Tweak image threshold ever so slightly (0.031->0.033) due to some small change with numpy2
* Adjust example expected text output for numpy 2 (include `np.int64()`).
=> Bump to numpy 2

examples/Advanced_Sounding_With_Complex_Layout.py
As I was working with someone on creating a sounding and calculating the different CAPE values who had started with this example code, we noticed that the MLCAPE value seemed off. It turns out that in this example, the parcel profile was used for the dew point temperature in the mixed-layer calculation. In the example itself there would not be much difference in the computed value (likely why it was missed), but happen to be fairly large in the case they were looking at.
Anyway, simple fix to update this wonderful example.
=> fix wrong input to function

docs/devel/infrastructureguide.rst
As it says in the title. Looks like the setuptools-scm was renamed to use a hyphen.
* Closes #3473 finally
=> Update redirecting link

src/metpy/calc/tools.py, src/metpy/interpolate/geometry.py, src/metpy/interpolate/points.py
SciPy 1.6 merged cKDTree and KDTree, with the former name now an alias for the latter.
=> MNT: Replace cKDTree with KDTree.

src/metpy/xarray.py, tests/test_xarray.py
This support was added in pydata/xarray#2844 and handles converting the `grid_mapping` variable to a coordinate in xarray itself, which was incompatible with some assumptions in `parse_cf()`. Add some handling for the case where the grid_mapping. Also add `decode_coords='all'` to our full test suite (parametrized) and adjust a few tests as necessary; this includes removing a test for not removing `grid_mapping` attribute since that's not a universal truth any more (beyond our control).
This is motivated by being compatible with rioxarray, which relies on `decode_coords='all'` for its own projection handling, and can be used to load GOES data and do direct image remapping.
=> Fix xarray support with decode_coords='all'

.github/actions/build-docs/action.yml, .github/actions/install-pypi/action.yml, .github/actions/run-tests/action.yml, .github/workflows/docs.yml, .github/workflows/tests-pypi.yml
These changes keep MetPy's functionality as is, but allows Siphon to re-use these actions.
=> Tweaks to internal actions

.github/workflows/docs-conda.yml, .github/workflows/docs.yml, .github/workflows/tests-conda.yml, .github/workflows/tests-pypi.yml, .github/workflows/unstable-builds.yml, ci/requirements.txt, docs/conf.py, pyproject.toml, src/metpy/calc/tools.py
Officially support Python 3.13:
* Add CI jobs for 3.13
* Update package metadata
* Bump Pint to 0.24.4
* Fix up our dynamically generated docstrings to be consistent with the indentation of the rest of the docstring, since 3.13 now strips leading whitespace from docstrings.
=> Python 3.13 Support

docs/userguide/gempak.rst
Currently, the row in the GEMPAK Conversion Guide referencing the MAG function points to `numpy.linalg.norm`, but the actual NumPy equivalent is `numpy.hypot`.  This commit updates the documentation accordingly.
=> Fix MAG entry in GEMPAK Guide

.github/workflows/assign-milestone.yml, .github/workflows/automerge-dependabot.yml, .github/workflows/backport-prs.yml, .github/workflows/cffcheck.yml, .github/workflows/code-analysis.yml, .github/workflows/docs-conda.yml, .github/workflows/docs.yml, .github/workflows/linting.yml, .github/workflows/release.yml, .github/workflows/tests-conda.yml, .github/workflows/tests-pypi.yml, .github/workflows/unstable-builds.yml
In light of a recent supply chain attack on Ultralytics that leveraged some template expansion vulnerabilities in some GitHub Actions, this addresses some issues found by the zizmor tool:
* Drop credentials after running `actions/checkout` whenever we don't need more git work
* Move permissions into individual jobs, rather than at the top of the workflow. Most using special permissions only have a single job, but this does change the docs workflow to only have `contents: write` for deploy (removing from build)
* Expand some PR parameters into intermediate environment variables to avoid template injection attacks
=> GHA security cleanup

docs/_templates/overrides/metpy.calc.rst, docs/api/references.rst, docs/conf.py, src/metpy/calc/thermo.py, src/metpy/constants/__init__.py, src/metpy/constants/default.py, src/metpy/constants/nounit.py, src/metpy/units.py, tests/calc/test_thermo.py
Taking recommendations from [community input](https://github.com/Unidata/MetPy/issues/626#issuecomment-1623569058), these calculations introduce temperature and moisture dependence to relevant "constant" quantities for use in upcoming analytic saturation vapor pressure and LCL calculations.
Beyond code review, specifically requesting feedback on function names and useful tests I might've missed. Will start playing around with satvap and LCL shortly this holiday!
=> Moisture/temperature dependent gas constants & latent heat

examples/calculations/QVector.py, src/metpy/calc/kinematics.py
With the final discussion in #3689, this tries to improve the documentation to make clear the option to pass in `static_stability`, as well as the relationship to various GEMPAK functions.
=> Fix q_vector units w/ default static stability

src/metpy/calc/tools.py
Since results could vary based on the method used to calculate the Laplacian of the field, it may be a good idea to refer to the method used to calculate the Laplacian of a field as discussed here #3458
=> add more information about the laplacian function

src/metpy/calc/turbulence.py, tests/calc/test_turbulence.py
As discussed in #3756, the turbulence kinetic energy calculation was incorrectly taking the square root of the squares of the perturbation velocity components.  The tests were also updated to use new, non-zero mean velocity components. A new, separate test was added to testing the tke calculation when perturbation velocities were supplied to the function.
=> BUG: Fix turbulence kinetic energy calculation (Fixes #3756)

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
When e_s >= p, we're outside liquid phase equilibrium and saturation mixing ratio is undefined. Instead of returning negative values in this case, warn and return NaNs for these cases. Fixes a problem found in #3751.
=> Avoid returning negative saturation mixing ratios

src/metpy/calc/thermo.py, tests/calc/test_thermo.py
This PR has 2 bug fixes for deriving parcel mixing ratio in `metpy.calc.thermo.cape_cin`.
1. Below the LCL, set the parcel mixing ratio to a constant value equal to the mixing ratio at the surface. _Do not use the pressure and dewpoint above the surface._ 
2. Above the LCL, use the _parcel_ temperature to derive parcel mixing ratio, _not the environmental temperature._ 
I noted this because this led to a negative mixing ratio when analyziing a test case sounding for [CM1](https://www2.mmm.ucar.edu/people/bryan/cm1/soundings/).
[input_sounding_jordan_allmean](https://www2.mmm.ucar.edu/people/bryan/cm1/soundings/input_sounding_jordan_allmean): West Indies annual mean (Jordan, 1958, J. Meteor., p. 91)
in which the top level of the sounding is 40000 m, the potential temperature is 1095 K, the …
=> Use parcel prof for parcel mix ratio

src/metpy/plots/mapping.py, src/metpy/xarray.py, tests/test_xarray.py
Instead of just assuming we should fall back to the geostationary perspective_point_height support, check to see if that attribute is even available, otherwise there's no point in trying.
This wasn't done in the first place because it wasn't clear there were other projections with valid coordinates that couldn't be converted to meters.
=> BUG: Fix handling rotated pole (lat/lon) parsing

.github/workflows/docs.yml
We were handling management of latest symlink and version information for docs using a workflow on gh-pages directly. This unfortunately does not automatically work due to GHA limitations on actions triggering more actions. Instead, just add version management to our docs workflow and run after deployment on appropriate versions.
=> Fix doc version handling on deployment

.github/workflows/automerge-dependabot.yml
This will allow the merged PR to trigger CI for main, which is important in order to have any coverage information for main (for later PRs).
=> Use app token for Dependabot auto-merge

benchmarks/Jenkinsfile
The argument for the deploy key was incorrect in the last version of the Jenkinsfile. This should be correct
=> Update Jenkinsfile - using withCredentials correctly for a deploy key

benchmarks/Jenkinsfile
Ok, we tested this one on a fake pipeline so this should really probably maybe if we're lucky work.
Long story short, Jenkins knew the SSH key but wasn't actually using it in the push which made GitHub think it was an imposter. This has been fixed with this PR.
=> Forcing Jenkins to actually use the ssh key

src/metpy/xarray.py
In xarray v2025.08.0 a `FutureWarning` has been introduced in the `xarray.merge` function to inform the users that the default value for the `compat` keyword argument will change in the future.
See https://github.com/pydata/xarray/commit/d237a712b7cbebf99ae8bc3149cd0c5f9dbddc6e.
The patch just modifies the current call to `xarray.merge` to pass explicitly the the current default value of `compat`.
=> Silence FututreWarning raised by xarray v2025.08.0

src/metpy/calc/tools.py, src/metpy/io/gini.py, src/metpy/plots/text.py
These were flagged as invalid codes by ruff. They seem to be related to older flake8 plugins that are no longer in use. Most importantly, removing them doesn't yield any lint errors.
This leaves some I900 lines flagged by ruff that are needed for flake8-requirements.
=> Remove unneeded noqa comments
